### PR TITLE
Add Osmosis to IBC setup

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnc0l0-X6f-aVZgg7K:-NOnc0l0-X6f-aVZgg7L:bx5qx70) (no related file):*
If I run `crust znet --profiles=ibc` there exists a running osmosis chain. but the states are not getting synced up between the chains. running the following only gives one chain state
`cored q ibc client states`

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnc0l0-X6f-aVZgg7K:-NOnef7QDVQjdvI_hj5u:bj7s5vf) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If I run `crust znet --profiles=ibc` there exists a running osmosis chain. but the states are not getting synced up between the chains. running the following only gives one chain state
`cored q ibc client states`
</blockquote></details>

You need to wait like 5+ minutes for the process to complete

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnc0l0-X6f-aVZgg7K:-NOneoMCB-ZMq6Vp4Pdu:b-h7sg7z) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You need to wait like 5+ minutes for the process to complete
</blockquote></details>

you may observe logs produced by relayer in container

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnc0l0-X6f-aVZgg7K:-NOneuTZ4Tb0k7Jp1jO1:b-pysclh) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may observe logs produced by relayer in container
</blockquote></details>

I have waited more than 5 min, regardless of the logs, the final out come should be client state being updated. are they using a different relayer and hence a different relaying logic ?

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/osmosis/run.tmpl` line 25 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnfhHA0Xi8wjAxbwmx:-NOnfhHB9miQaNpaknWM:b-hpi5nn) ([raw file](https://github.com/CoreumFoundation/crust/blob/e3907465a337630092f7707f19f710ed145380d4/infra/apps/osmosis/run.tmpl#L25)):*
> ```
> 
> # fund the validator and relayer accounts
> osmosisd add-genesis-account $(osmosisd keys show validator -a $KEYRING_FLAGS) 100000000000stake
> ```

maybe the issue is the stake denom here, the stake denom is probably not a valid fee paying denom in osmosis.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnc0l0-X6f-aVZgg7K:-NOngFec4Uih0rmhoK1l:b-4kbojo) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have waited more than 5 min, regardless of the logs, the final out come should be client state being updated. are they using a different relayer and hence a different relaying logic ?
</blockquote></details>

will check it, no both are connected by the same relayer instance

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnc0l0-X6f-aVZgg7K:-NOo5AWYDJxjjv6wmKKg:bdx4ntd) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

will check it, no both are connected by the same relayer instance
</blockquote></details>

This is what I get:

```
client_states:
- client_id: 07-tendermint-0
  client_state:
    '@type': /ibc.lightclients.tendermint.v1.ClientState
    allow_update_after_expiry: true
    allow_update_after_misbehaviour: true
    chain_id: gaia-localnet-1
    frozen_height:
      revision_height: "0"
      revision_number: "0"
    latest_height:
      revision_height: "13"
      revision_number: "1"
    max_clock_drift: 600s
    proof_specs:
    - inner_spec:
        child_order:
        - 0
        - 1
        child_size: 33
        empty_child: null
        hash: SHA256
        max_prefix_length: 12
        min_prefix_length: 4
      leaf_spec:
        hash: SHA256
        length: VAR_PROTO
        prefix: AA==
        prehash_key: NO_HASH
        prehash_value: SHA256
      max_depth: 0
      min_depth: 0
    - inner_spec:
        child_order:
        - 0
        - 1
        child_size: 32
        empty_child: null
        hash: SHA256
        max_prefix_length: 1
        min_prefix_length: 1
      leaf_spec:
        hash: SHA256
        length: VAR_PROTO
        prefix: AA==
        prehash_key: NO_HASH
        prehash_value: SHA256
      max_depth: 0
      min_depth: 0
    trust_level:
      denominator: "3"
      numerator: "1"
    trusting_period: 1540800s
    unbonding_period: 1814400s
    upgrade_path:
    - upgrade
    - upgradedIBCState
- client_id: 07-tendermint-1
  client_state:
    '@type': /ibc.lightclients.tendermint.v1.ClientState
    allow_update_after_expiry: true
    allow_update_after_misbehaviour: true
    chain_id: osmosis-localnet-1
    frozen_height:
      revision_height: "0"
      revision_number: "0"
    latest_height:
      revision_height: "26"
      revision_number: "1"
    max_clock_drift: 600s
    proof_specs:
    - inner_spec:
        child_order:
        - 0
        - 1
        child_size: 33
        empty_child: null
        hash: SHA256
        max_prefix_length: 12
        min_prefix_length: 4
      leaf_spec:
        hash: SHA256
        length: VAR_PROTO
        prefix: AA==
        prehash_key: NO_HASH
        prehash_value: SHA256
      max_depth: 0
      min_depth: 0
    - inner_spec:
        child_order:
        - 0
        - 1
        child_size: 32
        empty_child: null
        hash: SHA256
        max_prefix_length: 1
        min_prefix_length: 1
      leaf_spec:
        hash: SHA256
        length: VAR_PROTO
        prefix: AA==
        prehash_key: NO_HASH
        prehash_value: SHA256
      max_depth: 0
      min_depth: 0
    trust_level:
      denominator: "3"
      numerator: "1"
    trusting_period: 1540800s
    unbonding_period: 1814400s
    upgrade_path:
    - upgrade
    - upgradedIBCState
pagination:
  next_key: null
  total: "0"
```

Looks like both chains are connected

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/osmosis/run.tmpl` line 25 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOnfhHA0Xi8wjAxbwmx:-NOo5S7c6Ca2HALtBBkk:bhnby1l) ([raw file](https://github.com/CoreumFoundation/crust/blob/e3907465a337630092f7707f19f710ed145380d4/infra/apps/osmosis/run.tmpl#L25)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

maybe the issue is the stake denom here, the stake denom is probably not a valid fee paying denom in osmosis. 
</blockquote></details>

I tried with `osmo` and got errors, they use `stake` in their default genesis

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`infra/apps/osmosis/osmosis.go` line 1 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOt-CgXEHmWNuXCLige:-NOt-CgXEHmWNuXCLigf:bcdjqs9) ([raw file](https://github.com/CoreumFoundation/crust/blob/e3907465a337630092f7707f19f710ed145380d4/infra/apps/osmosis/osmosis.go#L1)):*
> ```Go
> package osmosis
> ```

I disagree with approach taken here.

osmosis.go & gaia.go are almost identical except some chain specific parts:


Also run.tmpl are also mostly the same 

IMO we should define a single generic pkg for IBC chains which contains all common code and then have separate folders/files defining configs specific for each chain.

In this way adding new chains in the future will be much simpler and require less copy-paste

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/osmosis/osmosis.go` line 1 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NOt-CgXEHmWNuXCLige:-NP2-jyUEj1dJHoVwmmc:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/e3907465a337630092f7707f19f710ed145380d4/infra/apps/osmosis/osmosis.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I disagree with approach taken here.

osmosis.go & gaia.go are almost identical except some chain specific parts:


Also run.tmpl are also mostly the same 

IMO we should define a single generic pkg for IBC chains which contains all common code and then have separate folders/files defining configs specific for each chain.

In this way adding new chains in the future will be much simpler and require less copy-paste

 
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`infra/apps/apps.go` line 179 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NP2OPT048Ul2HCMxZKY:-NP2OPT048Ul2HCMxZKZ:b-px4hcb) ([raw file](https://github.com/CoreumFoundation/crust/blob/bbd54f6269abbf1db791a0591489b81874444f82/infra/apps/apps.go#L179)):*
> ```Go
> 	nameGaia := name + "-gaia"
> 	nameOsmosis := name + "-osmosis"
> 	nameRelayerGaia := name + "-relayer-gaia"
> ```

minor: if we are going to integrate hermes relayer later I would name this one `relayercosmos` 
So in result we have `relayercosmos-gaia`
___
*[`infra/apps/apps.go` line 209 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NP2OdiK2fIR8yFeroJe:-NP2OdiK2fIR8yFeroJf:ba40wfe) ([raw file](https://github.com/CoreumFoundation/crust/blob/bbd54f6269abbf1db791a0591489b81874444f82/infra/apps/apps.go#L209)):*
> ```Go
> 	})
> 
> 	relayerOsmosisApp := relayercosmos.New(relayercosmos.Config{
> ```

this will create 2 separate relayers one gaia and one osmosis right ?
___
*[`infra/apps/gaiad/gaia.go` line 7 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NP2NQji2mtPQczVheiq:-NP2NQji2mtPQczVheir:bl7tqb7) ([raw file](https://github.com/CoreumFoundation/crust/blob/bbd54f6269abbf1db791a0591489b81874444f82/infra/apps/gaiad/gaia.go#L7)):*
> ```Go
> 
> 	"github.com/CoreumFoundation/crust/infra"
> 	"github.com/CoreumFoundation/crust/infra/cosmos"
> ```

minor: naming this package just cosmos is a bit confusing IMO
Maybe cosmoschain ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`infra/apps/apps.go` line 179 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NP2OPT048Ul2HCMxZKY:-NP2Z_0yAViqFrftTS_z:bqr5e6d) ([raw file](https://github.com/CoreumFoundation/crust/blob/bbd54f6269abbf1db791a0591489b81874444f82/infra/apps/apps.go#L179)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: if we are going to integrate hermes relayer later I would name this one `relayercosmos` 
So in result we have `relayercosmos-gaia`
</blockquote></details>

yes, then we rename it, it is already implemented in that package
___
*[`infra/apps/apps.go` line 209 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/167#-NP2OdiK2fIR8yFeroJe:-NP2Zld91EUwL-DgOR79:bkxov9c) ([raw file](https://github.com/CoreumFoundation/crust/blob/bbd54f6269abbf1db791a0591489b81874444f82/infra/apps/apps.go#L209)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this will create 2 separate relayers one gaia and one osmosis right ?
</blockquote></details>

yes, to spin up everything faster

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 9 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 3 of 9 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/167)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
