### PR TITLE
Simulate latency between cored nodes

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/399#-Ny-X4662MwYACRwxNFs:-Ny-X4662MwYACRwxNFt:b-tf2nff) (no related file):*
This definitely should be enabled by the flag or specific command.

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/399#-Ny-XMybCnkO30j-AMxU:-Ny-XMybCnkO30j-AMxV:b-nvo4hi) (no related file):*
What about using of `toxiproxy` or silimal tools, when the network delays are don't not bu the original docker instance, but the network. 

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/399#-Ny-XMybCnkO30j-AMxU:-Ny-lTRzCEpi7ov65hrg:b-m7m2ze) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about using of `toxiproxy` or silimal tools, when the network delays are don't not bu the original docker instance, but the network.
</blockquote></details>

I don't see the reason to use `toxiproxy` if everything I need might be set up easily using kernel by single command

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/399#-Ny-XMybCnkO30j-AMxU:-Ny0Axu11UbDh6jpdYua:btwwuw1) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see the reason to use `toxiproxy` if everything I need might be set up easily using kernel by single command
</blockquote></details>

I would agree, but you have to update the docker template for the dev tools, that's why I proposed to check other approaches.  

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/399#-Ny-XMybCnkO30j-AMxU:-Ny0GImI40bbMlQuEOrM:b-zg2nkj) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would agree, but you have to update the docker template for the dev tools, that's why I proposed to check other approaches.
</blockquote></details>

what's wrong about that? There are two more system binaries in the image now

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/399#-Ny-XMybCnkO30j-AMxU:-Ny0JzeX80A5GXkom_9H:b-aphat1) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what's wrong about that? There are two more system binaries in the image now
</blockquote></details>

If we implement it on the network level, we can apply it on any component, for example gaia, osmosis, XRPL and etc. If on coreum level only on coreum. I'm OK with it, if the team is ok.
@masihyeganeh @miladz68 @ysv WDYT guys?

___

**Pull request closed without merging**
