### PR TITLE
Add ignore for the lintNewLines linter.

### PR DESCRIPTION
**Pull request by dzmitryhil**
Add ignore of the "\\.", "vendor" folders and  ".iml", ".wasm" files for the lintNewLines linter.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/golang/lint.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpRba7Jubkn_OEoTQ:-NAcpRba7Jubkn_OEoTR:b-y1rdx9) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L24)):*
> ```Go
> 
> var (
> 	lintNewLinesSkipDirsRegexps  = []string{"\\.", "vendor"}
> ```

"\\." -> `^\.`
"vendor" -> "^vendor$"
___
*[`build/golang/lint.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpigj9DZSJEd8Pi5S:-NAcpigj9DZSJEd8Pi5T:b-etkyhl) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L25)):*
> ```Go
> var (
> 	lintNewLinesSkipDirsRegexps  = []string{"\\.", "vendor"}
> 	lintNewLinesSkipFilesRegexps = []string{".iml", ".wasm"}
> ```

I would use extensions only instead of regexps

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcqCo67Xx5DhEooQsq:-NAcqCo67Xx5DhEooQsr:b-r2b6nm) (no related file):*
Approved.
Just for consideration. 
another way of doing it which I think would be better is to have 1 list for both files and directories and use regex on the `path` string. then it would be easier to include all extenstions like "*.iml" or "*_test.go" or so on. However converting "*.iml" into proper regex would need some work. 

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`build/golang/lint.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpRba7Jubkn_OEoTQ:-NAcqWS77KZ2rohUJuqY:b-juvsza) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"\\." -> `^\.`
"vendor" -> "^vendor$"
</blockquote></details>

What is the reson to do it? 
We need to handle a line starts with the "." and exec match with "vendor". That's what current patters does.
___
*[`build/golang/lint.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpigj9DZSJEd8Pi5S:-NAcqM4YApZcBRQzJiQY:b-po1ptm) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would use extensions only instead of regexps
</blockquote></details>

The regexp is more flexible, in that case, so we will be able to add any types of files we need to ignore, not just by extensions, but for example _gen files and so on.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcqCo67Xx5DhEooQsq:-NAcrq2wAo1qg-2vbY57:bhniejj) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Approved.
Just for consideration. 
another way of doing it which I think would be better is to have 1 list for both files and directories and use regex on the `path` string. then it would be easier to include all extenstions like "*.iml" or "*_test.go" or so on. However converting "*.iml" into proper regex would need some work. 
</blockquote></details>

I had a thought like this, but decided to follow the golint way, they use the both skipDirs and skipFiles patterns, to give you more flexibility.

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/lint.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpRba7Jubkn_OEoTQ:-NAct3IeCRFOTCUEXRQS:b3antd) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the reson to do it? 
We need to handle a line starts with the "." and exec match with "vendor". That's what current patters does.
</blockquote></details>

But for your convenience I'll update it :-)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/lint.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpRba7Jubkn_OEoTQ:-NActjOW1El1NRIbbrMg:b-bu91xm) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But for your convenience I'll update it :-)
</blockquote></details>

Updated

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

___
*[`build/golang/lint.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpRba7Jubkn_OEoTQ:-NAcyBuI9qcDTd0cfNQ3:b-903w5s) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated
</blockquote></details>

1. you want to match dirs starting with `.`, not dirs containing `.` anywhere
2. similarly for vendor

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`build/golang/lint.go` line 25 at r2](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcyX1mCih10-Uuv93T:-NAcyX1n9mk3qLHLKbvl:bu97cfv) ([raw file](https://github.com/coreumfoundation/crust/blob/d554d728df63e3598afa6de1c7cb0e9eabb7e9b0/build/golang/lint.go#L25)):*
> ```Go
> var (
> 	lintNewLinesSkipDirsRegexps  = []string{`^\.`, `^vendor$`}
> 	lintNewLinesSkipFilesRegexps = []string{`.iml`, `.wasm`}
> ```

\.iml, \.wasm

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`build/golang/lint.go` line 25 at r2](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcyX1mCih10-Uuv93T:-NAcygrrAP2mfeGyUupY:b7fmfs6) ([raw file](https://github.com/coreumfoundation/crust/blob/d554d728df63e3598afa6de1c7cb0e9eabb7e9b0/build/golang/lint.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

```
\.iml, \.wasm
```
</blockquote></details>

or 
```
\.iml$, \.wasm$
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`build/golang/lint.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcpRba7Jubkn_OEoTQ:-NAczHCFB3Ucwr13z7wo:b-18nrsj) ([raw file](https://github.com/coreumfoundation/crust/blob/5fd5b4c4ff7a52c557aea192c033a376e626201d/build/golang/lint.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

1. you want to match dirs starting with `.`, not dirs containing `.` anywhere
2. similarly for vendor
</blockquote></details>

Both updated.
___
*[`build/golang/lint.go` line 25 at r2](https://reviewable.io/reviews/coreumfoundation/crust/75#-NAcyX1mCih10-Uuv93T:-NAczKFzAzqkdh4fJR_d:bpw7zq9) ([raw file](https://github.com/coreumfoundation/crust/blob/d554d728df63e3598afa6de1c7cb0e9eabb7e9b0/build/golang/lint.go#L25)):*
> \.iml$, \.wasm$
Both updated

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Pull request merged**
