### PR TITLE
Upgrade to go 1.19.1 and golangci 1.49.0

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)

### CODE REVIEW

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

___
*[`build/.golangci.yaml` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/crust/85#-NBpN6jV3H68arTMAFPA:-NBpN6jWEMCI2wNUYeor:b-gferur) ([raw file](https://github.com/coreumfoundation/crust/blob/103c07e5bc0f9c506df0f7623960660335a8991c/build/.golangci.yaml#L85)):*
> ```YAML
>   revive:
>     rules:
>       - name: package-comments
> ```

This rule forces every package to have comment at the top at least in one file. We never required them, and IMO it seems too harmful to require it for all the tiny, obvious packages. WDYT?

**Review by ysv — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`build/.golangci.yaml` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/crust/85#-NBpN6jV3H68arTMAFPA:-NBqkL2q7sgDwVvGzQjN:bthhrci) ([raw file](https://github.com/coreumfoundation/crust/blob/103c07e5bc0f9c506df0f7623960660335a8991c/build/.golangci.yaml#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This rule forces every package to have comment at the top at least in one file. We never required them, and IMO it seems too harmful to require it for all the tiny, obvious packages. WDYT?
</blockquote></details>

I'm ok
___
*[`pkg/znet/commands.go` line 223 at r3](https://reviewable.io/reviews/coreumfoundation/crust/85#-NBqkWUc0zhzaEB2KJa9:-NBqkWUc0zhzaEB2KJaA:bojrepg) ([raw file](https://github.com/coreumfoundation/crust/blob/1753b1a3ba340cd282608dafb6d4891227b71abe/pkg/znet/commands.go#L223)):*
> ```Go
> 	}
> 	coredNode := coredApp.(cored.Cored)
> 	//nolint:contextcheck // Function `Client->New->New->NewWithClient->New$1` should pass the context parameter... whatever it really means
> ```

so do you mean that the require ctx to be passed here ?
that is strange linter

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @wojtek-coreum)

___
*[`build/.golangci.yaml` line 86 at r3](https://reviewable.io/reviews/coreumfoundation/crust/85#-NC09aU78IgKKwLuXr5c:-NC09aU78IgKKwLuXr5d:bat4s2y) ([raw file](https://github.com/coreumfoundation/crust/blob/3c30eb6a30612df2ce94064e2dba1770620ada89/build/.golangci.yaml#L86)):*
> ```YAML
>     rules:
>       - name: package-comments
>         disabled: true
> ```

What is the problem with the package-comments?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @dzmitryhil)

___
*[`build/.golangci.yaml` line 86 at r3](https://reviewable.io/reviews/coreumfoundation/crust/85#-NC09aU78IgKKwLuXr5c:-NC0AZZi7d2q3TrVcTPs:b3aajbf) ([raw file](https://github.com/coreumfoundation/crust/blob/3c30eb6a30612df2ce94064e2dba1770620ada89/build/.golangci.yaml#L86)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the problem with the package-comments?
</blockquote></details>

There is no problem. I think we just don't need to require them. Discussed it here: https://reviewable.io/reviews/CoreumFoundation/crust/85#-NBpN6jV3H68arTMAFPA

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @dzmitryhil)

___
*[`build/.golangci.yaml` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/crust/85#-NBpN6jV3H68arTMAFPA:-NC0H2Tl7OFzKXQf9gwg:bfwngls) ([raw file](https://github.com/coreumfoundation/crust/blob/103c07e5bc0f9c506df0f7623960660335a8991c/build/.golangci.yaml#L85)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm ok
</blockquote></details>

It's needed to build proper package go docs. But we won't do it then ok :-)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Pull request merged**
