### PR TITLE
Added cache for smart contracts

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/255)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/255)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
Is it draft?

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/255#-:-Nak4y127RWrPz6O8DDm:bevt9qa)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
nope it is the final version.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/255#-:-NakT0Ra6YemxiglIbpN:b9vv6fp)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/255)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Pull request merged**
