### PR TITLE
Decrease `-test.parallel` when running integration-tests in CI to fix issue with different state

### PR DESCRIPTION
**Pull request by ysv**
# Description

https://github.com/cosmos/cosmos-sdk/issues/18761

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/testing/run.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/335#-NmCI3lYBm6wVT_g_ADy:-NmCI3lYBm6wVT_g_ADz:b-u7luob) ([raw file](https://github.com/CoreumFoundation/crust/blob/f9285aeb5b44d2e5ba5626b9e5e1077fb0bca705/infra/testing/run.go#L68)):*
> ```Go
> 		// The tests themselves are not computationally expensive, most of the time they spend waiting for transactions
> 		// to be included in blocks, so it should be safe to run more tests in parallel than we have CPus available.
> 		"-test.v", "-test.parallel", strconv.Itoa(runtime.NumCPU() / 2),
> ```

I've checked in CI & it takes extra ~3m for integr-test step with this decrease so it is +- ok

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`infra/testing/run.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/335#-NmCI3lYBm6wVT_g_ADy:-NmFhyVJ53Xu8f-VWo_N:bp1dv7p) ([raw file](https://github.com/CoreumFoundation/crust/blob/f9285aeb5b44d2e5ba5626b9e5e1077fb0bca705/infra/testing/run.go#L68)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I've checked in CI & it takes extra ~3m for integr-test step with this decrease so it is +- ok
</blockquote></details>

Could we somehow detect if this is the CI run (some env variable configured by github maybe)? I would love to keep the original parallelism when running it locally.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/testing/run.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/335#-NmCI3lYBm6wVT_g_ADy:-NmGBSsW5bsPIGxz_K9K:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/f9285aeb5b44d2e5ba5626b9e5e1077fb0bca705/infra/testing/run.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could we somehow detect if this is the CI run (some env variable configured by github maybe)? I would love to keep the original parallelism when running it locally.
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/335)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Comment by ysv** [comment]
This didn't help. Test still faild

**Pull request closed without merging**
