### PR TITLE
`znet`: Use production docker images

### PR DESCRIPTION
**Pull request by wojtek-coreum**
After doing this all the apps are started using existing docker images so some abstractions are removed from the code

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/98)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/98)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/98#-NCdr8mj6TfLLoWelTK_:-NCdr8mkCFb3e8l-sFK8:b-ihtp7u) (no related file):*
I recommend to review this PR commit by commit

___

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/98)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/98)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/98)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

**Pull request merged**
