### PR TITLE
Release faucet

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/faucet/build.go` line 41 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/195#-NU17THn7DTyBUUdrM7V:-NU17THn7DTyBUUdrM7W:bqtv4rk) ([raw file](https://github.com/CoreumFoundation/crust/blob/8786a2f036d80f7ed0d196fc2e51a44f97ab6ceb/build/faucet/build.go#L41)):*
> ```Go
> 	// If we build on ARM64 for ARM64 no special config is required. But if we build on AMD64 for ARM64
> 	// then crosscompilation must be enabled.
> 	case platform == tools.PlatformDockerARM64 && platform == tools.PlatformDockerLocal:
> ```

We have the same code already, let's have a common func for it. 



_Code quote:_
```Go
case platform == tools.PlatformDockerA
```

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/faucet/build.go` line 41 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/195#-NU17THn7DTyBUUdrM7V:-NU5fXBi1c_O5Gg-cDZK:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/16f1b0530600f33c8b4a41dcda3f690879130797/build/faucet/build.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We have the same code already, let's have a common func for it. 
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
