### PR TITLE
Update hermes version to v1.6.0 and config close to mainnet.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/257)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/257)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/hermes/config.tmpl` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/257#-Nal8UHe4mMtTTRB5KeF:-Nal8UHf42Z0ZRQ5a5pS:b-byl35s) ([raw file](https://github.com/CoreumFoundation/crust/blob/705dc55b9a414c3d1c5b49b6d294b8a1470b29b9/infra/apps/hermes/config.tmpl#L33)):*
> ```
> 
> # Whether or not to enable the connection workers for handshake completion. [Required]
> enabled = true
> ```

I don't think we need to enable this. same goes for channels, we do the handshakes once and specifically trigger the handshakes. 
___
*[`infra/apps/hermes/config.tmpl` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/257#-Nal8gYf6WeE2jjTSm5M:-Nal8gYf6WeE2jjTSm5N:bymhra0) ([raw file](https://github.com/CoreumFoundation/crust/blob/705dc55b9a414c3d1c5b49b6d294b8a1470b29b9/infra/apps/hermes/config.tmpl#L39)):*
> ```
> 
> # Whether or not to enable the channel workers for handshake completion. [Required]
> enabled = true
> ```

commented above.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/257)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/hermes/config.tmpl` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/257#-Nal8UHe4mMtTTRB5KeF:-Nal9ZPu070MeGOx6pXf:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/705dc55b9a414c3d1c5b49b6d294b8a1470b29b9/infra/apps/hermes/config.tmpl#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think we need to enable this. same goes for channels, we do the handshakes once and specifically trigger the handshakes. 
</blockquote></details>

Done.
___
*[`infra/apps/hermes/config.tmpl` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/257#-Nal8gYf6WeE2jjTSm5M:-Nal9tsB0s_sgOyU1eOY:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/705dc55b9a414c3d1c5b49b6d294b8a1470b29b9/infra/apps/hermes/config.tmpl#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

commented above.
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/257)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/257)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Pull request merged**
