### PR TITLE
Re-enable health-checks for IBC relayers & prepare crust to run upgrade v3 integration-tests

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR re-enables health-checks for IBC relayers since both of versions started by crust support IBC now. 
It also has some minor changes to crust to make new upgrade tests work

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/277)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Pull request merged**
