### PR TITLE
Add IBC tests

### PR DESCRIPTION
**Pull request by dzmitryhil**
* IBC tests binaries for the build
* Remove legacy tests run arguments
* Add funding accounts for the gaia and osmosis

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/cosmoschain/run.tmpl` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVEN3yq4kmve5zptcOr:-NVEN3yq4kmve5zptcOs:b-dw1xd0) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/cosmoschain/run.tmpl#L26)):*
> ```
> 
> # import the funding mnemonic
> echo $FUNDING_MNEMONIC | {{ .ExecName }} keys add funding --recover $KEYRING_FLAGS
> ```

Add quotes here and around `RELAYER_MNEMONIC`
___
*[`infra/testing/run.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVENxtp1LkpqUfXLctt:-NVENxtp1LkpqUfXLctu:byhc4a1) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L104)):*
> ```Go
> 				}
> 
> 				gaiadApp, ok := m.(gaiad.Gaiad)
> ```

Maybe instead of introducing new type, you could use the generic one and compare chain ID
___
*[`infra/testing/run.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVEOLAzDsC-k4cNiiky:-NVEOLAzDsC-k4cNiikz:b11j0vu) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L106)):*
> ```Go
> 				gaiadApp, ok := m.(gaiad.Gaiad)
> 				if ok {
> 					fullArgs = append(fullArgs, "-gaia-address", infra.JoinNetAddr("", gaiadApp.Info().HostFromHost, gaiadApp.Ports().GRPC))
> ```

you may use single `append` to serve both lines
___
*[`infra/testing/run.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVEOQZe-BDFhZMeuLLj:-NVEOQZe-BDFhZMeuLLk:bljszdk) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L106)):*
> ```Go
> 				gaiadApp, ok := m.(gaiad.Gaiad)
> 				if ok {
> 					fullArgs = append(fullArgs, "-gaia-address", infra.JoinNetAddr("", gaiadApp.Info().HostFromHost, gaiadApp.Ports().GRPC))
> ```

These arguments are specific to `coreum-ibc`. They shouldn't be passed neither to `coreum-modules` nor `coreum-upgrade`

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/testing/run.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVENxtp1LkpqUfXLctt:-NVETLN2A-0j9YxUqk_r:b1op0kb) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L104)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe instead of introducing new type, you could use the generic one and compare chain ID
</blockquote></details>

You may check how @miladz68 did it here: https://github.com/CoreumFoundation/crust/blob/milad/handle-v2-upgrade/infra/testing/run.go#L105

Guys, please coordinate because I see some parts are common.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/cosmoschain/run.tmpl` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVEN3yq4kmve5zptcOr:-NVEsfU09A9qwqdIq751:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/cosmoschain/run.tmpl#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Add quotes here and around `RELAYER_MNEMONIC`
</blockquote></details>

Done.
___
*[`infra/testing/run.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVENxtp1LkpqUfXLctt:-NVEslFC9tBMgHrMKwtY:b-51hqjb) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L104)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You may check how @miladz68 did it here: https://github.com/CoreumFoundation/crust/blob/milad/handle-v2-upgrade/infra/testing/run.go#L105

Guys, please coordinate because I see some parts are common.
</blockquote></details>

I had such thought, but then found that we don't use constants, and use types in that files for Cored as well, so we should follow the same rule, IMO the type is better approach here.
___
*[`infra/testing/run.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVEOLAzDsC-k4cNiiky:-NVEtFA90HKbtNO3KK5b:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may use single `append` to serve both lines
</blockquote></details>

Done.
___
*[`infra/testing/run.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVEOQZe-BDFhZMeuLLj:-NVEu4E0C4e_8pqftkf-:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L106)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

These arguments are specific to `coreum-ibc`. They shouldn't be passed neither to `coreum-modules` nor `coreum-upgrade`
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`infra/testing/run.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/204#-NVENxtp1LkpqUfXLctt:-NVTha28CPZS_hcQVOXB:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/crust/blob/f6ba24a7e048753448a3e3e32eaf70b5237e5363/infra/testing/run.go#L104)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I had such thought, but then found that we don't use constants, and use types in that files for Cored as well, so we should follow the same rule, IMO the type is better approach here.
</blockquote></details>

Updated.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Pull request merged**
