### PR TITLE
Lint proto files and detect breaking changes

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @keyleu, and @miladz68)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @keyleu, and @miladz68)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`build/coreum/generate-proto-lint.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/291#-Ng35VQ3EEdzyfYo-bbm:-Ng35VQ4164u-e5y4cy6:b-tw13id) ([raw file](https://github.com/CoreumFoundation/crust/blob/9663ee07cfdedb8a456b29e224db5682e15bf3c2/build/coreum/generate-proto-lint.go#L21)):*
> ```Go
> 
> 	//  We need versions to derive paths to protoc for given modules installed by `go mod tidy`
> 	moduleDirs, err := golang.ModuleDirs(ctx, deps, repoPath,
> ```

Why is the list of the modules here and in different places different? Can't we use just one for all of them?
The same question about the `includeDirs`.
___
*[`build/coreum/generate-proto-lint.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/291#-Ng35rniE05JZ7jebLGi:-Ng35rniE05JZ7jebLGj:b3tttuv) ([raw file](https://github.com/CoreumFoundation/crust/blob/9663ee07cfdedb8a456b29e224db5682e15bf3c2/build/coreum/generate-proto-lint.go#L65)):*
> ```Go
> 		"--buf-lint_out=.",
> 		`--buf-lint_opt={
> 			"input_config": {
> ```

How about moving it the the file and read for it ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`build/coreum/generate-proto-lint.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/291#-Ng35rniE05JZ7jebLGi:-Ng3GERC67oZWPaekQWd:b-i9x71v) ([raw file](https://github.com/CoreumFoundation/crust/blob/9663ee07cfdedb8a456b29e224db5682e15bf3c2/build/coreum/generate-proto-lint.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about moving it the the file and read for it ?
</blockquote></details>

what for?

**Review by ysv — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`build/coreum/generate-proto-lint.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/291#-Ng35VQ3EEdzyfYo-bbm:-Ng3Ov6IEGbTSeLBD3ce:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/9663ee07cfdedb8a456b29e224db5682e15bf3c2/build/coreum/generate-proto-lint.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why is the list of the modules here and in different places different? Can't we use just one for all of them?
The same question about the `includeDirs`.
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

___
*[`build/coreum/generate-proto-lint.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/291#-Ng35rniE05JZ7jebLGi:-Ng5469YClEg6KPGTl7w:b-bprr5u) ([raw file](https://github.com/CoreumFoundation/crust/blob/9663ee07cfdedb8a456b29e224db5682e15bf3c2/build/coreum/generate-proto-lint.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's easier to edit a file. Why don't we have can all files we you for the config in the code as string?
</blockquote></details>

I agree with Dima

on the other hand it is not that big 

But probably makes sense to move to file and use embeding via var for simpler editing

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

___
*[`build/coreum/generate-proto-lint.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/291#-Ng35rniE05JZ7jebLGi:-NgITDNc0RkpOonmvOl_:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/9663ee07cfdedb8a456b29e224db5682e15bf3c2/build/coreum/generate-proto-lint.go#L65)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Dima

on the other hand it is not that big 

But probably makes sense to move to file and use embeding via var for simpler editing
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @keyleu)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
