### PR TITLE
Use GCP binaries for the tools with `latest` only supported version

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Use GCP binaries for the tools with `latest` only supported version

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`build/tools/tools.go` line 404 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/392#-NweGpge7POx8AhXxYfM:-NweGpge7POx8AhXxYfN:b-79dbh6) ([raw file](https://github.com/CoreumFoundation/crust/blob/d1e88c61c0ac34c80d3c3b052218713503ecf91c/build/tools/tools.go#L404)):*
> ```Go
> 			},
> 			TargetPlatformDarwinAMD64: {
> 				URL:  "https://storage.googleapis.com/cored-build-process-binaries/rustup-init/1.27.0/x86_64-apple-darwin-rustup-init", //nolint:lll // breaking down urls is not beneficial
> ```

nit: maybe it makes sense to move this to constant. Kinda base URL



_Code quote:_
```Go
https://storage.googleapis.com/cored-build-process-binaries
```

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/392#-NwiV-a78tFR3EQ_XCEW:-NwiV-a78tFR3EQ_XCEX:b-vg07j5) (no related file):*
what is the point, is it to pin a fixed version of rust binaries ?

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/392#-NwiV-a78tFR3EQ_XCEW:-NwifM7R4I79AJnGyMi5:b2lex97) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what is the point, is it to pin a fixed version of rust binaries ?
</blockquote></details>

Correct. Now for those two binaries the crust uses the latest version, so when the latest version is update the crust build failed because of the hash mismatch. That PR prevents it.

___
___
*[`build/tools/tools.go` line 404 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/392#-NweGpge7POx8AhXxYfM:-NwifjnV4UDd5IIQ38aZ:b7n1zoi) ([raw file](https://github.com/CoreumFoundation/crust/blob/d1e88c61c0ac34c80d3c3b052218713503ecf91c/build/tools/tools.go#L404)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: maybe it makes sense to move this to constant. Kinda base URL
</blockquote></details>

IMO the current way is more optimal.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`build/tools/tools.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/392#-NweDUPH62u8fQIoBTY1:-NwtJI-eAqTxg2Dybuh6:b-u4jdac) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef0a4b5d93ea6c7fc0ae123ec8785b910054f36e/build/tools/tools.go#L140)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@miladz68 @wojtek-coreum Check please the `release` CLI, since it doesn't work on my machine.
</blockquote></details>

It works.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/392)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

**Pull request merged**
