### PR TITLE
Add command to remove stuff created by `crust` in case someone is fired

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
I don't get this part of the title `in case someone is fired` ! :smile: 

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230#-:-NZ-fP_P6aShC7hQArWE:b-zgxgs1)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/230#-NZ-lBcS0-hhqFcXraCC:-NZ-lBcS0-hhqFcXraCD:bnvuhh) (no related file):*
I think the main issue that is we are facing and the reason we have this task is that sometimes we have to remove the cache before we rebuild crust so the changes in the repo will take affect. can you also investigate that part ?

___

**Review by wojtek-coreum — COMMENTED** [review]
Because this is the next step :)

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230#-:-NZ-rhMV1PSBn5U-xAqD:bjsxexk)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/230#-NZ-lBcS0-hhqFcXraCC:-NZ-ruc69W1p8dWtaa8p:b-ot0so8) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think the main issue that is we are facing and the reason we have this task is that sometimes we have to remove the cache before we rebuild crust so the changes in the repo will take affect. can you also investigate that part ?
</blockquote></details>

But what cache are you talking about? I'm removing the cache dir of crust. Is there any other?

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/230#-NZ-lBcS0-hhqFcXraCC:-NZ-xxDp0NMLOxcR-mwI:byqlz7u) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But what cache are you talking about? I'm removing the cache dir of crust. Is there any other?
</blockquote></details>

I am only see code related to docker ! maybe I am missing the folder cleaning code ? 

___

**Review by miladz68 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`build/crust/remove.go` line 20 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/230#-NZ03srcCezuHfcqkWTc:-NZ03srd2u-rDEDkjLDR:b-b4az6d) ([raw file](https://github.com/CoreumFoundation/crust/blob/6784e4976642d1a3f3f8502889331fd865c6673f/build/crust/remove.go#L20)):*
> ```Go
> 	}
> 
> 	return errors.WithStack(os.RemoveAll(tools.CacheDir()))
> ```

@miladz68 here it is

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/230#-NZ-lBcS0-hhqFcXraCC:-NZ03wNDAU6pRuLcTub4:b-or53bd) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am only see code related to docker ! maybe I am missing the folder cleaning code ? 
</blockquote></details>

I tagged you in the line where it is done

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/230)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/crust/remove.go` line 20 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/230#-NZ03srcCezuHfcqkWTc:-NZ06NNM8rcYbQNkv9rU:b-q8ilnv) ([raw file](https://github.com/CoreumFoundation/crust/blob/6784e4976642d1a3f3f8502889331fd865c6673f/build/crust/remove.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 here it is
</blockquote></details>

gotcha

**Pull request merged**
