### PR TITLE
Run `cored` using `cosmovisor`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/coreum/image/Dockerfile.tmpl` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDbrvkH7L8oJpezg61K:-NDbrvkH7L8oJpezg61L:b-aufm6n) ([raw file](https://github.com/coreumfoundation/crust/blob/63ef5f13afcd5fb679cb32a61c0e23b3c4d17674/build/coreum/image/Dockerfile.tmpl#L1)):*
> ```
> FROM {{ .From }}
> ```

what about production image do we include cosmovisor there also ?
___
*[`infra/apps/cored/cored.go` line 198 at r3](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDbrgxR2PpjNTmukv-g:-NDbrgxR2PpjNTmukv-h:b-ri8n54) ([raw file](https://github.com/coreumfoundation/crust/blob/63ef5f13afcd5fb679cb32a61c0e23b3c4d17674/infra/apps/cored/cored.go#L198)):*
> ```Go
> 		ArgsFunc: func() []string {
> 			args := []string{
> 				"run",
> ```

do we really need bot run & start now ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/coreum/image/Dockerfile.tmpl` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDbrvkH7L8oJpezg61K:-NDbtuiB9VGzfur49E3j:blaf42k) ([raw file](https://github.com/coreumfoundation/crust/blob/63ef5f13afcd5fb679cb32a61c0e23b3c4d17674/build/coreum/image/Dockerfile.tmpl#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about production image do we include cosmovisor there also ?
</blockquote></details>

This is the production image
___
*[`infra/apps/cored/cored.go` line 198 at r3](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDbrgxR2PpjNTmukv-g:-NDbtykG5XRvYJGeOtEP:bl3n3ck) ([raw file](https://github.com/coreumfoundation/crust/blob/63ef5f13afcd5fb679cb32a61c0e23b3c4d17674/infra/apps/cored/cored.go#L198)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need bot run & start now ?
</blockquote></details>

`run` is a command for cosmovisor, the rest is passed to `cored`.
Yes we need it, we want to use cosmovisor so let's use it. In enxt step I will add infrastructure for testing it.

**Review by ysv — CHANGES_REQUESTED** [review]
I'm just blocking it till daily meeting because I want to discuss some details of cosmvisor with you

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113#-:-NDcEv4b0DVq4LEtoTqX:b-t5zdw)* status: 2 of 10 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`build/coreum/image/Dockerfile.tmpl` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDbrvkH7L8oJpezg61K:-NDcElgI3BLChTEBtjEC:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/63ef5f13afcd5fb679cb32a61c0e23b3c4d17674/build/coreum/image/Dockerfile.tmpl#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the production image
</blockquote></details>

ok
___
*[`infra/apps/cored/cored.go` line 198 at r3](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDbrgxR2PpjNTmukv-g:-NDcEnpM1iAadZ9DsV3e:bvuoglw) ([raw file](https://github.com/coreumfoundation/crust/blob/63ef5f13afcd5fb679cb32a61c0e23b3c4d17674/infra/apps/cored/cored.go#L198)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`run` is a command for cosmovisor, the rest is passed to `cored`.
Yes we need it, we want to use cosmovisor so let's use it. In enxt step I will add infrastructure for testing it.
</blockquote></details>

I see
It just looked strange the sequence of 'run start'

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/apps.go` line 39 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcIM5p79A5wcyiBvqL:-NDcIM5p79A5wcyiBvqM:b-peb5s5) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/apps.go#L39)):*
> ```Go
> 
> // CoredNetwork creates new network of cored nodes
> func (f *Factory) CoredNetwork(name string, firstPorts cored.Ports, validatorsCount int, sentriesCount int) (cored.Cored, infra.Mode, error) {
> ```

Why name is "firstPorts" ?
___
*[`infra/apps/cored/cored.go` line 192 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcIS0v8J73UQLXS5wR:-NDcIS0v8J73UQLXS5wS:b-i0ya1i) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/cored/cored.go#L192)):*
> ```Go
> 				{
> 					Name:  "DAEMON_NAME",
> 					Value: "cored",
> ```

This value should be taken form the shared constant since I saw it in the build as well



_Code quote:_
```Go
cored
```
___
*[`infra/apps/cored/cored.go` line 243 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcK5vF3p3JNMb7691W:-NDcK5vG1Osossborspr:b-552t4n) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/cored/cored.go#L243)):*
> ```Go
> 				return errors.WithStack(err)
> 			}
> 			return c.saveUpgradeWrapper("upgrade")
> ```

Didn't get that part. Could you please explain?
___
*[`infra/testing/run.go` line 58 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcKE5a41eFmvs9o3am:-NDcKE5a41eFmvs9o3an:b63u8z4) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/testing/run.go#L58)):*
> ```Go
> 
> 	log.Info("All the applications are ready")
> 	coredApp := mode.FindRunningApp(cored.AppType, "coredev-00")
> ```

"coredev-00" constant, it can be reused in the code? Same comment for the "faucetdev"



_Code quote:_
```Go
"coredev-00"
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`infra/apps/cored/cored.go` line 192 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcIS0v8J73UQLXS5wR:-NDfslMR4BVfNSxzIKat:b-z4jl4x) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/cored/cored.go#L192)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So let's have the common place - pkg?
</blockquote></details>

for single constant?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 192 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcIS0v8J73UQLXS5wR:-NDgULfw52eqnBJmeA62:bwx0833) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/cored/cored.go#L192)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

for single constant?
</blockquote></details>

Right, why not?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 4 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`infra/apps/cored/cored.go` line 192 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcIS0v8J73UQLXS5wR:-NDgy3R0281NO-W4HUm9:bt5hhze) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/cored/cored.go#L192)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, why not?
</blockquote></details>

because I would have to create separate module with go.mod etc. just to provide one constant. @ysv ?

**Review by ysv — APPROVED** [review]
approving & resolving discussions to not block merging while I'm on vacation
@dzmitryhil @miladz68 pls review this PR attentively

> Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 4 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113#-:-NDtTx6H8DfjsRSN4tjf:b-1e85yo)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`infra/apps/cored/cored.go` line 192 at r4](https://reviewable.io/reviews/coreumfoundation/crust/113#-NDcIS0v8J73UQLXS5wR:-NDtTtK-BdmGgivjWknr:b-fs18fa) ([raw file](https://github.com/coreumfoundation/crust/blob/b488affc84fc0a15b607ce6f26ab2e9f6f762e5a/infra/apps/cored/cored.go#L192)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

because I would have to create separate module with go.mod etc. just to provide one constant. @ysv ?
</blockquote></details>

not sure that it is worth to create a pkg for this

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
