### PR TITLE
Add confidence = 0.1 to the revive linter

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`build/.golangci.yaml` line 88 at r1](https://reviewable.io/reviews/coreumfoundation/crust/144#-NIqQjC1A4-oeT3hS2ZO:-NIqQjC22KnOu8Rd081h:b-fok38h) ([raw file](https://github.com/coreumfoundation/crust/blob/e58821108e89a618591917b4281242ac25fda513/build/.golangci.yaml#L88)):*
> ```YAML
> 
>   revive:
>     confidence: 0.1
> ```

but isn't 0.1 too low and may lead to false positives ?

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`build/.golangci.yaml` line 88 at r1](https://reviewable.io/reviews/coreumfoundation/crust/144#-NIqQjC1A4-oeT3hS2ZO:-NIqwM4tBFc1RPa6lcBc:b-l8l7r9) ([raw file](https://github.com/coreumfoundation/crust/blob/e58821108e89a618591917b4281242ac25fda513/build/.golangci.yaml#L88)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but isn't 0.1 too low and may lead to false positives ?
</blockquote></details>

same question

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/.golangci.yaml` line 88 at r1](https://reviewable.io/reviews/coreumfoundation/crust/144#-NIqQjC1A4-oeT3hS2ZO:-NJ43Qnk3ZUgF_v423Ef:b-w6da1h) ([raw file](https://github.com/coreumfoundation/crust/blob/e58821108e89a618591917b4281242ac25fda513/build/.golangci.yaml#L88)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same question
</blockquote></details>

If it finds "false positives" cases we will see them, and will be able to adjust it.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
