### PR TITLE
Link genesis cored binary for cosmovisor inside Dockerfile

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/types.go` line 296 at r1](https://reviewable.io/reviews/coreumfoundation/crust/128#-NEFWWJR8CkZcRle7bcn:-NEF_oJ570vJ6lMut6aJ:b-ltbkly) ([raw file](https://github.com/coreumfoundation/crust/blob/e4773e4458a27dcb76dfd7483082db0058d06d65/infra/types.go#L296)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The comment isn't clear. 
</blockquote></details>

what exactly?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/types.go` line 296 at r1](https://reviewable.io/reviews/coreumfoundation/crust/128#-NEFWWJR8CkZcRle7bcn:-NEFdLaSCIpTMFMHjOIT:b-9i5duo) ([raw file](https://github.com/coreumfoundation/crust/blob/e4773e4458a27dcb76dfd7483082db0058d06d65/infra/types.go#L296)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what exactly?
</blockquote></details>

What do you mean: "It is required IF container creates files". Do you mean "It is required for container to create" ? If Yes let's better to rephrase this comment.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/types.go` line 296 at r1](https://reviewable.io/reviews/coreumfoundation/crust/128#-NEFWWJR8CkZcRle7bcn:-NEGXaxcCGLOX0GpN3eb:b-oyz7np) ([raw file](https://github.com/coreumfoundation/crust/blob/e4773e4458a27dcb76dfd7483082db0058d06d65/infra/types.go#L296)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What do you mean: "It is required IF container creates files". Do you mean "It is required for container to create" ? If Yes let's better to rephrase this comment.
</blockquote></details>

no, I mean that if container creates files on mounted volumes this option must be set to true

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
