### PR TITLE
Integrate monitoring

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/grafana/grafana.go` line 133 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJBfz3P5LTJYLdcX7:-NKTJBfz3P5LTJYLdcX8:b-jjm2yz) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L133)):*
> ```Go
> 	}
> 
> 	err := os.WriteFile(filepath.Join(g.config.HomeDir, datasourceFileName), buf.Bytes(), 0o700)
> ```

0o700 -> 0o600
___
*[`infra/apps/grafana/grafana.go` line 139 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJSrKAAOuvEbL61dr:-NKTJSrKAAOuvEbL61ds:b-4ox167) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L139)):*
> ```Go
> 
> 	// create dashboards dir
> 	err = os.MkdirAll(filepath.Join(g.config.HomeDir, dashboardsFolder), os.ModePerm)
> ```

os.ModePerm -> 0o700
___
*[`infra/apps/grafana/grafana.go` line 158 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJkPNB-nkMDpdqb98:-NKTJkPO0kjV4DMnLYYN:b-6a16dh) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L158)):*
> ```Go
> 		defer file.Close()
> 
> 		fileBytes, err := io.ReadAll(file)
> ```

Minor: io.Copy would use less resources
___
*[`infra/apps/grafana/grafana.go` line 160 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJrYhE4GFxibFyftQ:-NKTJrYhE4GFxibFyftR:b9hpvli) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L160)):*
> ```Go
> 		fileBytes, err := io.ReadAll(file)
> 		if err != nil {
> 			panic(fmt.Sprintf("can't read file %+v from dashboards FS", file))
> ```

panic -> return err
___
*[`infra/apps/grafana/config/datasource.tmpl` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTIM5bCf-MxHTRByl_:-NKTIM5c3trnFrEAjlz1:bt4rbh0) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/config/datasource.tmpl#L3)):*
> ```
> apiVersion: 1
> 
> deleteDatasources:
> ```

why do we need to delete it?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTO-9X7aygBvce8_ye:-NKTO-9X7aygBvce8_yf:bxmuhcy) (no related file):*
I get this in prometheus container:

```
[wojciech@coreum crust]$ docker logs 789ba4ec6c0e
ts=2022-12-29T14:57:06.670Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: permission denied"
```

I fixed it by adding `RunAsUser: true` to both prometheus and grafana.

But then prometheus logs this:

```
ts=2022-12-29T15:00:47.490Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/data/queries.active err="open data/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x3342398, 0x5}, 0x14, {0x3d4d7a0, 0xc000050af0})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3
```

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: 15 of 17 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTO-9X7aygBvce8_ye:-NKTP5UJ5a-23JLVhUy9:b-s5o4s9) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I get this in prometheus container:

```
[wojciech@coreum crust]$ docker logs 789ba4ec6c0e
ts=2022-12-29T14:57:06.670Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: permission denied"
```

I fixed it by adding `RunAsUser: true` to both prometheus and grafana.

But then prometheus logs this:

```
ts=2022-12-29T15:00:47.490Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/data/queries.active err="open data/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x3342398, 0x5}, 0x14, {0x3d4d7a0, 0xc000050af0})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3
```
</blockquote></details>

I committed `RunAsUser` to this PR

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: 15 of 17 files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTO-9X7aygBvce8_ye:-NKXUl3P32271TbX5AGB:b-gkf6d) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I committed `RunAsUser` to this PR
</blockquote></details>

Got you thanks.

___
___
*[`infra/apps/grafana/grafana.go` line 133 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJBfz3P5LTJYLdcX7:-NKXV7rB4RkSR-poCNCH:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L133)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

0o700 -> 0o600
</blockquote></details>

Done.
___
*[`infra/apps/grafana/grafana.go` line 139 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJSrKAAOuvEbL61dr:-NKXV2mh-PIB1JOmZZzH:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L139)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

os.ModePerm -> 0o700
</blockquote></details>

Done.
___
*[`infra/apps/grafana/grafana.go` line 158 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJkPNB-nkMDpdqb98:-NKXX-qR07RSJtcy9deo:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L158)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: io.Copy would use less resources
</blockquote></details>

Updated.
___
*[`infra/apps/grafana/grafana.go` line 160 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTJrYhE4GFxibFyftQ:-NKXX0rkCcoNffXqLBVM:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/grafana.go#L160)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

panic -> return err
</blockquote></details>

Updated.
___
*[`infra/apps/grafana/config/datasource.tmpl` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTIM5bCf-MxHTRByl_:-NKXX9S337x-3GjQqu9K:b-z9o12z) ([raw file](https://github.com/coreumfoundation/crust/blob/3a3d2e068e36cb826cc3901fce393f4116ca5268/infra/apps/grafana/config/datasource.tmpl#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why do we need to delete it?
</blockquote></details>

It meath that we need to delete/recreate it in case we reload/remove that file.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/grafana/grafana.go` line 159 at r3](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKYCsce0OtE7h09iGcb:-NKYCsce0OtE7h09iGcc:bxsu1lh) ([raw file](https://github.com/coreumfoundation/crust/blob/c718e7424f5aee1db98aebbff3a58ea8bb8f674d/infra/apps/grafana/grafana.go#L159)):*
> ```Go
> 		defer source.Close()
> 
> 		destination, err := os.OpenFile(filepath.Join(g.config.HomeDir, dashboardsFolder, d.Name()), os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o777) //nolint:nosnakecase // os constants
> ```

0o777 -> 0o600

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTO-9X7aygBvce8_ye:-NKYEwfz-hveMjRZwz4d:b7q5jcu) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Got you thanks.
</blockquote></details>

I still get this error:

```
ts=2022-12-30T13:35:53.221Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/prometheus/queries.active err="open prometheus/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffcf9515f7e, 0xa}, 0x14, {0x3d4d7a0, 0xc0004af5e0})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3

```

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKTO-9X7aygBvce8_ye:-NKYLdUD3opN_JvOaQpy:b-ik34px) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I still get this error:

```
ts=2022-12-30T13:35:53.221Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/prometheus/queries.active err="open prometheus/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffcf9515f7e, 0xa}, 0x14, {0x3d4d7a0, 0xc0004af5e0})
	/app/promql/query_logger.go:121 +0x3cd
main.main()
	/app/cmd/prometheus/main.go:618 +0x69d3

```
</blockquote></details>

I got the same error before, but then added a volume now it's good. Try to clear the /Users/<you>/Library//Caches/crust/znet

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/grafana/grafana.go` line 159 at r3](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKYCsce0OtE7h09iGcb:-NKYOXLa3uzLetCDtx3n:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/c718e7424f5aee1db98aebbff3a58ea8bb8f674d/infra/apps/grafana/grafana.go#L159)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

0o777 -> 0o600
</blockquote></details>

Done.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 519 at r4](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKlmSAK-iTQvUeAcc9F:-NKlmSAK-iTQvUeAcc9G:b-52nrjr) ([raw file](https://github.com/coreumfoundation/crust/blob/86bc933c634edd531b03017289d964c49d1629df/build/tools/tools.go#L519)):*
> ```Go
> 
> // FIXME (wojciech): once build uses go 1.18 replace `combine` with https://github.com/samber/lo#assign
> func combine(m1, m2 map[string]string) map[string]string {
> ```

we are using 1.18 now, so we should be able to remove this function altogether and the package mentioned in the comment.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: 16 of 21 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 519 at r4](https://reviewable.io/reviews/coreumfoundation/crust/151#-NKlmSAK-iTQvUeAcc9F:-NKmnWcmD9nfSN_XDGHL:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/86bc933c634edd531b03017289d964c49d1629df/build/tools/tools.go#L519)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we are using 1.18 now, so we should be able to remove this function altogether and the package mentioned in the comment. 
</blockquote></details>

Done



_Code quote:_
```Go
XME (wojciech): once build uses go 1.18 replace `combine` with https://github.com/samber/lo#assign
```

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 14 of 17 files at r1, 1 of 1 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
