### PR TITLE
Moved proto docs generation to generate/coreum target

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/generate.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/237#-NZ-bOiU9xqNTuYBhK_W:-NZ-bOiV-Pen8euX9KOr:btt10qg) ([raw file](https://github.com/CoreumFoundation/crust/blob/c6f25fd73f9847eea8e5828262826a03b2fee67a/build/coreum/generate.go#L13)):*
> ```Go
> func Generate(ctx context.Context, deps build.DepsFunc) error {
> 	deps(ensureRepo)
> 	deps(generateProtoDocs)
> ```

`deps(ensureRepo, generateProtoDocs)`
___
*[`build/coreum/generate-proto-docs.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/237#-NZ-bXnx3PkL9CJQzvXX:-NZ-bXnx3PkL9CJQzvXY:b-7dmvll) ([raw file](https://github.com/CoreumFoundation/crust/blob/c6f25fd73f9847eea8e5828262826a03b2fee67a/build/coreum/generate-proto-docs.go#L86)):*
> ```Go
> 	args := []string{
> 		fmt.Sprintf("%s=%s", "--doc_out", "docs"),
> 		fmt.Sprintf("%s=%s,api.md", "--doc_opt", filepath.Join("docs", "api.md.tmpl")),
> ```

`api.tmpl.md`, so the last part of the extension helps the IDE to format the file better.
Also, now I see that the template is controlled by us (earielr I thought that we take it from external source), so could you try to remove those extra lines linter complaints about and remove that file frome exceptions?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/generate-proto-docs.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/237#-NZ-bXnx3PkL9CJQzvXX:-NZ-xXnhD_pqTE1V4aTl:bsygcp0) ([raw file](https://github.com/CoreumFoundation/crust/blob/c6f25fd73f9847eea8e5828262826a03b2fee67a/build/coreum/generate-proto-docs.go#L86)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Renamed.
Fixed double line at the end of file by adding HTML comment, and two empty lines go before it.
</blockquote></details>

I don't see the PR with modified ap.tmpl.md

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/generate-proto-docs.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/237#-NZ-bXnx3PkL9CJQzvXX:-NZ043tJ5eVmiwhQTDIw:b16uqrw) ([raw file](https://github.com/CoreumFoundation/crust/blob/c6f25fd73f9847eea8e5828262826a03b2fee67a/build/coreum/generate-proto-docs.go#L86)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

I remember about it, but intended to create it later after we merge this PR
</blockquote></details>

nope, because if you forget, nobody will be able to merge PRs in coreum

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Pull request merged**
