### PR TITLE
made total supply 500m in znet

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)

### Testing:
- `cored q bank total` returned around 500m+ in both `crust znet start --profiles=1cored` and `crust znet start --profiles=5cored`.
- `cored q staking validators` shows that each validator has expected 9_000_000_000_000udevcore

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/.golangci.yaml` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/188#-NTSHWjTCCrN8SmVsqek:-NTYicrH5IMEgpF89wka:bn1pz20) ([raw file](https://github.com/CoreumFoundation/crust/blob/8e96fb0a1d0eda47ddd2f9e2145bd7f4b0315266/build/.golangci.yaml#L29)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Also, the question is - do we need both `gci` and`goimports`? They do the same stuff - sort imports
</blockquote></details>

crust lint/crust passes on master, so it must be some code that you introduced. disabling a linter is not a good idea
___
*[`infra/apps/apps.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/188#-NTYl5QRElnsIZR463xx:-NTYl5QRElnsIZR463xy:b-324clg) ([raw file](https://github.com/CoreumFoundation/crust/blob/ce114cc74fe319e3e0b0902f0be79cd17a4d587b/infra/apps/apps.go#L51)):*
> ```Go
> 	binaryVersion string,
> ) (cored.Cored, []cored.Cored, error) {
> 	if validatorsCount > len(cored.StakerMnemonics) {
> ```

this is not a bad check and it still should be moved somewhere. 
___
*[`infra/apps/cored/wallets.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/188#-NTYkJAr-PJFJES7DFVT:-NTYkJAr-PJFJES7DFVU:bob61a0) ([raw file](https://github.com/CoreumFoundation/crust/blob/8e96fb0a1d0eda47ddd2f9e2145bd7f4b0315266/infra/apps/cored/wallets.go#L80)):*
> ```Go
> 
> // NewFundedWallet creates wallet and funds all predefined accounts.
> func NewFundedWallet(network *config.Network) *Wallet {
> ```

The way that I understand it, you always alocate funds to all the mnemonics listed regardless they are used or not. If I am correct it will cause problems with integration tests. Because  we start tests with 3 nodes and run proposals based on that, those proposal will fail, since they will never get enough votes. the way that it works is that we take all the validators (3) and vote with them, but their vote will not be enough (i.e less that 66% of total supply) and the vote will never pass and test will fail.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 64 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/188#-NTxUnfM1Tp_yGbZWTCn:-NTxUnfM1Tp_yGbZWTCo:bafvshe) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a1d9dd423203bb9b497e264392574dcf1a4a95c/infra/apps/cored/cored.go#L64)):*
> ```Go
> 
> // New creates new cored app.
> func New(cfg Config, stakerMnemonicBalance int64) Cored {
> ```

add `stakerMnemonicBalance` it to `cfg` and maybe call it `StakerBalance` there
___
*[`infra/apps/cored/wallets.go` line 81 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/188#-NTxVbrN7znzBHuYFFsH:-NTxVbrN7znzBHuYFFsI:b-3amqa) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a1d9dd423203bb9b497e264392574dcf1a4a95c/infra/apps/cored/wallets.go#L81)):*
> ```Go
> // NewFundedWallet creates wallet and funds all predefined accounts.
> func NewFundedWallet(network *config.Network) *Wallet {
> 	var desiredTotalSupply int64 = 500_000_000_000_000    // 500m core
> ```

make constants here

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`infra/apps/cored/wallets.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/188#-NTYkJAr-PJFJES7DFVT:-NU6H4IU9207atop_2Ww:b-fnvv5n) ([raw file](https://github.com/CoreumFoundation/crust/blob/8e96fb0a1d0eda47ddd2f9e2145bd7f4b0315266/infra/apps/cored/wallets.go#L80)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

discussed
</blockquote></details>

what was the result of the discussion?

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
