### PR TITLE
GRPC client codec fix

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Set correc codec for the GRPC client.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/270)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/270)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`infra/cosmoschain/base.go` line 194 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/270#-Nbmw9W-7l7sNgW3i-bi:-Nbmw9W-7l7sNgW3i-bj:b58mv32) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee61b9c7f63672e27e789998501566c93e0522d7/infra/cosmoschain/base.go#L194)):*
> ```Go
> }
> 
> func dialGRPCClient(url string, mm module.BasicManager) (*grpc.ClientConn, error) {
> ```

Let's export it here and reuse in `cored`

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/270)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/270)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`infra/cosmoschain/base.go` line 194 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/270#-Nbmw9W-7l7sNgW3i-bi:-NbslM6Y2b29i7cnt6wI:b-p5vrxq) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee61b9c7f63672e27e789998501566c93e0522d7/infra/cosmoschain/base.go#L194)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's export it here and reuse in `cored`
</blockquote></details>

I 100% agree wit this approach
@wojtek-coreum could you pls take care of this PR & finalize pls ?

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/270)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @vertex451)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
