### PR TITLE
Add `devnet` profile to `znet`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 375 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/318#-NkPTU8U401gaHek3bQi:-NkPTU8U401gaHek3bQj:b4cxkk7) ([raw file](https://github.com/CoreumFoundation/crust/blob/6457e76956521841bf362584845573c81a2b2a80/infra/apps/cored/cored.go#L375)):*
> ```Go
> 
> 	if c.config.IsValidator {
> 		appCfg.Pruning = "everything"
> ```

Is all will be OK if we have just 3 validators and explorer connected to it? I'm not sure.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/cored/cored.go` line 375 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/318#-NkPTU8U401gaHek3bQi:-NkPcNdUAVfLgDwW-wud:b-okbi6f) ([raw file](https://github.com/CoreumFoundation/crust/blob/6457e76956521841bf362584845573c81a2b2a80/infra/apps/cored/cored.go#L375)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is all will be OK if we have just 3 validators and explorer connected to it? I'm not sure.
</blockquote></details>

I removed this part

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/318#-NkR6wz7C31cUkxN6wOZ:-NkR6wz7C31cUkxN6wO_:b-94t7uu) (no related file):*
pls add it to the readme

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/318#-NkR6wz7C31cUkxN6wOZ:-NkUNPHj2S1X5y6-YAn9:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls add it to the readme
</blockquote></details>

Done.

___

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
