### PR TITLE
Add required replacements to build's go.mod

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/go.mod` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/185#-NSoYPxk0FM-yaefp4pK:-NSoYPxl3PtvTeXmzO11:b-37lwfl) ([raw file](https://github.com/CoreumFoundation/crust/blob/d8377237621b3a7632c3933134a2aaf95af1766f/build/go.mod#L7)):*
> ```XML
> go 1.19
> 
> replace (
> ```

What is the reason for it?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`build/go.mod` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/185#-NSoYPxk0FM-yaefp4pK:-NSqriRL9Tvx0ZAF88b6:b-l8l7r9) ([raw file](https://github.com/CoreumFoundation/crust/blob/d8377237621b3a7632c3933134a2aaf95af1766f/build/go.mod#L7)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the reason for it?
</blockquote></details>

same question

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/go.mod` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/185#-NSoYPxk0FM-yaefp4pK:-NSu-U384brCGyzzuAKS:b1cj605) ([raw file](https://github.com/CoreumFoundation/crust/blob/d8377237621b3a7632c3933134a2aaf95af1766f/build/go.mod#L7)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same question
</blockquote></details>

We import `coreum` and that repo imports tendermint `v0.34.26` which exists only in the informal systems' fork. I have no idea how come that code worked previously.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/go.mod` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/185#-NSoYPxk0FM-yaefp4pK:-NSu52VI5MF8-j0VdbZl:b-z9nvo5) ([raw file](https://github.com/CoreumFoundation/crust/blob/d8377237621b3a7632c3933134a2aaf95af1766f/build/go.mod#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We import `coreum` and that repo imports tendermint `v0.34.26` which exists only in the informal systems' fork. I have no idea how come that code worked previously.
</blockquote></details>

oh I see what you mean, that is reasonable
___
*[`build/go.mod` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/185#-NSu5F5i5C6Pew36KZtk:-NSu5F5i5C6Pew36KZtl:b79qfb4) ([raw file](https://github.com/CoreumFoundation/crust/blob/d8377237621b3a7632c3933134a2aaf95af1766f/build/go.mod#L14)):*
> ```XML
> 
> require (
> 	github.com/CoreumFoundation/coreum v0.1.2-0.20230301133054-73acab73fba1
> ```

but still unclear why the version of coreum was downgraded to `v0.1.2` ?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/go.mod` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/185#-NSu5F5i5C6Pew36KZtk:-NSuG8Rk3qvZfHY_Jgtm:b-3o1hor) ([raw file](https://github.com/CoreumFoundation/crust/blob/d8377237621b3a7632c3933134a2aaf95af1766f/build/go.mod#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but still unclear why the version of coreum was downgraded to `v0.1.2` ?
</blockquote></details>

I took the version from crust. Now upgraded both to the newest commit

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
