### PR TITLE
Add test verbose to the integration tests executor.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/220)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/220)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/testing/run.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/220#-NWfGU_FChOMNInLVhRQ:-NWfGU_FChOMNInLVhRR:by82950) ([raw file](https://github.com/CoreumFoundation/crust/blob/8231b2b204c3e763f7025200450f4ffc88d1b27d/infra/testing/run.go#L83)):*
> ```Go
> 	}
> 	if config.VerboseLogging {
> 		args = append(args, "-test.v")
> ```

You need to remove this then

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/220)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/testing/run.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/220#-NWfGU_FChOMNInLVhRQ:-NWfRNql91JSO6pYYRSl:b5mwxlj) ([raw file](https://github.com/CoreumFoundation/crust/blob/8231b2b204c3e763f7025200450f4ffc88d1b27d/infra/testing/run.go#L83)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You need to remove this then
</blockquote></details>

Agree, removed.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
