### PR TITLE
Disable funlen linter in integration-tests folder

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/137)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
I decided to disable this linter for integration-tests folder because we have quite a lot of long testing scenarios there and we don't really want to split them into different funcs

Currently there are a few but in the next coreum PRs more will be added

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/137#-:-NGXdPCE3AMfE7_1fMi-:b8s7dma)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
