### PR TITLE
Add linting for the current dir.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXizoi15a7ryYwdFpOd:-NXizoi25-C5XsqC5HJ4:bv2ns33) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L38)):*
> ```Go
> 	"images/relayer":                         relayer.BuildDockerImage,
> 	"lint":                                   lint,
> 	"lint/current-dir":                       lintCurrentDir,
> ```

I don't agree with this approach. Although the previous design might not be perfect, this is not really an improvement.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXizoi15a7ryYwdFpOd:-NXj49gH7gxZIxTbuzwU:b-7mlrre) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L38)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't agree with this approach. Although the previous design might not be perfect, this is not really an improvement. 
</blockquote></details>

marked non-blocking.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQnmMEft1XX0104Tm:-NXjQnmMEft1XX0104Tn:b-pzu51m) (no related file):*
Please add the same for `test/current-dir`

___
___
*[`build/index.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQ_8d3SiKJaVVTNhB:-NXjQ_8d3SiKJaVVTNhC:bqk3abc) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L74)):*
> ```Go
> }
> 
> func lintCurrentDir(ctx context.Context, deps build.DepsFunc) error {
> ```

You don't need this function. Just set `crust.LintCurrentDir` directly in the map

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQnmMEft1XX0104Tm:-NXjdt4aEpNVZzY05HHm:bmzxlew) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please add the same for `test/current-dir`
</blockquote></details>

Do you use it? If not then why do we need it?

___
___
*[`build/index.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXizoi15a7ryYwdFpOd:-NXje-lp0IPd4lbSDVb4:b-dd7mxq) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L38)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

marked non-blocking. 
</blockquote></details>

I need it to integrate with the bridge contract, which private and out of the crust visibility. And in general IMO just having the relevant, lint/test/integration-test/was and etc is fully enough to cover almost any case we need. And that's the way to make the crust more abstract.
___
*[`build/index.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQ_8d3SiKJaVVTNhB:-NXjeVK26OWUoto1TExC:b-9115tm) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need this function. Just set `crust.LintCurrentDir` directly in the map
</blockquote></details>

Why do we have a single-line function for all other cases?

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQnmMEft1XX0104Tm:-NXnWSU091E0-PatCRsQ:b-4alxlj) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you use it? If not then why do we need it?
</blockquote></details>

For now I use `go test .` but having it in crust would be nice if you already touched this idea

___
___
*[`build/index.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQ_8d3SiKJaVVTNhB:-NXnWgbL7wMQX5Jos3hv:blbns1r) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L74)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we have a single-line function for all other cases?
</blockquote></details>

Because they call many items in `deps`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQnmMEft1XX0104Tm:-NXnmVz_5Z9imPe3VX4R:bg5s7fv) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

For now I use `go test .` but having it in crust would be nice if you already touched this idea
</blockquote></details>

Do you want to be able to execute it from any folder? If yes it won't as simple, as with the lint, since I need it for the root only and we have the check `onModule` which checks the `go.mod` is in the dir and skips the execution for the rest. It is possible of course to make it work differently but this is definitely out of scope for the things I do now.

___
___
*[`build/index.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQ_8d3SiKJaVVTNhB:-NXnofKb9UKFTiU4N95-:b-b8usf4) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because they call many items in `deps`
</blockquote></details>

But one line anyways. So if we update this one we should update all of them.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`build/index.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQ_8d3SiKJaVVTNhB:-NXnxq6B39Xv-2CTN1iE:b-ioo2mp) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L74)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But one line anyways. So if we update this one we should update all of them.
</blockquote></details>

I mean:

```go
"lint/current-dir":                       crust.LintCurrentDir,
```

and remove this function completely

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/index.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXjQ_8d3SiKJaVVTNhB:-NXpAgIdDcdkiS4wECcc:brjizs1) ([raw file](https://github.com/CoreumFoundation/crust/blob/7043d4373ab4e43c1e2c7cc1de1255081ef5718e/build/index.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean:

```go
"lint/current-dir":                       crust.LintCurrentDir,
```

and remove this function completely
</blockquote></details>

I got it, but if we don't need it for the `LintCurrentDir` we don't need it for other cases as well. Should I remove all one line functions from the current file?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`build/golang/lint.go` line 47 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/222#-NXsfm978-J3UeZdskxa:-NXsfm978-J3UeZdskxb:b-2k0g8n) ([raw file](https://github.com/CoreumFoundation/crust/blob/ad8a28933389890ff86447d15967d3418e4ef874/build/golang/lint.go#L47)):*
> ```Go
> 		log := logger.Get(ctx)
> 		log.Warn("git status:")
> 		log.Warn(dirtyContent)
> ```

fmt.Println is used intentionally here, because logger will escape special characters producing unreadable output

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
