### PR TITLE
Integrate code-coverage into integration-tests which we run in znet

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR integrates coverage into cored running in znet. Coverage report is then reported to codecov.io.
The flow is the following:
1. build cored image with coverage enabled
2. start znet integration tests
3. stop znet & go processes (so coverage is dumped to disk)
4. convert coverage from binary format to text
5. upload separate coverage file to codecov

Depending coreum PR: https://github.com/CoreumFoundation/coreum/pull/777

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 91 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJOoj19YRixFAc5qsI:-NpJOoj19YRixFAc5qsJ:b-wb19h0) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/build/coreum/build.go#L91)):*
> ```Go
> 		CGOEnabled:     true,
> 		Tags:           tagsDocker,
> 		Flags:          []string{"-cover"},
> ```

This affects the release process too: https://github.com/CoreumFoundation/crust/blob/master/build/coreum/release.go#L41
___
*[`cmd/znet/main.go` line 252 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJQfNx6QXEJKCH_qCh:-NpJQfNx6QXEJKCH_qCi:bx1jftc) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/cmd/znet/main.go#L252)):*
> ```Go
> 		"coverage-output",
> 		defaultString("CRUST_ZNET_COVERAGE_OUTPUT",
> 			filepath.Clean(filepath.Join(repoRoot(), "../coreum/coverage/coreum-integration-tests-modules"))),
> ```

`config.RootDir` (https://github.com/CoreumFoundation/crust/blob/master/infra/config.go#L23) is already there
___
*[`infra/apps/cored/coverage.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJNVlX9vJosbAJQhRN:-NpJNVlYAAKSZCUXpCcB:bb8byqh) ([raw file](https://github.com/CoreumFoundation/crust/blob/2a59014f79aa017ec0e9a24c7cc5aab21094f6ab/infra/apps/cored/coverage.go#L25)):*
> ```Go
> 
> 	if err := libexec.Exec(ctx, cmd); err != nil {
> 		return errors.WithStack(err)
> ```

`Exec` already returns error with callstack
___
*[`pkg/znet/commands.go` line 257 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJNzEg5akpwTqW8qKI:-NpJNzEg5akpwTqW8qKJ:b-8d003t) ([raw file](https://github.com/CoreumFoundation/crust/blob/2a59014f79aa017ec0e9a24c7cc5aab21094f6ab/pkg/znet/commands.go#L257)):*
> ```Go
> 		coredAppHome := filepath.Join(config.AppDir, appName, "coreum-devnet-1") // TODO: hardcoded chain id
> 
> 		// We convert coverage from the first cored app we find since codcove result for all of them is identical
> ```

codcov -> codecov

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJj3_U0nP5ygoXKtbU:-NpJj3_U0nP5ygoXKtbV:b2slvt4) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/build/golang/go.go#L49)):*
> ```Go
> 
> 	// Flags is a slice of additional flags to pass to `go build`. E.g -cover, -compiler etc.
> 	Flags []string
> ```

Personally I would prefer to have an option like `ExportCoverageReport bool`

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/coreum/build.go` line 91 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJOoj19YRixFAc5qsI:-NpJqbpp8ULzqfKIOrRb:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/build/coreum/build.go#L91)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This affects the release process too: https://github.com/CoreumFoundation/crust/blob/master/build/coreum/release.go#L41
</blockquote></details>

Done.
___
*[`build/golang/go.go` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJj3_U0nP5ygoXKtbU:-NpJmIjpAmlmQLNk02ea:b-hb4tqr) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/build/golang/go.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Personally I would prefer to have an option like `ExportCoverageReport bool`
</blockquote></details>

I prefer flags and even in favour of replacing some existing attributes (e.g Tags) with Flags. I was going to propose this.

Because Flags are more flexible and since we are going to move this to a separate package and use in other components I really prefer to make it flexible to minimaize changes in the future. Using Flags we don't need to add new attribute for each new feature we want to integrate in the future.

We might want to add `-covermode` or `-coverpkg` in the future
___
*[`cmd/znet/main.go` line 252 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJQfNx6QXEJKCH_qCh:-NpJmAKiA4HlX5My_Vj0:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/cmd/znet/main.go#L252)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`config.RootDir` (https://github.com/CoreumFoundation/crust/blob/master/infra/config.go#L23) is already there
</blockquote></details>

Done.
___
*[`infra/apps/cored/coverage.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJNVlX9vJosbAJQhRN:-NpJloDq9pWrWZLpeOiM:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/2a59014f79aa017ec0e9a24c7cc5aab21094f6ab/infra/apps/cored/coverage.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`Exec` already returns error with callstack
</blockquote></details>

Done.
___
*[`pkg/znet/commands.go` line 257 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJNzEg5akpwTqW8qKI:-NpJliJw1SelgPikDVDg:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/2a59014f79aa017ec0e9a24c7cc5aab21094f6ab/pkg/znet/commands.go#L257)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

codcov -> codecov
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJj3_U0nP5ygoXKtbU:-NpKBhVG2Vl7m-jAr2wv:b-e1gion) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/build/golang/go.go#L49)):*
> I prefer flags and even in favour of replacing some existing attributes (e.g Tags) with Flags. I was going to propose this.

So let's do it for everything together. What I don't like is when idea is changed but legacy code is not adjusted, leaving us with two ideas existing together.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/golang/go.go` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpJj3_U0nP5ygoXKtbU:-NpLjr1C08gOsXcHIhRR:b-bi3irm) ([raw file](https://github.com/CoreumFoundation/crust/blob/93e847ee0c81e7b63222b1f6f0397a3060bb32ee/build/golang/go.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> I prefer flags and even in favour of replacing some existing attributes (e.g Tags) with Flags. I was going to propose this.

So let's do it for everything together. What I don't like is when idea is changed but legacy code is not adjusted, leaving us with two ideas existing together.
</blockquote></details>

I agree 
but I want to discuss before doing this change because it is not obvious
And Also I want to limit changes in this PR because we need to carefully test this Flags refactoring

Added task to the clickup, I will take it in the next sprint

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`cmd/znet/main.go` line 252 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpPPvS40CtQG29OZYH6:-NpPPvS40CtQG29OZYH7:bgosfdf) ([raw file](https://github.com/CoreumFoundation/crust/blob/35b2ca1d7456ad6f8c2c41d6f0c63e5161460aa9/cmd/znet/main.go#L252)):*
> ```Go
> 		"coverage-output",
> 		defaultString("CRUST_ZNET_COVERAGE_OUTPUT",
> 			filepath.Clean(filepath.Join(configF.RootDir, "coreum/coverage/coreum-integration-tests-modules"))),
> ```

What about IBC and upgrade tests ?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`cmd/znet/main.go` line 252 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/355#-NpPPvS40CtQG29OZYH6:-NpQ9k9NBNOpUXZ_G3qD:btae1nc) ([raw file](https://github.com/CoreumFoundation/crust/blob/35b2ca1d7456ad6f8c2c41d6f0c63e5161460aa9/cmd/znet/main.go#L252)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about IBC and upgrade tests ?
</blockquote></details>

yes, I wanted to discuss this separately )
Idea of this PR is to integrate codecov for modules tests and live with the way it works. And after this lets discuss what we do with other parts

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/355)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
