### PR TITLE
made changes to handle ibc upgrade

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/relayercosmos/relayer.go` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVERKoC-f93BHaGJcjo:-NVERKoD85AHyhgtYKeh:bnftyy6) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/relayer.go#L113)):*
> ```Go
> 		PrepareFunc: r.prepare,
> 		Entrypoint:  filepath.Join(targets.AppHomeDir, dockerEntrypoint),
> 		DockerArgs: []string{
> ```

why is it needed?
___
*[`infra/apps/relayercosmos/run.tmpl` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVER_mXADyxMBJHA1_c:-NVER_mXADyxMBJHA1_d:bj3goox) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/run.tmpl#L23)):*
> ```
> fi
> 
> if [ $(relayer query channels coreum --home /app/.relayer/ | wc -l) -eq 0 ]
> ```

Do you need `--home`? `HOME` env is set at the beginning of the script
___
*[`infra/apps/relayercosmos/run.tmpl` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVERiBC2VBPr0lcLbkV:-NVERiBC2VBPr0lcLbkW:b-v3s86i) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/run.tmpl#L23)):*
> ```
> fi
> 
> if [ $(relayer query channels coreum --home /app/.relayer/ | wc -l) -eq 0 ]
> ```

Please mark it with TODO as temporary
___
*[`infra/targets/docker.go` line 191 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVESCf88zLuSJb-ztAz:-NVESCf88zLuSJb-ztB-:bewwvt8) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/targets/docker.go#L191)):*
> ```Go
> 	}
> 
> 	if len(app.DockerArgs) > 0 {
> ```

`if` is not needed, `append` will work with empty slice

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/relayercosmos/relayer.go` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVERKoC-f93BHaGJcjo:-NVEwv8XB-cA2TFqxG77:bnehub3) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/relayer.go#L113)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it needed?
</blockquote></details>

The relayer stops itself if a chain it tries to connect to is down

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`infra/testing/run.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVFDkHl6QnekxCfDQtO:-NVFDkHl6QnekxCfDQtP:bn145ea) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/testing/run.go#L99)):*
> ```Go
> 
> 			for _, m := range appSet {
> 				coredApp, ok := m.(cored.Cored)
> ```

Let's try to get the cored as constant.
___
*[`infra/testing/run.go` line 105 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVFDbKiBYhDgDR8DDdJ:-NVFDbKiBYhDgDR8DDdK:bozkqeu) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/testing/run.go#L105)):*
> ```Go
> 			}
> 		case "coreum-ibc":
> 			gaiaNode := appSet.FindRunningApp(gaiad.AppType, "ibc-gaia")
> ```

We agreed to use constants here.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/relayercosmos/run.tmpl` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVERiBC2VBPr0lcLbkV:-NVTBdkQ1xic6SJ-uY93:boba6k6) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/run.tmpl#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please mark it with TODO as temporary
</blockquote></details>

I think TODO is not needed here. I had a TODO that I removed, but I think this new check is a better check than the previous one. but since Dima is taking care of it, it is up to him to decide.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/apps.go` line 250 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVTJ7ukDOUuLIhIqiVM:-NVTJ7ukDOUuLIhIqiVN:ba9j26t) ([raw file](https://github.com/CoreumFoundation/crust/blob/440a67d091b8bb76a17990d18de41d12beeece69/infra/apps/apps.go#L250)):*
> ```Go
> }
> 
> // BuildPrefixedAppName build the app name based on it's prefix and name.
> ```

build -> builds
it's -> its
___
*[`infra/apps/relayercosmos/run.tmpl` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVER_mXADyxMBJHA1_c:-NVTJMZ-4AVWq8cRmSWT:b-wovp42) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/run.tmpl#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you need `--home`? `HOME` env is set at the beginning of the script
</blockquote></details>

isn't `$HOME` used by defult if `--home` is skipped?
___
*[`infra/testing/run.go` line 100 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVTK10_AJLSMNWAoqlB:-NVTK10_AJLSMNWAoqlC:bejokwv) ([raw file](https://github.com/CoreumFoundation/crust/blob/440a67d091b8bb76a17990d18de41d12beeece69/infra/testing/run.go#L100)):*
> ```Go
> 
> 			for _, m := range appSet {
> 				m.Type()
> ```

leftover?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/relayercosmos/run.tmpl` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVER_mXADyxMBJHA1_c:-NVT5EpT8JA1EwFEzw0g:bt2vr1b) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/run.tmpl#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you need `--home`? `HOME` env is set at the beginning of the script
</blockquote></details>

Fixed.
___
*[`infra/apps/relayercosmos/run.tmpl` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVERiBC2VBPr0lcLbkV:-NVT5T-73ibwb7yYCg6e:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/apps/relayercosmos/run.tmpl#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please mark it with TODO as temporary
</blockquote></details>

Done
___
*[`infra/targets/docker.go` line 191 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVESCf88zLuSJb-ztAz:-NVT5_pV-JuuutwJraM0:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/targets/docker.go#L191)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`if` is not needed, `append` will work with empty slice
</blockquote></details>

Updated.
___
*[`infra/testing/run.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVFDkHl6QnekxCfDQtO:-NVT5sPG-suLkzAYwEBb:bz6tq8q) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/testing/run.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's try to get the cored as constant.
</blockquote></details>

We can't do it that's the way here, because we use the type attributes, that are not present in the interface.
___
*[`infra/testing/run.go` line 105 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVFDbKiBYhDgDR8DDdJ:-NVTAnhY2xCukwQ4wxaj:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/crust/blob/03595ba10374a2f9e702c13c4531957df9e739a0/infra/testing/run.go#L105)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We agreed to use constants here. 
</blockquote></details>

Updated.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/apps.go` line 250 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVTJ7ukDOUuLIhIqiVM:-NVTLehe-TRhUjpmZIof:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/crust/blob/440a67d091b8bb76a17990d18de41d12beeece69/infra/apps/apps.go#L250)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

build -> builds
it's -> its
</blockquote></details>

Updated.
___
*[`infra/testing/run.go` line 100 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVTK10_AJLSMNWAoqlB:-NVTLZFs2k0mnPA4SgG2:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/crust/blob/440a67d091b8bb76a17990d18de41d12beeece69/infra/testing/run.go#L100)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

Updated.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`infra/apps/apps.go` line 250 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/206#-NVTJ7ukDOUuLIhIqiVM:-NVTMvCv8bMMDisnHMeC:b-9tubq3) ([raw file](https://github.com/CoreumFoundation/crust/blob/440a67d091b8bb76a17990d18de41d12beeece69/infra/apps/apps.go#L250)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

still build ->  builds

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
