### PR TITLE
Remove legacy signatures coreum types

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/126)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/126)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/126#-NEAlFR4BBqrm-LIyiux:-NEAlFR4BBqrm-LIyiuy:bvc1tf4) (no related file):*
Approved, but wait for Wojtek to review as well since he knows the crust side better than I .

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/126)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/126)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/126)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Pull request merged**
