### PR TITLE
Update big-dipper-ui tag to devnet-latest.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Update big-dipper-ui tag to devnet-latest.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/bigdipper/bigdipper.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/332#-NlxdArL0mYiBxCKyU4d:-Nm-qCpO0jFsCZcY8HGy:b-dlrblw) ([raw file](https://github.com/CoreumFoundation/crust/blob/ab7e95518a9ed4c109c2bb3e0cebf2eb2f793106/infra/apps/bigdipper/bigdipper.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think Alex told that he merged devnet branch into master
Let me ask him what is the state there
</blockquote></details>

@akhlopiachyi Will you merege it to master?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, and @miladz68)

___
*[`infra/apps/bigdipper/bigdipper.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/332#-Nm0KsHr5tWU2x6_Ne0u:-Nm0KsHr5tWU2x6_Ne0v:bt79p2d) ([raw file](https://github.com/CoreumFoundation/crust/blob/ab7e95518a9ed4c109c2bb3e0cebf2eb2f793106/infra/apps/bigdipper/bigdipper.go#L59)):*
> ```Go
> func (bd BigDipper) Deployment() infra.Deployment {
> 	return infra.Deployment{
> 		Image: "coreumfoundation/big-dipper-ui:devnet-latest",
> ```

Then you need to modify this as well: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/bigdipper/bigdipper.go#L59

We could also implement `release` procedure like we did for `coreum`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/bigdipper/bigdipper.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/332#-Nm0KsHr5tWU2x6_Ne0u:-Nm0xHCnD2icxvRi9GWl:b-ams1lf) ([raw file](https://github.com/CoreumFoundation/crust/blob/ab7e95518a9ed4c109c2bb3e0cebf2eb2f793106/infra/apps/bigdipper/bigdipper.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Then you need to modify this as well: https://github.com/CoreumFoundation/crust/blob/master/infra/apps/bigdipper/bigdipper.go#L59

We could also implement `release` procedure like we did for `coreum`
</blockquote></details>

But it release it differently.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @dzmitryhil, and @miladz68)

___
*[`infra/apps/bigdipper/bigdipper.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/332#-Nm0KsHr5tWU2x6_Ne0u:-Nm14QFM-ZyglmpKGien:b3kre) ([raw file](https://github.com/CoreumFoundation/crust/blob/ab7e95518a9ed4c109c2bb3e0cebf2eb2f793106/infra/apps/bigdipper/bigdipper.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But it release it differently.
</blockquote></details>

?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/bigdipper/bigdipper.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/332#-Nm0KsHr5tWU2x6_Ne0u:-Nm4yqMe4NGwHwaD8YOw:br5oo1d) ([raw file](https://github.com/CoreumFoundation/crust/blob/ab7e95518a9ed4c109c2bb3e0cebf2eb2f793106/infra/apps/bigdipper/bigdipper.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

?
</blockquote></details>

I mean we don't need to implement the `release` or `build` of the repos since this is the responsibility on the repos.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 2 unresolved discussions (waiting on @akhlopiachyi and @wojtek-coreum)

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: all files reviewed, 1 unresolved discussion (waiting on @akhlopiachyi)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/332)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
