### PR TITLE
Use genesis template depending on cored version

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/223#-NXuHyDW9yNTYMyoZhvM:-NXuHyDW9yNTYMyoZhvN:b-ndjvlj) ([raw file](https://github.com/CoreumFoundation/crust/blob/c865b2c525f183d29405b912461ecfecc9c92e65/go.mod#L10)):*
> ```XML
> )
> 
> replace github.com/tendermint/tendermint => github.com/cometbft/cometbft v0.34.27
> ```

why so many changes to go.mod ?
___
*[`pkg/znet/commands.go` line 303 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/223#-NXuHkR-5PYwu_gr3ASZ:-NXuHkR-5PYwu_gr3AS_:b-yg01nd) ([raw file](https://github.com/CoreumFoundation/crust/blob/c865b2c525f183d29405b912461ecfecc9c92e65/pkg/znet/commands.go#L303)):*
> ```Go
> 		return coreumconfig.GenesisV2Template, nil
> 	case "v1.0.0":
> 		return coreumconfig.GenesisV1Template, nil
> ```

I would say we should refactor crust to generate the template via cored cli interaction, instead of using golang.

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/znet/commands.go` line 303 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/223#-NXuHkR-5PYwu_gr3ASZ:-NXycZJa834dS0M5NqSA:b-cyie5r) ([raw file](https://github.com/CoreumFoundation/crust/blob/c865b2c525f183d29405b912461ecfecc9c92e65/pkg/znet/commands.go#L303)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I would say we should refactor crust to generate the template via cored cli interaction, instead of using golang. 
</blockquote></details>

I agree this doesn't look nice 

However, I'm ok to merge it as it is now to speed up the process.
And I have added this point to our crust refactoring task so we will address it there

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/223#-NXuHyDW9yNTYMyoZhvM:-NXymIOA5bsr7X2_xxsJ:bnt40ej) ([raw file](https://github.com/CoreumFoundation/crust/blob/c865b2c525f183d29405b912461ecfecc9c92e65/go.mod#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why so many changes to go.mod ?
</blockquote></details>

Coreum was not upgraded for a long time

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
