### PR TITLE
Add url to bdjuno config for compatibility with v0.47

### PR DESCRIPTION
**Pull request by alinetskyi**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/300)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/300)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @miladz68, and @ysv)

___
*[`infra/apps/blockexplorer/bdjuno/config/config.tmpl.yaml` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/300#-NicoI1O9tLPi1SeejjV:-NicoI1O9tLPi1SeejjW:blro88z) ([raw file](https://github.com/CoreumFoundation/crust/blob/7e2e10d36486d7188fe52956c634bcd40c319372/infra/apps/blockexplorer/bdjuno/config/config.tmpl.yaml#L46)):*
> ```YAML
> database:
>   url: postgresql://{{ .Postgres.User }}@{{ .Postgres.Host }}:{{ .Postgres.Port }}/{{ .Postgres.DB }}?sslmode=disable&search_path=public
>   name: {{ .Postgres.DB }}
> ```

Why do you need those args if you use the `url` ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/300)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @miladz68, and @ysv)

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/300)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/blockexplorer/bdjuno/config/config.tmpl.yaml` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/300#-NicoI1O9tLPi1SeejjV:-Nid_KkD4gFm5nPwphjf:bkuxyvc) ([raw file](https://github.com/CoreumFoundation/crust/blob/7e2e10d36486d7188fe52956c634bcd40c319372/infra/apps/blockexplorer/bdjuno/config/config.tmpl.yaml#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need those args if you use the `url` ?
</blockquote></details>

because this will allow to support old and new versions of bdjuno

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
