### PR TITLE
Use functions instead of constants to run znet

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/131#-NEkPZui5Yl4qNjVwQKH:-NEkPZui5Yl4qNjVwQKI:b-c3m9cj) (no related file):*
I bet CI won't pass because of incorrect validator set

___
___
*[`go.mod` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/crust/131#-NEkPVdpEW9RYoKiW8aZ:-NEkPVdq5t4vSLG1kfJZ:bywlish) ([raw file](https://github.com/coreumfoundation/crust/blob/a9825bb8a6388dddaf37ed593165a1cfc73f2ade/go.mod#L11)):*
> ```XML
> 
> require (
> 	github.com/CoreumFoundation/coreum v0.0.0-20221019130600-815c8bae14ea
> ```

blocking until this is in master

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/131#-NEkPZui5Yl4qNjVwQKH:-NEkU_Yj1YTtpMS71sjp:bekx2rr) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I bet CI won't pass because of incorrect validator set
</blockquote></details>

Right, it won't the fix in progress.

___

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/131#-NEkPZui5Yl4qNjVwQKH:-NEkY6VG5u1Pa1snW2ip:b-mj1yrb) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, it won't the fix in progress.
</blockquote></details>

CI passed.

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/crust/131#-NEkPVdpEW9RYoKiW8aZ:-NEkcv0h5_ujidVTvYa_:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/a9825bb8a6388dddaf37ed593165a1cfc73f2ade/go.mod#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

blocking until this is in master
</blockquote></details>

Updated.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
