### PR TITLE
Update go version to 1.20.5 and fix btcd import conflict.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/239#-NZ4x9tK48aONtmcTXSw):*
what's the issue?

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 122 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/239#-NZ5NxX82XtmqV3zYxaj:-NZ5NxX82XtmqV3zYxak:beo0vg6) ([raw file](https://github.com/CoreumFoundation/crust/blob/aa004e99cbf45151154d20872d85e517df76edb3/.github/workflows/ci.yml#L122)):*
> ```YAML
>         with:
>           key: ${{ runner.os }}-docker-${{ steps.get-year-week.outputs.date }} # year-week key
>           restore-keys: |
> ```

same thing for go and wasm cache?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/239#-NZ4x9tK48aONtmcTXSw):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what's the issue?
</blockquote></details>

The issue is detected, it was wit the `restore-key`  
The cache uses the `restore-key`  as a caching key if the cache key not found. So every week we update it in order to reset, but since the `restore-key`  is present in the config it takes the `restore-key`  cache instead of the reinit.
___
*[`.github/workflows/ci.yml` line 122 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/239#-NZ5NxX82XtmqV3zYxaj:-NZ5qFgD3CoqpxF1PdC3:bzf96xk) ([raw file](https://github.com/CoreumFoundation/crust/blob/aa004e99cbf45151154d20872d85e517df76edb3/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

same thing for go and wasm cache?
</blockquote></details>

Check the prev comment. IMO for the wasm and go we can keep the basic version, since 90% of it still actual. But that's discussable. 
@miladz68 @ysv WDYT ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 122 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/239#-NZ5NxX82XtmqV3zYxaj:-NZ61zsmAG2eZgdt6Syp:b-x7hs24) ([raw file](https://github.com/CoreumFoundation/crust/blob/aa004e99cbf45151154d20872d85e517df76edb3/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check the prev comment. IMO for the wasm and go we can keep the basic version, since 90% of it still actual. But that's discussable. 
@miladz68 @ysv WDYT ?
</blockquote></details>

But over time most of the dependencies get obsolete. That's the idea of cleaning it up from time to time

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/239)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 122 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/239#-NZ5NxX82XtmqV3zYxaj:-NZ6iW050VhYlcR6SeXT:bskfy0q) ([raw file](https://github.com/CoreumFoundation/crust/blob/aa004e99cbf45151154d20872d85e517df76edb3/.github/workflows/ci.yml#L122)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But over time most of the dependencies get obsolete. That's the idea of cleaning it up from time to time
</blockquote></details>

Moved to separate PR: https://github.com/CoreumFoundation/crust/pull/241

**Pull request merged**
