### PR TITLE
Resolve linting issues with an "unparam" check annotation line

### PR DESCRIPTION
**Pull request by xlab**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)

### CODE REVIEW

**Review by oliverasistemas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/17#-N6lJBKB89A9yjxrfngu:-N6lJBKB89A9yjxrfngv:b-kc4d8m) (no related file):*
Are we introducing this PR to fix the failing ci lint on this other PR ?
https://github.com/CoreumFoundation/coreum/pull/91



If so, I don't think that the problem is in the crust repo, inspecting the ci logs points to coreum repo itself.

https://github.com/CoreumFoundation/coreum/runs/7271573028?check_suite_focus=true 

___

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: all files reviewed, 1 unresolved discussion (waiting on @xlab and @ysv)

**Comment by xlab** [comment]
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/17#-N6lJBKB89A9yjxrfngu:-N6m9dZLESy9OrB0R7L7:b-15odos) (no related file):*
1) Yes we figured out this line breaks either Mac linting or CI linting. Looking for another way to fix this for both platforms

2)
>  I don't think that the problem is in the crust repo, inspecting the ci logs points to coreum repo itself

Please look careful

**Review by xlab — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: all files reviewed, 1 unresolved discussion (waiting on @xlab and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/17#-N6lJBKB89A9yjxrfngu:-N6mGzsQ8dhVLQgHT1en:b-q5z4dr) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you are pointing to a warning, I don't think that is an issue. 
</blockquote></details>

This is the error that I see github action runner. it is not pointing to crust anywhere. 
Am i missing something ?
```
- log: "2022-07-10 15:37:08.833 ERROR Application returned error: linter errors found in module '../coreum': exit status 1: "/home/runner/work/coreum/crust/bin/golangci-lint run --config /home/runner/work/coreum/crust/build/.golangci.yaml""
  details:
    error: 
      msg: "linter errors found in module '../coreum': exit status 1: "/home/runner/work/coreum/crust/bin/golangci-lint run --config /home/runner/work/coreum/crust/build/.golangci.yaml""
      stack:
      - "github.com/CoreumFoundation/coreum/build.goLint.func1 github.com/CoreumFoundation/coreum/build/go.go:175"
      - "github.com/CoreumFoundation/coreum/build.onModule.func1 github.com/CoreumFoundation/coreum/build/go.go:223"
      - "path/filepath.walkDir path/filepath/path.go:398"
      - "path/filepath.walkDir path/filepath/path.go:417"
      - "path/filepath.WalkDir path/filepath/path.go:481"
      - "github.com/CoreumFoundation/coreum/build.onModule github.com/CoreumFoundation/coreum/build/go.go:216"
      - "github.com/CoreumFoundation/coreum/build.goLint github.com/CoreumFoundation/coreum/build/go.go:170"
      - "reflect.Value.call reflect/value.go:556"
      - "reflect.Value.Call reflect/value.go:339"
      - "github.com/CoreumFoundation/coreum-tools/pkg/ioc.(*Container).Call github.com/CoreumFoundation/coreum-tools@v0.1.6/pkg/ioc/container.go:220"
      - "github.com/CoreumFoundation/coreum-tools/pkg/build.(*iocExecutor).Execute.func1 github.com/CoreumFoundation/coreum-tools@v0.1.6/pkg/build/build.go:97"
      - "runtime.goexit runtime/asm_amd64.s:1571"
    logged:
      by: "crust"
      at: "github.com/CoreumFoundation/coreum-tools@v0.1.6/pkg/run/run.go:86"
```

___

**Comment by xlab** [comment]
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/17#-N6lJBKB89A9yjxrfngu:-N6mIWrpBwyAaKex4elk:bn07zxu) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is the error that I see github action runner. it is not pointing to crust anywhere. 
Am i missing something ?
```
- log: "2022-07-10 15:37:08.833 ERROR Application returned error: linter errors found in module '../coreum': exit status 1: "/home/runner/work/coreum/crust/bin/golangci-lint run --config /home/runner/work/coreum/crust/build/.golangci.yaml""
  details:
    error: 
      msg: "linter errors found in module '../coreum': exit status 1: "/home/runner/work/coreum/crust/bin/golangci-lint run --config /home/runner/work/coreum/crust/build/.golangci.yaml""
      stack:
      - "github.com/CoreumFoundation/coreum/build.goLint.func1 github.com/CoreumFoundation/coreum/build/go.go:175"
      - "github.com/CoreumFoundation/coreum/build.onModule.func1 github.com/CoreumFoundation/coreum/build/go.go:223"
      - "path/filepath.walkDir path/filepath/path.go:398"
      - "path/filepath.walkDir path/filepath/path.go:417"
      - "path/filepath.WalkDir path/filepath/path.go:481"
      - "github.com/CoreumFoundation/coreum/build.onModule github.com/CoreumFoundation/coreum/build/go.go:216"
      - "github.com/CoreumFoundation/coreum/build.goLint github.com/CoreumFoundation/coreum/build/go.go:170"
      - "reflect.Value.call reflect/value.go:556"
      - "reflect.Value.Call reflect/value.go:339"
      - "github.com/CoreumFoundation/coreum-tools/pkg/ioc.(*Container).Call github.com/CoreumFoundation/coreum-tools@v0.1.6/pkg/ioc/container.go:220"
      - "github.com/CoreumFoundation/coreum-tools/pkg/build.(*iocExecutor).Execute.func1 github.com/CoreumFoundation/coreum-tools@v0.1.6/pkg/build/build.go:97"
      - "runtime.goexit runtime/asm_amd64.s:1571"
    logged:
      by: "crust"
      at: "github.com/CoreumFoundation/coreum-tools@v0.1.6/pkg/run/run.go:86"
```
</blockquote></details>

The original issue with the line was from Coreum repo, because we used `crust lint` for a Coreum branch.

In CI output for the crust you posted above, it's not mentioning the line that caused `linter errors found in module '../coreum'`

**Review by miladz68 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17#-:-N6mewWj2q89eIOQC_13:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by xlab — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xlab)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: all files reviewed, 2 unresolved discussions (waiting on @xlab)

___
*[`build/go.go` line 171 at r3](https://reviewable.io/reviews/coreumfoundation/crust/17#-N6mj_ua4IoemWgg-iUC:-N6mj_ub4m7HC6_JCx9B:bqdpe64) ([raw file](https://github.com/coreumfoundation/crust/blob/076a59fd980dd7ce6aea4fa9c78edfb804e7a2f4/build/go.go#L171)):*
> ```Go
> 	err := onModule(func(path string) error {
> 		log.Info("Running linter", zap.String("path", path),
> 			zap.String("goOS", runtime.GOOS),
> ```

Do we need those two fields to be reported? They are constants on each computer so they don't add much information.
___
*[`build/go.go` line 173 at r3](https://reviewable.io/reviews/coreumfoundation/crust/17#-N6mivHa9OZ0cZNo3eds:-N6mivHcDqVIuCQQAuI1:bl3v0x5) ([raw file](https://github.com/coreumfoundation/crust/blob/076a59fd980dd7ce6aea4fa9c78edfb804e7a2f4/build/go.go#L173)):*
> ```Go
> 			zap.String("goOS", runtime.GOOS),
> 			zap.String("goArch", runtime.GOARCH),
> 			zap.String("goVersion", runtime.Version()),
> ```

What's the idea behind reporting go version here? It will report the version used by `crust` runtime not necessarily the one used by `golangci-lint`.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xlab)

**Review by wojtek-coreum — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17#-:-N6s2MzIDVjGHRCkihSj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xlab)

**Review by xlab — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xlab)

**Pull request merged**
