### PR TITLE
Upgrade WASM VM to v1.1.2

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 144 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/229#-NYXJIUH1AQviyLx2rWY:-NYXJIUH1AQviyLx2rWZ:b25db61) ([raw file](https://github.com/CoreumFoundation/crust/blob/cbe3ce52eb99f7997cb6b28c008850658d40e6d4/build/tools/tools.go#L144)):*
> ```Go
> 		Sources: Sources{
> 			PlatformDockerAMD64: {
> 				URL:  "https://github.com/CosmWasm/wasmvm/releases/download/v1.1.2/libwasmvm_muslc.x86_64.a",
> ```

Are you sure that it's backward compatible with the current?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 144 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/229#-NYXJIUH1AQviyLx2rWY:-NYXJVjZ5Vk8EDZx9RlP:b-i24wo6) ([raw file](https://github.com/CoreumFoundation/crust/blob/cbe3ce52eb99f7997cb6b28c008850658d40e6d4/build/tools/tools.go#L144)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Are you sure that it's backward compatible with the current? 
</blockquote></details>

And why do we need tp update it?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`build/tools/tools.go` line 144 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/229#-NYXJIUH1AQviyLx2rWY:-NYXLeQOD1Uz_qtikm2A:b-c611lr) ([raw file](https://github.com/CoreumFoundation/crust/blob/cbe3ce52eb99f7997cb6b28c008850658d40e6d4/build/tools/tools.go#L144)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

And why do we need tp update it?
</blockquote></details>

According to their doc: https://coreumfoundation.slack.com/archives/C052QGQ9QCE/p1686084672056569
This is how it should be done

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`build/tools/tools.go` line 144 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/229#-NYXJIUH1AQviyLx2rWY:-NYXMMuE9utr6rPJ4GOw:b-9jgmpq) ([raw file](https://github.com/CoreumFoundation/crust/blob/cbe3ce52eb99f7997cb6b28c008850658d40e6d4/build/tools/tools.go#L144)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

According to their doc: https://coreumfoundation.slack.com/archives/C052QGQ9QCE/p1686084672056569
This is how it should be done
</blockquote></details>

And even compiled cored binary says this: `Error: libwasmversion mismatch. got: 1.1.1; expected: v1.1.2`

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
