### PR TITLE
update network config structure

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/config.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVib0is6lI3fX8wgN8I:-NVib0is6lI3fX8wgN8J:b8akiqd) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/config.go#L51)):*
> ```Go
> 			ProposalConfig: config.GovProposalConfig{
> 				MinDepositAmount: "1000",
> 				VotingPeriod:     votingPeriod.String(),
> ```

IMO you should either use the constants or values directly.
___
*[`infra/apps/cored/cored.go` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibU_nAm9Z9pORXEfR:-NVibU_nAm9Z9pORXEfS:b-9g3ead) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L98)):*
> ```Go
> 		nw := cfg.NetworkConfig.Provider.(config.DynamicConfigProvider)
> 		nw = nw.WithGenesisTx(createValidatorTx)
> 		cfg.NetworkConfig.Provider = nw
> ```

It's a matter of taste, but you can make it all in one line. 
___
*[`infra/apps/cored/cored.go` line 399 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibl4I-ff5m9yi3FVl:-NVibl4I-ff5m9yi3FVm:b-6bp5d0) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L399)):*
> ```Go
> 
> // SaveGenesis saves json encoded representation of the genesis config into file
> func (c Cored) SaveGenesis(homeDir string) error {
> ```

We decided to keep the coreum import, in order not to duplicate the code. But here we have the code duplication and still have the import.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/cored/config.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVicrc3Ee-RqTpQ_Ktp:-NVicrc3Ee-RqTpQ_Ktq:bcyp9dc) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/config.go#L44)):*
> ```Go
> 	}
> 
> 	networkConfig.Provider = config.DynamicConfigProvider{
> ```

Provider could be set in the struct initialization above
___
*[`infra/apps/cored/cored.go` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVid9eI0hjJyxickILX:-NVid9eI0hjJyxickILY:b8soxpl) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L50)):*
> ```Go
> 	BinDir            string
> 	WrapperDir        string
> 	NetworkConfig     *config.NetworkConfig
> ```

Do we need a pointer?
___
*[`infra/apps/cored/cored.go` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibU_nAm9Z9pORXEfR:-NVidds12vCvUya9yQ0T:bualne4) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L98)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's a matter of taste, but you can make it all in one line. 
</blockquote></details>

nw -> networkProvider like in other places

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/config.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVicrc3Ee-RqTpQ_Ktp:-NVnFIZh1nfS1UsYVW5h:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/config.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Provider could be set in the struct initialization above
</blockquote></details>

Done.
___
*[`infra/apps/cored/cored.go` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVid9eI0hjJyxickILX:-NVnFYdK2eO5qD7ijCLR:b-nakgsz) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we need a pointer?
</blockquote></details>

Yes, all the changes made to config by all cored instances should be globally visible and same. 
___
*[`infra/apps/cored/cored.go` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibU_nAm9Z9pORXEfR:-NVnFwQz4UOA4c75xO0B:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nw -> networkProvider like in other places
</blockquote></details>

Done
___
*[`infra/apps/cored/cored.go` line 399 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibl4I-ff5m9yi3FVl:-NVnEa_LCtYM5_EzLkH_:bmwpbnj) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L399)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We decided to keep the coreum import, in order not to duplicate the code. But here we have the code duplication and still have the import.
</blockquote></details>

SaveGenesis method does not exist on the coreum part, since it is not used there.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVid9eI0hjJyxickILX:-NVntvUO8e4iBFu-GVDy:b-c5wk7c) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Yes, all the changes made to config by all cored instances should be globally visible and same. 
</blockquote></details>

Could you give an example? Because what I see is that each node creates an independent config (which is the same in every case), generates genesis.json and that's it
___
*[`pkg/znet/commands.go` line 120 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVnuzIx0Sbu_RWQVSA0:-NVnuzIx0Sbu_RWQVSA1:brugwhz) ([raw file](https://github.com/CoreumFoundation/crust/blob/0736cb5d3137fe70e1ddbd23885ce6e1a5c3ee8b/pkg/znet/commands.go#L120)):*
> ```Go
> 		return err
> 	}
> 	networkConfig.SetSDKConfig()
> ```

Do we need it just to encode addresses? If yes, could we move our address encoder we have inside integration tests of coreum to the NetworkConfig and use everywhere?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVid9eI0hjJyxickILX:-NVnyfzs6FLMyecyoOXH:bwqk3do) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you give an example? Because what I see is that each node creates an independent config (which is the same in every case), generates genesis.json and that's it
</blockquote></details>

each node adds it genesis transaction to the config. this change must be globally visible, otherwise each node will end up with a different genesis file. 
___
*[`pkg/znet/commands.go` line 120 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVnuzIx0Sbu_RWQVSA0:-NVoOLBa2OJWKmP3Hh7R:bcvauln) ([raw file](https://github.com/CoreumFoundation/crust/blob/0736cb5d3137fe70e1ddbd23885ce6e1a5c3ee8b/pkg/znet/commands.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we need it just to encode addresses? If yes, could we move our address encoder we have inside integration tests of coreum to the NetworkConfig and use everywhere?
</blockquote></details>

as discussed that is beyond the scope of this task.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 399 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibl4I-ff5m9yi3FVl:-NW15dtT4eWLgv54TWUo:b-e7axru) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L399)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

SaveGenesis method does not exist on the coreum part, since it is not used there. 
</blockquote></details>

Create now, thanks.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 399 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVibl4I-ff5m9yi3FVl:-NW1KBTWDYguGyWxuBhx:bkk875l) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L399)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Create now, thanks. 
</blockquote></details>

we are trying to reduce the dependency, if the method is not used in coreum project and is crust specific, it should not live on coreum side.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVid9eI0hjJyxickILX:-NWC2cCrD1a94H_b0Aac:bc99v9) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

each node adds it genesis transaction to the config. this change must be globally visible, otherwise each node will end up with a different genesis file. 
</blockquote></details>

Then you need a mutex somewhere around this:
```go
		networkProvider := cfg.NetworkConfig.Provider.(config.DynamicConfigProvider)
		cfg.NetworkConfig.Provider = networkProvider.WithGenesisTx(createValidatorTx)
```

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

___
*[`infra/apps/cored/cored.go` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/214#-NVid9eI0hjJyxickILX:-NWC9nlh2RLnOXaHjEZL:b-6z5fa8) ([raw file](https://github.com/CoreumFoundation/crust/blob/770ee80063b2cf40a080489523f46576ed59a23e/infra/apps/cored/cored.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that code is not concurrent and is not really meant to be concurrent. 
</blockquote></details>

ah, I see now. ok

**Pull request merged**
