### PR TITLE
Use sql files from the bdjuno image.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3EKCL5baaLXJgAQHh:b-hisqwh) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
> ```Go
> 		Entrypoint:  filepath.Join(targets.AppHomeDir, dockerEntrypoint),
> 		DockerArgs: []string{
> 			"--user", "root",
> ```

Remove `RunAsUser: true` instead

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3EPLQAus14CuG54Fx:b-d2t9p0) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Remove `RunAsUser: true` instead
</blockquote></details>

Do you know why root is required?

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 20 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3KU2y2VUjZt_MK-q2:bjgsj93) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can't access the files copied to /var/lib/postgresql/schema without the root. 
</blockquote></details>

So maybe there is `r` permission missing on one of the dirs in the path?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3MEdQ-l83wFSDaEWF:b-lwt7ze) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

actually `x` I think
</blockquote></details>

I tested with the chmod 777 after the creation and the result was the same - permission denied.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3VKFE2pRzmSQSXVo-:b-uy0bl6) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I tested with the chmod 777 after the creation and the result was the same - permission denied. 
</blockquote></details>

Adding this to dockerfile fixes the problem:

```
RUN chmod a+rx /var/lib/postgresql && \
    chmod a+rx /var/lib/postgresql/schema
```

I don't know if it is required for both directories, please check. Also it might be that not both `r` and `x` are needed but I guess they are because you iterate over files in the dir.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3VlIU4MrVPnUZj-dl:b-owcokf) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Adding this to dockerfile fixes the problem:

```
RUN chmod a+rx /var/lib/postgresql && \
    chmod a+rx /var/lib/postgresql/schema
```

I don't know if it is required for both directories, please check. Also it might be that not both `r` and `x` are needed but I guess they are because you iterate over files in the dir.
</blockquote></details>

and maybe `r` or `x` is already set

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY3ccFGD49je1XjNXrO:br4val1) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

and maybe `r` or `x` is already set
</blockquote></details>

Seems like that helped. I guess the issue was with the ```/var/lib/postgresql``` since I didn't do it before.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NY6zSs83NwPDnNpFjqs:b-562zee) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Seems like that helped. I guess the issue was with the ```/var/lib/postgresql``` since I didn't do it before. 
</blockquote></details>

So please create PR for that and remove root from here

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/224)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`infra/apps/bdjuno/bdjuno.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/224#-NY3EKCK56wCmtMcRd4Q:-NYHMr1r6lefyamsJTf2:bpzryq1) ([raw file](https://github.com/CoreumFoundation/crust/blob/ef5af0f238fa8f97eaf87c3c48fd6a76e177fd4a/infra/apps/bdjuno/bdjuno.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So please create PR for that and remove root from here
</blockquote></details>

https://github.com/CoreumFoundation/bdjuno/pull/22

**Pull request merged**
