### PR TITLE
removed SetAccountPrefixes function from zstress cmd folder

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/znet/main.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/crust/31#-N8NJW-Q2ZUjSRk_xVcm:-N8NJW-R7fopddIhSyok:biaazyi) ([raw file](https://github.com/coreumfoundation/crust/blob/6689d05703a9277c958d1a22e67924af4fdc4fac/cmd/znet/main.go#L20)):*
> ```Go
> 
> func main() {
> 	network, _ := app.NetworkByChainID(app.Devnet)
> ```

panic on error?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/znet/main.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/crust/31#-N8NJW-Q2ZUjSRk_xVcm:-N8NRU8PEf-ZYFHRuAxu:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/6689d05703a9277c958d1a22e67924af4fdc4fac/cmd/znet/main.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

panic on error?
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31#-:-N8OeFhA1fL9EF1Ro_Ja:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas and @xlab)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas and @xlab)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas and @xlab)

**Pull request merged**
