### PR TITLE
Create `lib` folder manually to prevent misleading warning on darwin

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/243#-NZVIaVR1NGhZGc8eiaA:-NZVIaVR1NGhZGc8eiaB:b-1graws) ([raw file](https://github.com/CoreumFoundation/crust/blob/96ab660ca670347088f95cd0c97c6b5782be5907/build/golang/go.go#L94)):*
> ```Go
> 	}
> 
> 	libDir := filepath.Join(tools.CacheDir(), "lib")
> ```

What is the difference between lib and bin folders?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`build/golang/go.go` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/243#-NZVIaVR1NGhZGc8eiaA:-NZVQOY_CHJz9vaqjpma:b-hqo6y6) ([raw file](https://github.com/CoreumFoundation/crust/blob/96ab660ca670347088f95cd0c97c6b5782be5907/build/golang/go.go#L94)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the difference between lib and bin folders?
</blockquote></details>

Same as between /bin and /lib. bin contains executable files, lib contains shared libraries. Currentlyw e only have libwasmvm there I think

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/243#-NZVIaVR1NGhZGc8eiaA:-NZVwMqLBXHYVdZynZh0:bc69e36) ([raw file](https://github.com/CoreumFoundation/crust/blob/96ab660ca670347088f95cd0c97c6b5782be5907/build/golang/go.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Same as between /bin and /lib. bin contains executable files, lib contains shared libraries. Currentlyw e only have libwasmvm there I think
</blockquote></details>

But how about add them to the same folder or add lib to CI cache as well.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/golang/go.go` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/243#-NZVIaVR1NGhZGc8eiaA:-NZZzgYZ7lrlO2a1rxCa:b-5e5lsu) ([raw file](https://github.com/CoreumFoundation/crust/blob/96ab660ca670347088f95cd0c97c6b5782be5907/build/golang/go.go#L94)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But how about add them to the same folder or add lib to CI cache as well. 
</blockquote></details>

let's discuss

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`build/golang/go.go` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/243#-NZVIaVR1NGhZGc8eiaA:-NZkeGtE554RnYktva5H:b-a1uywu) ([raw file](https://github.com/CoreumFoundation/crust/blob/96ab660ca670347088f95cd0c97c6b5782be5907/build/golang/go.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss
</blockquote></details>

let's add caching in separate PR

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
