### PR TITLE
Remove build step from CI

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/213#-NViHSh04GsZUV7ZRkq_:-NViHSh04GsZUV7ZRkqa:b-cq84w3) ([raw file](https://github.com/CoreumFoundation/crust/blob/7d10db3224ac7a2bd64c6f6bc46d1f756e0b3574/.github/workflows/ci.yml#L38)):*
> ```YAML
>             linter-cache: false
>             docker-cache: false
>           - ci_step: "build"
> ```

As far as I remeber we wanted to replace it to release build to be sure that it works.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/213#-NViHSh04GsZUV7ZRkq_:-NViICgqE7c7CMvPheB6:b-8zg7j1) ([raw file](https://github.com/CoreumFoundation/crust/blob/7d10db3224ac7a2bd64c6f6bc46d1f756e0b3574/.github/workflows/ci.yml#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As far as I remeber we wanted to replace it to release build to be sure that it works.
</blockquote></details>

Yes, in next step because it will require another config update in our github repos

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/213#-NViHSh04GsZUV7ZRkq_:-NViK92A5Ndkcd7nytkT:bjp08h9) ([raw file](https://github.com/CoreumFoundation/crust/blob/7d10db3224ac7a2bd64c6f6bc46d1f756e0b3574/.github/workflows/ci.yml#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, in next step because it will require another config update in our github repos
</blockquote></details>

So you will remove it in next step as well.

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213#-:-NViLKE4EjitEBESI1lK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
