### PR TITLE
Add messages gas dashboard.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
Maybe we should let Piotr check this. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160#-:-NMnEWQn7fy-U0kEtu6z:b-5mwfan)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
Agree, would be nice

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160#-:-NMo9D_9DZV39KHmS3Xy:b-x5n6i4)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/160#-NMoBhyM55tBIBxSdDxO:-NMoBhyNE4Ngu7tRSNL2:b-6wstvw) (no related file):*
I wasn't able to make it work locally.
I rebuilt both znet & crust & cored before running but still didn't help



___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/160#-NMoBhyM55tBIBxSdDxO:-NMoDt539SSIdfCY2_nN:br0tbs8) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I wasn't able to make it work locally.
I rebuilt both znet & crust & cored before running but still didn't help



</blockquote></details>

if you can show this as a demo will be fine for me

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/160#-NMoBhyM55tBIBxSdDxO:-NN1Wk-y4zIXLqllZIHX:bmezspk) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have you run tests? If there are no transactions the dashboard will be empty.
</blockquote></details>

as you can see on the screenshot there are 6 transactions 
I didn't run tests I created them via CLI

___

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/160#-NMoBhyM55tBIBxSdDxO:-NN1qG3z5QAx9qGNIN50:b-u4be80) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv We don't report the failed transactions, that's probably the reason why it's not visible on your dashboard. Check the result of your transactions.
</blockquote></details>

you are right it was failed tx
My fault it seems to work properly now

___

**Pull request merged**
