### PR TITLE
Modify CI tests to run upgrade and then each test

### PR DESCRIPTION
**Pull request by miladz68**
This change will break down the upgrade test from upgrade->modules->ibc to 2 steps upgrade->modules and upgrade->ibc, which in turn will increase the execution speed as those 2 separate actions will be run in parallel. 

This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/256#-Nal1y5jEVaJwJARha29:-Nal1y5jEVaJwJARha2A:b-rg8dvg) ([raw file](https://github.com/CoreumFoundation/crust/blob/1f82fa7bd8655302725345c77d6750546651c155/.github/workflows/ci.yml#L19)):*
> ```YAML
>           "lint",
>           "test",
>           "integration tests coreum-upgrade & coreum-modules",
> ```

But we still need the IBC and Modules without the upgrade.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/256#-Nal1y5jEVaJwJARha29:-Nal4zHD0dWMpvWYFsWY:b-74h6s) ([raw file](https://github.com/CoreumFoundation/crust/blob/1f82fa7bd8655302725345c77d6750546651c155/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we still need the IBC and Modules without the upgrade.
</blockquote></details>

Buy why would we need them ? let's discuss on the call.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/256#-Nal1y5jEVaJwJARha29:-Nal9xC57YIkkeSja0j_:bio82d8) ([raw file](https://github.com/CoreumFoundation/crust/blob/1f82fa7bd8655302725345c77d6750546651c155/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Buy why would we need them ? let's discuss on the call. 
</blockquote></details>

Ok, let's discuss.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
