### PR TITLE
Crust command to build smart contracts

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTYGEoR24L-sWxeOwvc:b-9gr24l) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
> ```Go
> 	"tidy/faucet":             faucet.Tidy,
> 	"wasm":                    coreum.WASM,
> 	"wasm/bank-send":          coreum.WASMBankSend,
> ```

How about adding `contract` as param instead, otherwise we will have to update crust each time we update/add the test.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTYVFcM6xx5FmUeTcy0:b-lkjohg) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about adding `contract` as param instead, otherwise we will have to update crust each time we update/add the test.
</blockquote></details>

Problem with crust is that it does not accept params. It accepts only a list of actions. It's like Makefile, just written in go.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTY_X6U1qBGALYSx9T5:b-68xaky) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Problem with crust is that it does not accept params. It accepts only a list of actions. It's like Makefile, just written in go.
</blockquote></details>

We can add a flag then. With one or a list of contracts. By default we generate all.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTYegHt2gL1x4FnpSVx:b9smugt) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can add a flag then. With one or a list of contracts. By default we generate all. 
</blockquote></details>

If we want to do it we need to redesign crust completely to be more complex than just make-like tool. For now, all the flags would be global meaning that all the commands have them.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTYgMQW7yc6lbbPyYEE:b-xuvd13) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If we want to do it we need to redesign crust completely to be more complex than just make-like tool. For now, all the flags would be global meaning that all the commands have them.
</blockquote></details>

And BTW, replacing command with the flag would block me/us from using autocompletion in bash

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYp8qn7RPmbImMJXe9:-NTYp8qo2FCLqwsYiodZ:b-tz6a7d) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/coreum/wasm.go#L28)):*
> ```Go
> // WASMBankSend compiles bank-send smart contract.
> func WASMBankSend(ctx context.Context, deps build.DepsFunc) error {
> 	return compileWASMContract(ctx, filepath.Join(repoPath, "integration-tests", "modules", "testdata", "wasm", "bank-send"))
> ```

lets reuse `integration-tests/modules/testdata/wasm` as a reusable variable and reuse it.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTmEcaa2iJ73_Pszn5I:b-vrmzka) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
What if only one contract is updated? Only that one should be committed to the repo. But when compiling all of them, all the *.wasm files are different despite the fact that only the source code of one of them was modified.

> We want to avoid crust being so tightly connected with coreum.

Then let's write new `crust`. At the moment `crust` is Makefile-like tool and Makefiles are always tightly connected to the source code they are used for.
___
*[`build/index.go` line 47 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTZELUl48eMwv784INx:-NTmErHI9WzA6VyI96mo:b-wt9jgl) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

would be nice not specify each contract separately here but have a single command "wasm/*" and depending on the second param build one or another contract 
Not sure if this is supported 

</blockquote></details>

It is not supported
___
*[`build/coreum/wasm.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYp8qn7RPmbImMJXe9:-NTmFRoT1IPCIB_NwpyH:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/coreum/wasm.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree 100%
</blockquote></details>

Done.
___
*[`build/coreum/wasm.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYtEmMBpnT7ZMu3Voa:-NTmJbUA01TbNcFm2m5F:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/coreum/wasm.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

these funcs look like copy-paste
lets define a single func which returns fund to run
Smth like this
```go
func wasmCompileFunc(contractName string) func (ctx context.Context, deps build.DepsFunc) error {
  return func (ctx context.Context, deps build.DepsFunc) error {
    compileWASMContract(ctx, filepath.Join(repoPath, "integration-tests", "modules", "testdata", "wasm", contractName))
  }
}

// Usage:
"wasm/nft":                coreum.wasmCompileFunc("nft"),
```
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTmnBfv0YM0GU2PB1f4:b-xf2pa3) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What if only one contract is updated? Only that one should be committed to the repo. But when compiling all of them, all the *.wasm files are different despite the fact that only the source code of one of them was modified.

> We want to avoid crust being so tightly connected with coreum.

Then let's write new `crust`. At the moment `crust` is Makefile-like tool and Makefiles are always tightly connected to the source code they are used for.
</blockquote></details>

I didn't get the point regarding the flags. We already use them.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTn3crCDTQG0UDoeZsV:b-s7vcmd) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I didn't get the point regarding the flags. We already use them. 
</blockquote></details>

in crust we don't use flags

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTn46ww7xzZ3ZSJK1_3:bnvzfoq) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

in crust we don't use flags
</blockquote></details>

What about the `test-groups` or `profiles` ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTnK-U_EGMUQ4Hze1Ew:b-p1p9ix) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the `test-groups` or `profiles` ?
</blockquote></details>

They are in znet, not crust

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTnatAg5a4Z68ME1ZCB:b1xm0sv) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

They are in znet, not crust
</blockquote></details>

Anyways IMO we should have them here as well.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTncgSGDOuqUG2wOMBz:bqiv8x0) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Anyways IMO we should have them here as well. 
</blockquote></details>

Then we need to redo crust, but not here

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/index.go` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTYGEoR24L-sWxeOwvb:-NTo3BRREHobG8gqLvWV:b-exd5yw) ([raw file](https://github.com/CoreumFoundation/crust/blob/03a0604c822c5eabbb26ea29384f7a7be04679e6/build/index.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Then we need to redo crust, but not here
</blockquote></details>

ok
As we agree on the call, lets keep it like this for now and we will reimplement it in the future
___
*[`build/coreum/wasm.go` line 38 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTo3UuZCUg_VsnKr1Xx:-NTo3UuZCUg_VsnKr1Xy:b-lr03vy) ([raw file](https://github.com/CoreumFoundation/crust/blob/a45f80d9cc66f1b38ee5fbb58cf8d3b256e507e3/build/coreum/wasm.go#L38)):*
> ```Go
> 	actions := make([]build.CommandFunc, 0, len(entries))
> 	for _, e := range entries {
> 		fmt.Println(e.Name())
> ```

minor: do you want to use logger here or remove ?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`build/coreum/wasm.go` line 38 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTo3UuZCUg_VsnKr1Xx:-NTs2tEK4fDKPp7WUJeN:bdmwvt8) ([raw file](https://github.com/CoreumFoundation/crust/blob/a45f80d9cc66f1b38ee5fbb58cf8d3b256e507e3/build/coreum/wasm.go#L38)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: do you want to use logger here or remove ?
</blockquote></details>

leftover, removed

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`build/coreum/wasm.go` line 54 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/192#-NTtNnaI7iDV2GiclRzX:-NTtNnaI7iDV2GiclRzY:b-w557x6) ([raw file](https://github.com/CoreumFoundation/crust/blob/96815b6e82a846490c7d78ce3f5c39c00eab55be/build/coreum/wasm.go#L54)):*
> ```Go
> }
> 
> // CompileSmartContract compiels smart contract.
> ```

minor: is not actually true. It returns func which compiles it

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
