### PR TITLE
Move `znet` main package to location shared in all repos

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

`znet` will be built in each repository. To use the common function to build it, the `main` package is moved to ` build/cmd/znet` and it will be located there in each repo.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/406)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/406#-:-Nz2x46c91OfHg9SsUGw:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
