### PR TITLE
Update gaia, osmosis, hermes to latest version and update corresponding run.sh scripts.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Update gaia, osmosis, hermes to latest version and update corresponding run.sh scripts.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/hermes/config.tmpl` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/402#-NyVf20v7qUJqdVaQvSR:-NyVf20v7qUJqdVaQvSS:b-pgbyf5) ([raw file](https://github.com/CoreumFoundation/crust/blob/92c26a1e58a38036aeb70c752c31b34a91a37436/infra/apps/hermes/config.tmpl#L32)):*
> ```
> [mode.connections]
> 
> # Whether or not to enable the connection workers for handshake completion. [Required]
> ```

I can see that hermes added some new config attributes in v1.8

Shall we update our template to include all new things ?

___
*[`infra/apps/hermes/config.tmpl` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/402#-NyVfEOr5qQt0-Qo1NcU:-NyVfEOr5qQt0-Qo1NcV:bo5nmz0) ([raw file](https://github.com/CoreumFoundation/crust/blob/66e0a14ecac37fe053780b6d814231bd98eb2240/infra/apps/hermes/config.tmpl#L124)):*
> ```
> trust_threshold = { numerator = '1', denominator = '3' }
> address_type = { derivation = 'cosmos' }
> packet_filter = { policy = 'allow', list = [['transfer', '*'], ['wasm*', '*']] }
> ```

so now we just relay everything ?
___
*[`infra/apps/osmosis/run.tmpl` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/402#-NyVfUrmAQ0iPSY6tQ4p:-NyVfUrmAQ0iPSY6tQ4q:b-ivejli) ([raw file](https://github.com/CoreumFoundation/crust/blob/92c26a1e58a38036aeb70c752c31b34a91a37436/infra/apps/osmosis/run.tmpl#L35)):*
> ```
> 
> # use uosmo as default denom
> sed -i "s/\"stake\"/\"uosmo\"/g" $GENESIS_PATH
> ```

is denom it the only difference between osmosis vs gaiad ?

Because if it is then we can just pass it as argument or env into this template

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/hermes/config.tmpl` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/402#-NyVf20v7qUJqdVaQvSR:-NyYmdTX7xrKF6J6IauH:b-t2ej9) ([raw file](https://github.com/CoreumFoundation/crust/blob/92c26a1e58a38036aeb70c752c31b34a91a37436/infra/apps/hermes/config.tmpl#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I can see that hermes added some new config attributes in v1.8

Shall we update our template to include all new things ?

</blockquote></details>

Not all of the chains support `[EIP-1559]` but our config is common for all (actually osmosis only). 
We can check how to use it - [https://docs.evmos.org/protocol/modules/feemarket](https://docs.osmosis.zone/overview/features/eip-1559/)
___
*[`infra/apps/hermes/config.tmpl` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/402#-NyVfEOr5qQt0-Qo1NcU:-NyYmTvn3iHKjmsYe21Z:b2nhswy) ([raw file](https://github.com/CoreumFoundation/crust/blob/66e0a14ecac37fe053780b6d814231bd98eb2240/infra/apps/hermes/config.tmpl#L124)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so now we just relay everything ?
</blockquote></details>

Yes
___
*[`infra/apps/osmosis/run.tmpl` line 35 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/402#-NyVfUrmAQ0iPSY6tQ4p:-NyYn1VHDqnA4bBb7iA9:b-s56ply) ([raw file](https://github.com/CoreumFoundation/crust/blob/92c26a1e58a38036aeb70c752c31b34a91a37436/infra/apps/osmosis/run.tmpl#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is denom it the only difference between osmosis vs gaiad ?

Because if it is then we can just pass it as argument or env into this template
</blockquote></details>

No, the CLI is different as well.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/402)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
