### PR TITLE
Build `bdjuno` in crust

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Waiting for all the dependencies to be downloaded and rebuilt by `docker build` each time I want to test modified version of bdjuno devastates my psyche.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/338#-NmKxDmwC5dMa6ukCokQ:-NmKxDmwC5dMa6ukCokR:b-ex8vs3) (no related file):*
This PR outdates https://reviewable.io/reviews/CoreumFoundation/crust/332

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/338#-NmKxGWb8pEF_wGDViBD:-NmKxGWb8pEF_wGDViBE:b2c4vt) (no related file):*
@ysv to make it fully work, branch `chains/coreum` in bdjuno repo should be set to default one

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/338#-NnFWnYHCupjGZ_P8VUf:-NnFWnYI6OBBOGXwFopu:b-vcxiz2) (no related file):*
Lets discuss on call, if we really need this

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/338#-NnFWnYHCupjGZ_P8VUf:-NoX51-6AHVSVALu6IZP:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets discuss on call, if we really need this
</blockquote></details>

Done.

___

**Review by ysv — APPROVED** [review]
> Reviewed 15 of 17 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/338#-:-NojmKpUAdXkzqISjfvY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
