### PR TITLE
Add TestFuzz go function to run fuzz tests.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add TestFuzz go function to run fuzz tests.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/421)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/421)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 668 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/421#-O1Vy-K59-EKsF5_l1vq:-O1Vy-K59-EKsF5_l1vr:b5vf9b5) ([raw file](https://github.com/CoreumFoundation/crust/blob/3c4efe4790cd243cf849551efa05997308ccf66e/build/golang/go.go#L668)):*
> ```Go
> 			line := scanner.Text()
> 			if strings.HasPrefix(line, fuzzFuncPrefix) {
> 				lines := strings.Split(strings.TrimLeft(line, funcPrefix), "(")
> ```

Here, `strings.TrimLeft` does not do what you want. It will trim each characters defined in `funcPrefix` instead of trimming the whole thing, so of a function is defined as `func fcfccnnabc()` it will extract `abc` as test name.

You can test it yourself:
```
const (
	funcPrefix     = "func "
	fuzzFuncPrefix = funcPrefix + "Fuzz"
)

func TestPrefix(t *testing.T) {
	line := "func fcfccnnabc("
	if strings.HasPrefix(line, fuzzFuncPrefix) {
		lines := strings.Split(strings.TrimLeft(line, funcPrefix), "(")
		if len(lines) != 2 {
			t.Fatalf("invalid fuzz test %s", line)
		}
		t.Logf("test name: %s", lines[0])
	}

	t.Log(strings.TrimLeft("func fabc", "func "))
}
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/421)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 668 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/421#-O1Vy-K59-EKsF5_l1vq:-O1WNFd69g55vtYnFV1n:bcppo66) ([raw file](https://github.com/CoreumFoundation/crust/blob/3c4efe4790cd243cf849551efa05997308ccf66e/build/golang/go.go#L668)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Here, `strings.TrimLeft` does not do what you want. It will trim each characters defined in `funcPrefix` instead of trimming the whole thing, so of a function is defined as `func fcfccnnabc()` it will extract `abc` as test name.

You can test it yourself:
```
const (
	funcPrefix     = "func "
	fuzzFuncPrefix = funcPrefix + "Fuzz"
)

func TestPrefix(t *testing.T) {
	line := "func fcfccnnabc("
	if strings.HasPrefix(line, fuzzFuncPrefix) {
		lines := strings.Split(strings.TrimLeft(line, funcPrefix), "(")
		if len(lines) != 2 {
			t.Fatalf("invalid fuzz test %s", line)
		}
		t.Logf("test name: %s", lines[0])
	}

	t.Log(strings.TrimLeft("func fabc", "func "))
}
```
</blockquote></details>

Right, updated.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/421)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/421)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
