### PR TITLE
Fix building `cored` from dirty repository

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/108)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/108)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/golang/lint.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/crust/108#-ND8V03PBcKckS-lfZgq:-ND8V03PBcKckS-lfZgr:b-e9nkp3) ([raw file](https://github.com/coreumfoundation/crust/blob/0e9a48303cc94950dc3cd676915bae914a19b99f/build/golang/lint.go#L46)):*
> ```Go
> 	}
> 	if !isClean {
> 		fmt.Println("git status:")
> ```

clean this ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/108)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/golang/lint.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/crust/108#-ND8V03PBcKckS-lfZgq:-ND8W7FH8zCZZRzWO8KA:b-yh1oq3) ([raw file](https://github.com/coreumfoundation/crust/blob/0e9a48303cc94950dc3cd676915bae914a19b99f/build/golang/lint.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

clean this ?
</blockquote></details>

No, it is intentionally printed, just moved it to different place. If during linting `crust` discovers that some changes are not committed (usually go.mod) it lists the dirty files

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/108)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

___
*[`build/golang/lint.go` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/crust/108#-ND8V03PBcKckS-lfZgq:-NDCocYb4GEh_wg_945u:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/ea79ac363b44741e69daeff709a3330020ec5bab/build/golang/lint.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, it is intentionally printed, just moved it to different place. If during linting `crust` discovers that some changes are not committed (usually go.mod) it lists the dirty files
</blockquote></details>

ok

**Pull request merged**
