### PR TITLE
Install `cored v2.0.0`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
introducing into crust and removing it after testnet upgrade seems like unnecessary stuff. just a local test that it works should be enough. 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254#-:-NaM1axoBTPwHar6jDqy:b1o05js)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
But we decided to add integration test for v2.0.0 -> v2.0.1 upgrade. And for this I need v2.0.0 binary to be there.
Later on we will replace v2.0.0 with v2.0.1 to be able to write upgrade tests for v3.0.0

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254#-:-NaM3bs3Aa60RHFjnZtO:b-5dvodm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
