### PR TITLE
devnet predefined validators mnemonic for the staking testing

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/apps.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzDxcY4UP1jwJQzJcQ:-NCzDxcZB1XIlEOo-u8q:b-wpkg4u) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/apps.go#L99)):*
> ```Go
> 			},
> 			IsValidator:       i < len(validatorMnemonics),
> 			ValidatorMnemonic: validatorMnemonics[i],
> ```

This will panic for sentry node
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEChK14ccabskLU_n:-NCzEChL3MbdrvDcOmo0:bk6fm16) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/cored.go#L44)):*
> ```Go
> 	Ports             Ports
> 	IsValidator       bool
> 	ValidatorMnemonic string
> ```

Maybe `StakerMenmonic`?
___
*[`infra/apps/cored/wallets.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEH771uhXuBD81Cjt:-NCzEH771uhXuBD81Cju:bk9hk6) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/wallets.go#L8)):*
> ```Go
> 	BobMnemonic        = "move equip digital assault wrong speed border multiply knife steel trash donor isolate remember lucky moon cupboard achieve canyon smooth pulp chief hold symptom"
> 	CharlieMnemonic    = "announce already cherry rotate pull apology banana dignity region horse aspect august country exit connect unit agent curious violin tide town link unable whip"
> 	Validator1Mnemonic = "biology rigid design broccoli adult hood modify tissue swallow arctic option improve quiz cliff inject soup ozone suffer fantasy layer negative eagle leader priority"
> ```

Validator*Mnemonic -> Staker*Mnemonic
___
*[`infra/testing/run.go` line 98 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEn831nMJvnn0xwM5:-NCzEn831nMJvnn0xwM6:b4fm5kt) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/testing/run.go#L98)):*
> ```Go
> 				"-funding-mnemonic", FundingMnemonic,
> 			)
> 			for _, mnemonics := range stakerMnemonics {
> ```

mnemonics -> mnemonic
___
*[`pkg/znet/mode.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzExAm-38MuVm-RoRj:-NCzExAm-38MuVm-RoRk:b-acpawc) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/pkg/znet/mode.go#L67)):*
> ```Go
> 	node, coredNodes, err := appF.CoredNetwork(
> 		"coretest",
> 		[]string{
> ```

I would still prefer to pass number here and reference mnemonics internally. Here, as auser I want to provide just the number of validators I need, I don't care about where private keys come from

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEChK14ccabskLU_n:-NCzs7Oo9OMXCJkmlLIf:bh56s5l) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/cored.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe `StakerMenmonic`?
</blockquote></details>

Agree with Wojtek
___
*[`pkg/znet/mode.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzExAm-38MuVm-RoRj:-NCzsN3s9mIZJyLzBwCJ:btb2vcf) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/pkg/znet/mode.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would still prefer to pass number here and reference mnemonics internally. Here, as auser I want to provide just the number of validators I need, I don't care about where private keys come from
</blockquote></details>

I agree with Wojtek. Is there a specific reason we pass them on this step ?
Because the idea was to keep this part simple so we can easily change number here and have more/less validators running when needed

Maybe we can have first 3+ pre-generated & known and if network requires more validators then others we generate randomly ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/apps.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzDxcY4UP1jwJQzJcQ:-ND1urpd9iOX_4QujQcd:b-8ezbo2) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/apps.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This will panic for sentry node
</blockquote></details>

Agree, updated.
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEChK14ccabskLU_n:-ND1uuoC1iCtfH82-DpS:b-bmmixv) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/cored.go#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Agree with Wojtek
</blockquote></details>

This is the validator mnemonic, and will be used for the validator keys generations, and operator address as well.
IMHO the staker here is to abstract to understand the code. 
___
*[`infra/apps/cored/wallets.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEH771uhXuBD81Cjt:-ND1v16_--Me9qGxcl4Y:b-otilcs) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/wallets.go#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Validator*Mnemonic -> Staker*Mnemonic
</blockquote></details>

See comment above.
___
*[`infra/testing/run.go` line 98 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEn831nMJvnn0xwM5:-ND1v8f2Et-qt5hZvh59:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/testing/run.go#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

mnemonics -> mnemonic
</blockquote></details>

Done.



_Code quote:_
```Go
mnemonics := range stakerMnemonics {
```
___
*[`pkg/znet/mode.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzExAm-38MuVm-RoRj:-ND1sS9I2Urg0PC2UsZz:b-dsbusk) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/pkg/znet/mode.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Wojtek. Is there a specific reason we pass them on this step ?
Because the idea was to keep this part simple so we can easily change number here and have more/less validators running when needed

Maybe we can have first 3+ pre-generated & known and if network requires more validators then others we generate randomly ?
</blockquote></details>

It easier to work with the tests or zero chain if the stakers/validators are predefined, that's why we don't generate them. If you want to provide the number then you should be ready to any number, here we say that you should provide the list of mnemonics because it has started beeng matters, and the "Validator" prefix is important as well, since it should that we will take the mnemonics to create the validators. 
So the number here doesn't work as for me. In case you want more then, just generate more mnemonics.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/apps.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzDxcY4UP1jwJQzJcQ:-ND22cqP-S5kJm0aEg5c:b-x176x2) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/apps.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, updated.
</blockquote></details>

I love the solution, but I guess @ysv will be against it :D
___
*[`infra/apps/apps.go` line 98 at r3](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND22rax7vGPqqCX-909:-ND22ray9xOyKYKa_wqH:b-wdez3j) ([raw file](https://github.com/coreumfoundation/crust/blob/f58a2752da205f7f5cd05f711835c957627d54fa/infra/apps/apps.go#L98)):*
> ```Go
> 				Prometheus: cored.DefaultPorts.Prometheus + portDelta,
> 			},
> 			IsValidator: i < len(validatorMnemonics),
> ```

Minor: looks like `IsValidator` might not be needed because `ValidatorMnemonic == ""` may do the job as well
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEChK14ccabskLU_n:-ND23SttEhjpdEv1dPlf:b-mh59f7) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/cored.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is the validator mnemonic, and will be used for the validator keys generations, and operator address as well.
IMHO the staker here is to abstract to understand the code. 
</blockquote></details>

I don't get it. The process is like this:
- you generate staker's wallet
- you start a validator with different key (still might be random, because we don't care)
- staker stakes the funds to validator
- and later, staker is able to vote

Validator and Staker are two different entities, and here you use mnemonics to generate staking accounts
___
*[`pkg/znet/mode.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzExAm-38MuVm-RoRj:-ND23EVn336QClb0MPGU:bcvyj2w) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/pkg/znet/mode.go#L67)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It easier to work with the tests or zero chain if the stakers/validators are predefined, that's why we don't generate them. If you want to provide the number then you should be ready to any number, here we say that you should provide the list of mnemonics because it has started beeng matters, and the "Validator" prefix is important as well, since it should that we will take the mnemonics to create the validators. 
So the number here doesn't work as for me. In case you want more then, just generate more mnemonics. 
</blockquote></details>

Two recommendations:
- generate 10 mnemonics for validators
- still accept only a  number here
- if number is too big, return an error

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 66 at r4](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND2MSZ13dtE7tFZp3lA:-ND2MSZ3AgUSRlWrU8Cq:b5l6h7q) ([raw file](https://github.com/coreumfoundation/crust/blob/c3ac1b03209ddf2698a20bf28c4311594fcc4826/infra/apps/cored/cored.go#L66)):*
> ```Go
> 		stake := "100000000" + cfg.Network.TokenSymbol()
> 		// the additional balance will be used to pay for the tx submitted from the validators accounts
> 		fullBalance := "100010000" + cfg.Network.TokenSymbol()
> ```

I would prefer to have it in an explicit form of `stake + additional`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/apps.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzDxcY4UP1jwJQzJcQ:-ND2uOREEY_IMTqDBOB5:b2nh4j5) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/apps.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I love the solution, but I guess @ysv will be against it :D
</blockquote></details>

:-)
___
*[`infra/apps/apps.go` line 98 at r3](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND22rax7vGPqqCX-909:-ND2uG_i0iDEvVyubr5V:b-lurrhc) ([raw file](https://github.com/coreumfoundation/crust/blob/f58a2752da205f7f5cd05f711835c957627d54fa/infra/apps/apps.go#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: looks like `IsValidator` might not be needed because `ValidatorMnemonic == ""` may do the job as well
</blockquote></details>

Now we have 2 flags IsValidator and StakerMnemonic. I would keep them different, since the IsValidator is about the node and staker about delegation.
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEChK14ccabskLU_n:-ND2uTFp83dI9M97yyRT:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/cored.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't get it. The process is like this:
- you generate staker's wallet
- you start a validator with different key (still might be random, because we don't care)
- staker stakes the funds to validator
- and later, staker is able to vote

Validator and Staker are two different entities, and here you use mnemonics to generate staking accounts
</blockquote></details>

Updated.
___
*[`infra/apps/cored/cored.go` line 66 at r4](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND2MSZ13dtE7tFZp3lA:-ND2vPtQ1vdXfbVrF_Zq:b-cypxrc) ([raw file](https://github.com/coreumfoundation/crust/blob/c3ac1b03209ddf2698a20bf28c4311594fcc4826/infra/apps/cored/cored.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would prefer to have it in an explicit form of `stake + additional`
</blockquote></details>

updated.
___
*[`infra/apps/cored/wallets.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzEH771uhXuBD81Cjt:-ND2udcc8LAEUoun2Y2v:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/cored/wallets.go#L8)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Updated.



_Code quote (from infra/apps/cored/cored.go):_
```Go
dditional balance will be used to pay for the tx s
```
___
*[`pkg/znet/mode.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzExAm-38MuVm-RoRj:-ND2u9nyCaH9A0MHe17G:b-tjvwa9) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/pkg/znet/mode.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Two recommendations:
- generate 10 mnemonics for validators
- still accept only a  number here
- if number is too big, return an error
</blockquote></details>

Now we have 32 stakers

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/apps.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/103#-NCzDxcY4UP1jwJQzJcQ:-ND303Y33zswS4699ioq:b-mo5qkx) ([raw file](https://github.com/coreumfoundation/crust/blob/3020e8d35ee0570a8dd54b6fe47d66a6655b06f6/infra/apps/apps.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

:-)
</blockquote></details>

I'm ok to keep it

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/wallets.go` line 8 at r5](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND3NKxzA_eU2y0lQnf4:-ND3O8fK9Fu5p-Rlq70B:brv5ztq) ([raw file](https://github.com/coreumfoundation/crust/blob/a34cd6100901df048df276e75aab6c2237800d57/infra/apps/cored/wallets.go#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you ever plan to access these mnemonics directly by name? If not, just put them in the slice directly
</blockquote></details>

Ok,  updated.
___
*[`infra/testing/run.go` line 37 at r5](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND3N_HO5QuvQSInEirw:-ND6vb6w1USXnNKuPmCI:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/a34cd6100901df048df276e75aab6c2237800d57/infra/testing/run.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you should count the number of deployed validators. Because someone may want to update the number when network is created (in the argument of `CoredNetwork` call)
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`infra/apps/cored/cored.go` line 132 at r6](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND7PTZgDGaAfjkbohL2:-ND815zt3LDuMUxeEPtd:b-dqun5u) ([raw file](https://github.com/coreumfoundation/crust/blob/ad038f3b915aa71c1579f565440d64d86fbba063/infra/apps/cored/cored.go#L132)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why not all config? It seems to me more logical. 
</blockquote></details>

Okay, but then remove all the methods which might be now satisfied by `Config()`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 132 at r6](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND7PTZgDGaAfjkbohL2:-ND87gZ6DFpzdr_HPqdO:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/ad038f3b915aa71c1579f565440d64d86fbba063/infra/apps/cored/cored.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Okay, but then remove all the methods which might be now satisfied by `Config()`
</blockquote></details>

Done.



_Code quote:_
```Go
func (c Cored) Config() Config {
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`.gitignore` line 3 at r9](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8FbP-80Sc5FUBXBaY:-ND8FbP-80Sc5FUBXBaZ:b-kdpyut) ([raw file](https://github.com/coreumfoundation/crust/blob/e4e73738b4934282cef57c1843a7e7d340fb52c3/.gitignore#L3)):*
> ```ignore
> .idea
> .vscode
> /bin
> ```

it shouldn't be removed
___
*[`.gitignore` line 4 at r9](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8FeRK4RnmFwAOEk8n:-ND8FeRK4RnmFwAOEk8o:b-kyqon5) ([raw file](https://github.com/coreumfoundation/crust/blob/731f8983ee644230e2fa963e83204040b08aae8a/.gitignore#L4)):*
> ```ignore
> .vscode
> vendor
> *.iml
> ```

new line missing

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`infra/apps/cored/wallets.go` line 11 at r10](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8MZXd-o0GkoVb1mgO:-ND8MZXeEvCN5P_C14MZ:bdbqd5j) ([raw file](https://github.com/coreumfoundation/crust/blob/e6abf04ba25faaa3df11d6c75c29e920df8cb00d/infra/apps/cored/wallets.go#L11)):*
> ```Go
> 
> var (
> 	// StakerMnemonics defines the list of the staked used by validators.
> ```

staked -> stakes

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`infra/apps/cored/wallets.go` line 11 at r10](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8MZXd-o0GkoVb1mgO:-ND8MgV5EX-exbOzs_57:bteck93) ([raw file](https://github.com/coreumfoundation/crust/blob/e6abf04ba25faaa3df11d6c75c29e920df8cb00d/infra/apps/cored/wallets.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

staked -> stakes
</blockquote></details>

or whatever you meant :)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 6 files at r8, 2 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`.gitignore` line 3 at r9](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8FbP-80Sc5FUBXBaY:-ND8Vjti5QQnSF2OSRyM:b-bvwhm5) ([raw file](https://github.com/coreumfoundation/crust/blob/e4e73738b4934282cef57c1843a7e7d340fb52c3/.gitignore#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it shouldn't be removed
</blockquote></details>

Restored.
___
*[`.gitignore` line 4 at r9](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8FeRK4RnmFwAOEk8n:-ND8VoMx9aIPQTnTWmTv:b-8b11j9) ([raw file](https://github.com/coreumfoundation/crust/blob/731f8983ee644230e2fa963e83204040b08aae8a/.gitignore#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

new line missing
</blockquote></details>

Added



_Code quote:_
```ignore
vendor
```
___
*[`infra/apps/cored/wallets.go` line 11 at r10](https://reviewable.io/reviews/coreumfoundation/crust/103#-ND8MZXd-o0GkoVb1mgO:-ND8Vu69Ex5A3u-CwgpE:b-bw8e14) ([raw file](https://github.com/coreumfoundation/crust/blob/e6abf04ba25faaa3df11d6c75c29e920df8cb00d/infra/apps/cored/wallets.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

or whatever you meant :)
</blockquote></details>

Updated.



_Code quote:_
```Go
 staked
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
