### PR TITLE
Build smart contracts on host system

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

We decided to remove building smart contracts inside docker to make everything faster.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/327)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
Nice job. Not full rebuild of all contracts on my machine takes 3-5min. Before it was about 30 minutes.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/327#-:-Nlaof2PBlBHQKNYx7wc:b-5l0dxg)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 916 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/327#-NlalZzy6DM3mVLW8Q-K:-NlalZzy6DM3mVLW8Q-L:b9d26cb) ([raw file](https://github.com/CoreumFoundation/crust/blob/cb1fcd19043d259815d0ad7c5067e32fe6e72ca2/build/tools/tools.go#L916)):*
> ```Go
> 			}
> 
> 			must.OK(os.MkdirAll(filepath.Dir(dstPath), 0o700))
> ```

Didn't we want not to use the must.OK ? You func signature includes error, so better to return it. 
___
*[`build/tools/tools.go` line 945 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/327#-NlalmXx9Xgh0Cc-bhRE:-NlalmXx9Xgh0Cc-bhRF:b1dhahn) ([raw file](https://github.com/CoreumFoundation/crust/blob/cb1fcd19043d259815d0ad7c5067e32fe6e72ca2/build/tools/tools.go#L945)):*
> ```Go
> 	toolDir := toolDir(ri, platform)
> 	rustupHome := filepath.Join(toolDir, "rustup")
> 	toolchainsDir := filepath.Join(rustupHome, "toolchains")
> ```

Repeated code with the same constants, here and in the `Ensure`.



_Code quote:_
```Go
	rustupHome := filepath.Join(toolDir, "rustup")
	toolchainsDir := filepath.Join(rustupHome, "toolchains")
```

**Review by wojtek-coreum — COMMENTED** [review]
Thanks. Yes, mostly it's because compiled cache is common to all the smart contracts now. Probably on macos some time is saved on starting docker container for each smart contract, I don't know the impact because on linux it's negligible.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/327#-:-NlbIeJl9V3uuu64g6j5:b-itnbsg)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 916 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/327#-NlalZzy6DM3mVLW8Q-K:-NlbKow2DfVLOewGP75_:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/cb1fcd19043d259815d0ad7c5067e32fe6e72ca2/build/tools/tools.go#L916)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't we want not to use the must.OK ? You func signature includes error, so better to return it.
</blockquote></details>

Done.
___
*[`build/tools/tools.go` line 945 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/327#-NlalmXx9Xgh0Cc-bhRE:-NlbIQtf0tsNsrz2MCLp:b-thqag4) ([raw file](https://github.com/CoreumFoundation/crust/blob/cb1fcd19043d259815d0ad7c5067e32fe6e72ca2/build/tools/tools.go#L945)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Repeated code with the same constants, here and in the `Ensure`.
</blockquote></details>

yes, I could pass the directory as an argument but I chose to keep the function header as simple as possible

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/327)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/327)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
