### PR TITLE
Add IBC monitoring and alerting.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/217)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/217)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/apps.go` line 209 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/217#-NWMkLqYDIwA3FxDDFJS:-NWMkLqYDIwA3FxDDFJT:bd2b3hy) ([raw file](https://github.com/CoreumFoundation/crust/blob/3352f938a011f189e628dad5002b5b8799d22ba2/infra/apps/apps.go#L209)):*
> ```Go
> 		HomeDir:               filepath.Join(f.config.AppDir, nameRelayerCosmosOsmosis),
> 		AppInfo:               f.spec.DescribeApp(relayercosmos.AppType, nameRelayerCosmosOsmosis),
> 		DebugPort:             relayercosmos.DefaultDebugPort,
> ```

Change it to `TelemtryPort` too

**Review by miladz68 — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/217)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/217)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/217)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/apps.go` line 209 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/217#-NWMkLqYDIwA3FxDDFJS:-NWMw6Tn4qPUVLN3-k85:b-7xm5t4) ([raw file](https://github.com/CoreumFoundation/crust/blob/3352f938a011f189e628dad5002b5b8799d22ba2/infra/apps/apps.go#L209)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Change it to `TelemtryPort` too
</blockquote></details>

Actualy I left it intentionaly. On the `Hermes` it's called `TelemtryPort`, but in the `cosmos relayer` this port is responsible for the API and Telemetry, that's why it's called the `DebugPort`, so the name is correct.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
