### PR TITLE
Add function to roll back uncommitted changes

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

It is required to compile cored with CometBFT replaced.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/404)

### CODE REVIEW

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/404)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/404)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`build/git/git.go` line 140 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/404#-Ny_4f3E3QkmoSvaZb8E:-Ny_4f3E3QkmoSvaZb8F:bp47ihc) ([raw file](https://github.com/CoreumFoundation/crust/blob/4f3dcf2234b3db79f1d024e2c793c26a3f37ca18/build/git/git.go#L140)):*
> ```Go
> 
> // RollbackChanges rolls back uncommitted changes made to the specified files.
> func RollbackChanges(ctx context.Context, repoPath string, files ...string) error {
> ```

what if we use `-modfile` go build flag to achieve build with replaced go dependency ?

```
-modfile file
		in module aware mode, read (and possibly write) an alternate go.mod
		file instead of the one in the module root directory. A file named
		"go.mod" must still be present in order to determine the module root
		directory, but it is not accessed. When -modfile is specified, an
		alternate go.sum file is also used: its path is derived from the
		-modfile flag by trimming the ".mod" extension and appending ".sum".
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/404)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/git/git.go` line 140 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/404#-Ny_4f3E3QkmoSvaZb8E:-NydZN0C4eh-DTmf_5oI:bkflzx0) ([raw file](https://github.com/CoreumFoundation/crust/blob/4f3dcf2234b3db79f1d024e2c793c26a3f37ca18/build/git/git.go#L140)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what if we use `-modfile` go build flag to achieve build with replaced go dependency ?

```
-modfile file
		in module aware mode, read (and possibly write) an alternate go.mod
		file instead of the one in the module root directory. A file named
		"go.mod" must still be present in order to determine the module root
		directory, but it is not accessed. When -modfile is specified, an
		alternate go.sum file is also used: its path is derived from the
		-modfile flag by trimming the ".mod" extension and appending ".sum".
```
</blockquote></details>

`go: -modfile cannot be used in workspace mode`

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/404)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/404)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)

**Pull request merged**
