### PR TITLE
Upgrade tools

### PR DESCRIPTION
**Pull request by wojtek-coreum**
go 1.19.3
ignite 0.23.0 - downgraded to the latest version using cosmos sdk v0.45.x
gaia 7.1.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/crust/139#-NHYnhD86QWqYIc_Xxa5:-NHYnhD86QWqYIc_Xxa6:br47hl9) ([raw file](https://github.com/coreumfoundation/crust/blob/1dd6aa2761b023fdcd43be1ef4d45a93285be7b1/build/tools/tools.go#L92)):*
> ```Go
> 	// https://github.com/ignite/cli/releases/
> 	Ignite: {
> 		Version:  "0.25.2",
> ```

What is the SDK version is used there? If SDK v0.46+ I would event decrease it, since now after the proto generation it updates the version to v0.46.
___
*[`build/tools/tools.go` line 160 at r1](https://reviewable.io/reviews/coreumfoundation/crust/139#-NHYnsRtBRJgRxTKX_5K:-NHYnsRtBRJgRxTKX_5L:b-9sb28p) ([raw file](https://github.com/coreumfoundation/crust/blob/1dd6aa2761b023fdcd43be1ef4d45a93285be7b1/build/tools/tools.go#L160)):*
> ```Go
> 	// https://github.com/cosmos/gaia/releases
> 	Gaia: {
> 		Version:   "v7.1.0",
> ```

What is the IBC version used in the "v7.1.0" still v3 ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/crust/139#-NHYnhD86QWqYIc_Xxa5:-NHcsswTEOMq0ZoZVN-y:b2qfmum) ([raw file](https://github.com/coreumfoundation/crust/blob/1dd6aa2761b023fdcd43be1ef4d45a93285be7b1/build/tools/tools.go#L92)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the SDK version is used there? If SDK v0.46+ I would event decrease it, since now after the proto generation it updates the version to v0.46.
</blockquote></details>

Done. Downgraded to 0.23.0
___
*[`build/tools/tools.go` line 160 at r1](https://reviewable.io/reviews/coreumfoundation/crust/139#-NHYnsRtBRJgRxTKX_5K:-NHctJQv1uXRWughz9fm:b2nign6) ([raw file](https://github.com/coreumfoundation/crust/blob/1dd6aa2761b023fdcd43be1ef4d45a93285be7b1/build/tools/tools.go#L160)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the IBC version used in the "v7.1.0" still v3 ?
</blockquote></details>

yes

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
