### PR TITLE
Only project-related files are ignored by `.gitignore`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/42#-N8gmYqsA2ms-FebxntH:-N8gmYqsA2ms-FebxntI:bfz2wy7) (no related file):*
I think this is very trivial issue. I have seen .gitignore files with hundreds of lines tailored for different OSes and editors, without causing any problems and everyone was happy. 
But I don't have an issue with it since it does not affect me in anyway as I don't have an editor config in project root. So I give my approval.

___
___
*[`.gitignore` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/42#-N8gnRi33S3XQxWmILhB:-N8gnRi33S3XQxWmILhC:bj5nzhx) ([raw file](https://github.com/coreumfoundation/crust/blob/3996995dc76563387aca182ebac3cadf316536d1/.gitignore#L1)):*
> ```ignore
> # Don't put files or directories specific to your operating system or development environment here.
> ```

Add please to the start of the sentence to be more polite :smile: .

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

**Review by miladz68 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42#-:-N8go1wg9gWJ7M_lvjGy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/42#-N8gmYqsA2ms-FebxntH:-N8gqhmxBqb5nTZDzuA8:b-mx3768) (no related file):*
> I have seen .gitignore files with hundreds of lines

And probably no one understood if those lines are needed or what they are related to, tolerating them just because nobody wanted to take the effort of cleaning them. The preferred approach is to not create that garbage in the first place IMO.

___
___
*[`.gitignore` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/crust/42#-N8gnRi33S3XQxWmILhB:-N8gqYRfCBjtI9wKabUk:b-c54bqx) ([raw file](https://github.com/coreumfoundation/crust/blob/3996995dc76563387aca182ebac3cadf316536d1/.gitignore#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Add please to the start of the sentence to be more polite :smile: .
</blockquote></details>

:D :D done

**Review by begmaroman — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Pull request merged**
