### PR TITLE
Command for generating deterministic gas spec

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/generate.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYHF6K7noj8NqY-1dj:-NTYHF6K7noj8NqY-1dk:b-r91wny) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/coreum/generate.go#L19)):*
> ```Go
> // GenerateDeterministicGasSpec regenerates spec of deterministic gas.
> func GenerateDeterministicGasSpec(ctx context.Context, deps build.DepsFunc) error {
> 	return golang.Generate(ctx, filepath.Join(repoPath, "x", "deterministicgas", "spec"), deps)
> ```

I would do the generation for all files, not just the doc. In that case we won't have to update the crust later, once we have  more code-generation functions.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/generate.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYHF6K7noj8NqY-1dj:-NTYUzD3DLF6v5egeVAy:b-hgjfj9) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/coreum/generate.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would do the generation for all files, not just the doc. In that case we won't have to update the crust later, once we have  more code-generation functions.
</blockquote></details>

On the other hand, if you modify the doc, you don't want to regenerate other parts

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/generate.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYHF6K7noj8NqY-1dj:-NTY_E-FEiTmHQrgUaQx:b-73yz9v) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/coreum/generate.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

On the other hand, if you modify the doc, you don't want to regenerate other parts
</blockquote></details>

But what is the use case when you don't need to generate other? The only case I see is that you forgot to do it. In that case the general generate will show it.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/generate.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYHF6K7noj8NqY-1dj:-NTYeHj607VB7Pzv615J:b-45zxz0) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/coreum/generate.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But what is the use case when you don't need to generate other? The only case I see is that you forgot to do it. In that case the general generate will show it. 
</blockquote></details>

If you modify docs, you want to commit only docs. But if everything is generated it might happen that content is slightly different (e.g. wasm contracts are different even if source code stays the same), leading to misleading commits or necessity for reverting unrelated files.

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`build/coreum/generate.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYHF6K7noj8NqY-1dj:-NTYpR-A1UJYWTuPCR4w:bavu9k9) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/coreum/generate.go#L19)):*
I agree with Dzmitry. IMO we should generate everything but not a specific file.
Generation should be deterministic so this should not happen.

Also the command should be universal. We don't want to modify crust for each new go generator file inside coreum because It is inconvenient.

IMO we should run go generate for the whole coreum repo for now.


> e.g. wasm contracts are different even if source code stays the same

It is not a case because we will not generate them. They should be compiled which is different command



In the future if this generation becomes complex we might split into into multiple parts but for now lets keep it simple and do everything under a single command
___
*[`build/golang/go.go` line 252 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYqU5sCNC0hLqCw1KQ:-NTYqU5sCNC0hLqCw1KR:b-12aubu) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/golang/go.go#L252)):*
> ```Go
> 
> // Generate calls `go generate` for specific package.
> func Generate(ctx context.Context, path string, deps build.DepsFunc) error {
> ```

we should run this command in CI before checking if git status is clean

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/generate.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYHF6K7noj8NqY-1dj:-NTmES4B5SyJIE961QF_:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/coreum/generate.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Dzmitry. IMO we should generate everything but not a specific file.
Generation should be deterministic so this should not happen.

Also the command should be universal. We don't want to modify crust for each new go generator file inside coreum because It is inconvenient.

IMO we should run go generate for the whole coreum repo for now.


> e.g. wasm contracts are different even if source code stays the same

It is not a case because we will not generate them. They should be compiled which is different command



In the future if this generation becomes complex we might split into into multiple parts but for now lets keep it simple and do everything under a single command
</blockquote></details>

Done.
___
*[`build/golang/go.go` line 252 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/191#-NTYqU5sCNC0hLqCw1KQ:-NTmEQxDE08_vSzsMjsc:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/2969fb25d32a0a608f5c7f845f70bc6e4c56e4cb/build/golang/go.go#L252)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we should run this command in CI before checking if git status is clean
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
