### PR TITLE
Bump up coreum version to support new chain/network configuration with SDK types

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`go.mod` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/crust/132#-NFIMEkQAunSU7sbiwYE:-NFIMEkR1QkCVzRDR6xn:b62ihz0) ([raw file](https://github.com/coreumfoundation/crust/blob/fdc0531dc327510eeabf04a533214f61d0af69e2/go.mod#L11)):*
> ```XML
> 
> require (
> 	github.com/CoreumFoundation/coreum v0.0.0-20221024110009-64ad8b391783
> ```

Blocking until it's in master

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/crust/132#-NFIMEkQAunSU7sbiwYE:-NFN7W027q0kspTcv73D:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/fdc0531dc327510eeabf04a533214f61d0af69e2/go.mod#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Blocking until it's in master
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
