### PR TITLE
Added support for genesis creation via cored CLI

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR allows crust to generate genesis by interacting with the cored CLI, instead of import template files. We still need to support templates files since earlier versions (v3 and before) depend on it, and we can drop the legacy method after we drop the support to cored v3 binary.
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/cored/cored.go` line 556 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/326#-NlXDOecB4pzcxX_wd3H:-NlXDOed-HdSzFVWE4b8:b-5trkjw) ([raw file](https://github.com/CoreumFoundation/crust/blob/afb7149665126136c5a5f428ed911dcd59ae641f/infra/apps/cored/cored.go#L556)):*
> ```Go
> 		return errors.Wrap(err, "unable to make config directory")
> 	}
> 	tempFile, err := os.CreateTemp("", "*.json")
> ```

maybe store it in the config dir next to genesis.json, just in case we want to debug sth. And don't remove it.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`infra/apps/cored/cored.go` line 170 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/326#-NlXo9nF0EBFWxF5UPKS:-NlXo9nF0EBFWxF5UPKT:b-4bla6k) ([raw file](https://github.com/CoreumFoundation/crust/blob/afb7149665126136c5a5f428ed911dcd59ae641f/infra/apps/cored/cored.go#L170)):*
> ```Go
> 		stake := sdk.NewInt64Coin(cfg.NetworkConfig.Denom(), int64(float64(cfg.StakerBalance)*0.9))
> 
> 		createValidatorTx, err := prepareTxStakingCreateValidator(
> ```

Why do you still need those txs? The genesis generator should generate them for you.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 170 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/326#-NlXo9nF0EBFWxF5UPKS:-Nlbvqcr14ZNdQvdAIXw:b-sslxxk) ([raw file](https://github.com/CoreumFoundation/crust/blob/afb7149665126136c5a5f428ed911dcd59ae641f/infra/apps/cored/cored.go#L170)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you still need those txs? The genesis generator should generate them for you.
</blockquote></details>

we need those tx for v3 version that uses templates.
___
*[`infra/apps/cored/cored.go` line 556 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/326#-NlXDOecB4pzcxX_wd3H:-NlbvxxN7wcNzrZ5X8oR:b-8opwyg) ([raw file](https://github.com/CoreumFoundation/crust/blob/afb7149665126136c5a5f428ed911dcd59ae641f/infra/apps/cored/cored.go#L556)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe store it in the config dir next to genesis.json, just in case we want to debug sth. And don't remove it.
</blockquote></details>

Good point, Done

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/326)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
