### PR TITLE
Include versions in cache ids

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

We observed that over time linter generates invalid output. We suspect that this is due to cache being incompatible with new versions of the binaries. Now we include the version in the cache ID.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/312#-Nk077O64uhusCmeV3Dq:-Nk077O64uhusCmeV3Dr:blaoh1a) ([raw file](https://github.com/CoreumFoundation/crust/blob/26a636a4d5dc635dff502adee73bb6a65741a405/.github/workflows/ci.yml#L87)):*
> ```YAML
>             ~/.cache/go-build
>             ~/go/pkg/mod
>           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-1.21.4
> ```

Can we use the CLI for it instead of crust? And what about other repos?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/312#-Nk077O64uhusCmeV3Dq:-Nk0I8qVB6CFn82hyRhB:bwb581k) ([raw file](https://github.com/CoreumFoundation/crust/blob/26a636a4d5dc635dff502adee73bb6a65741a405/.github/workflows/ci.yml#L87)):*
> Can we use the CLI for it instead of crust?

WDYM?

> And what about other repos?

Once we discuss I will do the same for others

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/312#-Nk077O64uhusCmeV3Dq:-Nk0UH8b8Qpp6tD1Xhaq:b6p579f) ([raw file](https://github.com/CoreumFoundation/crust/blob/26a636a4d5dc635dff502adee73bb6a65741a405/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> Can we use the CLI for it instead of crust?

WDYM?

> And what about other repos?

Once we discuss I will do the same for others
</blockquote></details>

I mean call `go version`

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/312#-Nk077O64uhusCmeV3Dq:-Nk0VhqsEoOSiUUDeRvK:b-j56ga3) ([raw file](https://github.com/CoreumFoundation/crust/blob/26a636a4d5dc635dff502adee73bb6a65741a405/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean call `go version`
</blockquote></details>

Then we would move toward bashing

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/312#-Nk077O64uhusCmeV3Dq:-NkF33H0CLu09o8FGpvR:b-rwz4n5) ([raw file](https://github.com/CoreumFoundation/crust/blob/26a636a4d5dc635dff502adee73bb6a65741a405/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Then we would move toward bashing
</blockquote></details>

IMO better to go toward direction which is easier to support. IMO the regeneration of the github CI by template is mach harder. Also we already use the `bashing` in the templates.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/312)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/312#-NkGS42SD41x8JSTrTmG:-NkGS42SD41x8JSTrTmH:b-vtfrjf) (no related file):*
decided to impl it differently

___

**Pull request closed without merging**
