### PR TITLE
Enable gci linter for better imports grouping

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/54)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/54)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @begmaroman, @wojtek-coreum, and @xlab)

___
*[`build/.golangci.yaml` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/crust/54#-N9HHvrQ66O0XLqSnNd5:-N9HHvrQ66O0XLqSnNd6:b-2epjwq) ([raw file](https://github.com/coreumfoundation/crust/blob/5ded0da61c14e82b439df89874add582cb053c52/build/.golangci.yaml#L77)):*
> ```YAML
>       - standard
>       - default
>       - prefix(github.com/CoreumFoundation)
> ```

since we are using one linter for all projects I now see that 4 import groups are not possible, so this is good.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @xlab)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @xlab)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @xlab)

___
*[`build/.golangci.yaml` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/crust/54#-N9HHvrQ66O0XLqSnNd5:-N9HJ57MB6G1seKDHpCG:b5fidmn) ([raw file](https://github.com/coreumfoundation/crust/blob/5ded0da61c14e82b439df89874add582cb053c52/build/.golangci.yaml#L77)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

since we are using one linter for all projects I now see that 4 import groups are not possible, so this is good.
</blockquote></details>

yeah exactly

anyways it is ok for now an hopefully we can improve this later

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @xlab)

___
*[`build/.golangci.yaml` line 77 at r1](https://reviewable.io/reviews/coreumfoundation/crust/54#-N9HHvrQ66O0XLqSnNd5:-N9HLafA5bKGusLcvQ1b:byjw2r1) ([raw file](https://github.com/coreumfoundation/crust/blob/5ded0da61c14e82b439df89874add582cb053c52/build/.golangci.yaml#L77)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yeah exactly

anyways it is ok for now an hopefully we can improve this later
</blockquote></details>

personally I've never gave it my attention. Previously, I just used two groups only: for standard lib and other stuff

**Pull request merged**
