### PR TITLE
Building integration tests requires building smart contracts

### PR DESCRIPTION
**Pull request by wojtek-coreum**
It is related to #475 in coreum repo

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/coreum/build.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/196#-NUM0YZK-TZfbuZwPT86:-NUM0YZK-TZfbuZwPT87:b-fl03zi) ([raw file](https://github.com/CoreumFoundation/crust/blob/8bae436ec30edf0aad53bac93d2301c4eb2a3b8a/build/coreum/build.go#L87)):*
> ```Go
> // BuildIntegrationTests builds coreum integration tests.
> func BuildIntegrationTests(ctx context.Context, deps build.DepsFunc) error {
> 	deps(golang.EnsureGo, ensureRepo, CompileAllSmartContracts)
> ```

does it always rebuild smart contracts ?
or only if there are changes ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/build.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/196#-NUM0YZK-TZfbuZwPT86:-NUM9sZhCetHPdfPn3z5:b846526) ([raw file](https://github.com/CoreumFoundation/crust/blob/8bae436ec30edf0aad53bac93d2301c4eb2a3b8a/build/coreum/build.go#L87)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it always rebuild smart contracts ?
or only if there are changes ?
</blockquote></details>

Always but if there are no changes it takes couple of seconds. But now I see that binary files will be different anyway. But how to verify that files has been changed or not?

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`build/coreum/build.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/196#-NUM0YZK-TZfbuZwPT86:-NURBtoo5e-XrAjgwBx0:bcmygur) ([raw file](https://github.com/CoreumFoundation/crust/blob/1ceafe6bf8d07f1c895f803e4c4bb4868da53e31/build/coreum/build.go#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Always but if there are no changes it takes couple of seconds. But now I see that binary files will be different anyway. But how to verify that files has been changed or not?
</blockquote></details>

I see
IDK if we can somehow detect it. The only way I see is to use hash of WASM folder content in built artifact name. Smth similar to crust `crust-fc0ac9f` but there we use commit hash but here we should use hash of a specific WASM folder

On the other hand if it really takes a few seconds to built with cache I'm not sure if this improvement is needed

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

___
*[`build/coreum/build.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/196#-NUM0YZK-TZfbuZwPT86:-NVEUASR9p9Kt2i6pLZR:bdvx416) ([raw file](https://github.com/CoreumFoundation/crust/blob/b31b0c71a303f17754db8d70b5266ea244b34578/build/coreum/build.go#L87)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Resolving it since I will not be available for some time
Still address this comment if reasonable pls
</blockquote></details>

After discussion we found that it doesn't matter that wasm files are different each time because they are no longer part of the repo so they are not committed. Also it takes only a couple of seconds to rebuild them with hot cache. And I need this PR for my next changes so merging it as is. Let's come back to this discussion once you are back.

**Pull request merged**
