### PR TITLE
Access gaiad and osmosisd containers in znet with cli

### PR DESCRIPTION
**Pull request by vertex451**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)

Task:
https://app.clickup.com/t/86853rp4p

### CODE REVIEW

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`infra/cosmoschain/base.go` line 207 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbU4vOZEbfsFJEtacUM:-NbU4vOZEbfsFJEtacUN:b-vn3z45) ([raw file](https://github.com/CoreumFoundation/crust/blob/a7c5579e2ffbca29fb3105347645f40f8693e4ef/infra/cosmoschain/base.go#L207)):*
> ```Go
> }
> 
> func (ba BaseApp) saveClientWrapper(wrapperDir, hostname string) error {
> ```

I will improve this part

**Review by vertex451 — COMMENTED** [review]
```
ibc-gaiad status
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"a3f8eaaaa11a7b3c600b96409f78d6becf4c71ad","listen_addr":"tcp://0.0.0.0:26556","network":"gaia-localnet-1","version":"0.34.29","channels":"40202122233038606100","moniker":"moniker","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:26557"}},"SyncInfo":{"latest_block_hash":"1E10C0E1F7E281CE82D4A44F863B5E49A333AB4BC85F9DAE9943F46B27BB4DA9","latest_app_hash":"21C4A7F3CEEAD5ADA714FEB5EAAF2EA668F39B1D053FE0F0B3EA6D8DCFF1C2BD","latest_block_height":"3","latest_block_time":"2023-08-11T12:29:44.94247426Z","earliest_block_hash":"DD1D41F5B50EAB6C804CFB3E2B828A5F3D465114D293040CA9876151F3B412DF","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2023-08-11T12:29:34.146812339Z","catching_up":false},"ValidatorInfo":{"Address":"AC0872D275BC2A3D39AEAD376C427195E16CEEA2","PubKey":{"type":"tendermint/PubKeyEd25519","value":"xpKtX9kleY/ah1BGWLL6iDh1uSVoIug+Iy65B9IkNWA="},"VotingPower":"100"}}

ibc-osmosis status 
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"7694fc6737d5b94ca9beec67a1410dc21f79948c","listen_addr":"tcp://0.0.0.0:26456","network":"osmosis-localnet-1","version":"0.34.24","channels":"40202122233038606100","moniker":"moniker","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:26457"}},"SyncInfo":{"latest_block_hash":"EB01A4F555C45E4D26376A58BC9E50FDA07220D5466487228845E687D6E68267","latest_app_hash":"4D4710BE7F2C9389E9788FA3C0FF2C8347D1CC886A7F77E0D6495BE8F674957F","latest_block_height":"5","latest_block_time":"2023-08-11T12:29:55.685188543Z","earliest_block_hash":"BF8B1AF1B1174655E5520D12860F0F0127DF32270C7B86CB84ABE5516412F361","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2023-08-11T12:29:34.174652714Z","catching_up":false},"ValidatorInfo":{"Address":"5095ACBD85A2E137DA0CB13EE30EA78F1702995D","PubKey":{"type":"tendermint/PubKeyEd25519","value":"x3rYFw6Ek9aDb1JGDf1mxJnjXlDQrY3zNoMiEpxmANE="},"VotingPower":"100"}}
```

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268#-:-NbZZwAQAMtqGN_EWNwz:bd9tman)* status: 0 of 5 files reviewed, 1 unresolved discussion

**Review by vertex451 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 210 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbZdoElEZY-ebl2H-tv:-NbZdoElEZY-ebl2H-tw:b5h4dum) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/tools/tools.go#L210)):*
> ```Go
> 				},
> 			},
> 			PlatformDarwinARM64: {
> ```

Since I am using darwinARM64, I need this to prevent the error: `Application returned error: tool gaia is not configured for platform darwin.arm64`.
`PlatformDarwinAMD64` and `PlatformLinuxAMD64` are need to simplify `saveClientWrapper` command and retrieve all binaries from `tools.BinariesRootPath(tools.PlatformLocal)/bin` directory

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmwgsE2t9RLKKfgIze:-NbmwgsFAGtIw_gxYXhn:bkvee4z) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/go.mod#L15)):*
> ```XML
> 	github.com/CoreumFoundation/coreum-tools v0.4.1-0.20230627094203-821c6a4eebab
> 	github.com/CoreumFoundation/coreum/v2 v2.0.3-0.20230809094605-79de52cdf4d0
> 	github.com/CoreumFoundation/crust/build v0.0.0-20230811092000-ae7df2ee56b7
> ```

Code in `crust` should not refer to `build`
___
*[`build/index.go` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbmwu9C8EyMDntb6oJA:-Nbmwu9C8EyMDntb6oJB:bimmg6h) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/index.go#L83)):*
> ```Go
> 		crust.BuildZNet,
> 		buildIntegrationTests,
> 		gaia.EnsureBinary,
> ```

It should not be added here. If any action listed above requires gaiad or osmosisd, that action should specify them internally using `deps`
___
*[`build/gaia/build.go` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbmx60SEESyBSdS48b0:-Nbmx60SEESyBSdS48b1:be7rxfc) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/gaia/build.go#L11)):*
> ```Go
> 
> // EnsureBinary installs gaiad binary to crust cache.
> func EnsureBinary(ctx context.Context, deps build.DepsFunc) error {
> ```

`build.go` is a bad name because this code does not build anything. Maybe `install.go` or `ensure.go`?
___
*[`build/osmosis/build.go` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmxCk_EM4PMJK5aJwK:-NbmxCk_EM4PMJK5aJwL:be7rxfc) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/osmosis/build.go#L10)):*
> ```Go
> )
> 
> // EnsureBinary installs osmosis binary to crust cache.
> ```

`build.go` is a bad name because this code does not build anything. Maybe `install.go` or `ensure.go`?
___
*[`build/tools/tools.go` line 221 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmxNKZDXsdnj5Kt9u3:-NbmxNKZDXsdnj5Kt9u4:b-a7l73h) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/tools/tools.go#L221)):*
> ```Go
> 
> 	// https://github.com/osmosis-labs/osmosis/releases
> 	Osmosis: {
> ```

If we need this binary, then I vote for creating local docker image for running osmosis inside `znet` (like we do for gaia), to save on downloading the osmosis docker image. And to be always sure that we use the same version in both places.
___
*[`build/tools/tools.go` line 222 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmxsXMArWA78374MYB:-NbmxsXMArWA78374MYC:bqkukb9) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/tools/tools.go#L222)):*
> ```Go
> 	// https://github.com/osmosis-labs/osmosis/releases
> 	Osmosis: {
> 		Version: "16.1.1",
> ```

znet uses different version

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: 4 of 11 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmwgsE2t9RLKKfgIze:-NbnHtwY7l4jjcsuJRKH:bc7wk28) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/go.mod#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Code in `crust` should not refer to `build`
</blockquote></details>

I used it in the `infra/cosmoschain/base.go` to call the `tools.BinariesRootPath` function to retrieve the path to the binary from the crust cache. (Otherwise, I need to copy functions from there together with Platform struct and it's all values)

I see that this crust/build belongs to the Coreum repo but `github.com/CoreumFoundation/crust/build/tools` is imported 21 times to crust. 
Where the line goes?
___
*[`build/index.go` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbmwu9C8EyMDntb6oJA:-NbnIXFJEmdT7WCfZZto:b-m544bz) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/index.go#L83)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should not be added here. If any action listed above requires gaiad or osmosisd, that action should specify them internally using `deps`
</blockquote></details>

Moved to `crust.BuildZNet` since I need those binaries only in case of using znet.
___
*[`build/osmosis/build.go` line 10 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmxCk_EM4PMJK5aJwK:-NbnH_nfCRJVmj-mPUL7:b-wk3v94) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/osmosis/build.go#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`build.go` is a bad name because this code does not build anything. Maybe `install.go` or `ensure.go`?
</blockquote></details>

Agree, renamed to ensure.go
___
*[`build/tools/tools.go` line 221 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmxNKZDXsdnj5Kt9u3:-NbnIfVx5z_0x5bVdGUQ:bmj72i7) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/tools/tools.go#L221)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If we need this binary, then I vote for creating local docker image for running osmosis inside `znet` (like we do for gaia), to save on downloading the osmosis docker image. And to be always sure that we use the same version in both places.
</blockquote></details>

Added osmosis binary
___
*[`build/gaia/build.go` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbmx60SEESyBSdS48b0:-NbnHL0_891XYEcEILR7:b-wk3v94) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/build/gaia/build.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`build.go` is a bad name because this code does not build anything. Maybe `install.go` or `ensure.go`?
</blockquote></details>

Agree, renamed to ensure.go

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`go.mod` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmwgsE2t9RLKKfgIze:-NbniuOt2BhtRBDfS_xp:b-3k0g05) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/go.mod#L15)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

I used it in the `infra/cosmoschain/base.go` to call the `tools.BinariesRootPath` function to retrieve the path to the binary from the crust cache. (Otherwise, I need to copy functions from there together with Platform struct and it's all values)

I see that this crust/build belongs to the Coreum repo but `github.com/CoreumFoundation/crust/build/tools` is imported 21 times to crust. 
Where the line goes?
</blockquote></details>

`build` is never imported outside `build`. This is prevented intentionally to not mix those two things. If you need sth in the rest of `crust`, then implement it there.
___
*[`build/index.go` line 94 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbnjJ-A5UVM6mVm7Egl:-NbnjJ-A5UVM6mVm7Egm:b-rdwudp) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/index.go#L94)):*
> ```Go
> 		hermes.BuildDockerImage,
> 		relayer.BuildDockerImage,
> 		osmosis.BuildDockerImage,
> ```

move osmosis after gaia to keep things organized
___
*[`build/crust/build.go` line 32 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbnjZU41ZWepaEP75hB:-NbnjZU41ZWepaEP75hC:b-88oyx1) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/crust/build.go#L32)):*
> ```Go
> // BuildZNet builds znet.
> func BuildZNet(ctx context.Context, deps build.DepsFunc) error {
> 	deps(golang.EnsureGo, gaia.EnsureBinary, osmosis.EnsureBinary)
> ```

znet also requires:
- cored binary
- gaia docker image
- osmosis docker image
- cosmos relayer docker image
- hermes docker image

We overlooked them in the past. You may fix it here or create a task to do it.
___
*[`build/osmosis/image.go` line 31 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbnk-1m4jg31UgeAl0y:-Nbnk-1m4jg31UgeAl0z:bkdym8n) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/osmosis/image.go#L31)):*
> ```Go
> 
> 	dockerfile, err := dockerbasic.Execute(dockerbasic.Data{
> 		From:   docker.UbuntuImage,
> ```

Please check if it works with `docker.AlpineImage` - if osmosis starts in znet
___
*[`build/tools/tools.go` line 221 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbnkJtx24kBhQUtXFzg:-NbnkJtx24kBhQUtXFzh:b-nxdq8j) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/tools/tools.go#L221)):*
> ```Go
> 
> 	// https://github.com/osmosis-labs/osmosis/releases
> 	// FIXME [Artem S] make it work with v16 or compile v15 for darwin
> ```

Does it mean that v16 indeed doesn't work in znet?
___
*[`build/tools/tools.go` line 224 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbnkQWH1BgmPpH_C-vN:-NbnkQWH1BgmPpH_C-vO:bmemhbd) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/tools/tools.go#L224)):*
> ```Go
> 	Osmosis: {
> 		Version: "15.2.0",
> 		Sources: Sources{
> ```

This blocker is just a mark that code here must be fixed before merging
___
*[`infra/apps/osmosis/osmosis.go` line 9 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbnkd21-aR5DCjg7WG8:-Nbnkd21-aR5DCjg7WG9:buc8jri) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/infra/apps/osmosis/osmosis.go#L9)):*
> ```Go
> 
> const (
> 	// dockerImage = "osmolabs/osmosis:15.2.0-alpine" // FIXME (wojtek): version 16.1.2-alpine is available but it breaks our scripts.
> ```

Remove commented code before merging

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: 4 of 13 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbmwgsE2t9RLKKfgIze:-Nbo05KiDpRdo0Dq-1ex:b-8n340i) ([raw file](https://github.com/CoreumFoundation/crust/blob/e06b78b26f46fa521f35cc2be581f58883fa8ba2/go.mod#L15)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

So, what about other
</blockquote></details>

Sorry, leftover, copied code from coreum repo and put it to the crust/pkg/tools

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 7 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 7 files at r2, 2 of 7 files at r3, 8 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`build/crust/build.go` line 32 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbnjZU41ZWepaEP75hB:-Nbs0NJkD96zmGyZFOHf:b1khlao) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/crust/build.go#L32)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

Let's track it with a separate task:
https://app.clickup.com/t/8685af3m0
</blockquote></details>

isn't it just adding more items to this list ? if so, it might not require a separate task maybe ?
___
*[`build/tools/tools.go` line 225 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbs0qB13TRc-0MGG2Na:-Nbs0qB265dxC-Cwi6pT:b3zhmo9) ([raw file](https://github.com/CoreumFoundation/crust/blob/9f7dee0b1e42a0e2c9084d26763e5d078e7e09cd/build/tools/tools.go#L225)):*
> ```Go
> 		Version: "15.2.0",
> 		Sources: Sources{
> 			PlatformDockerAMD64: {
> ```

we should not need docker anymore, right ?

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/crust/build.go` line 32 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/268#-NbnjZU41ZWepaEP75hB:-NbsL5OyA0KGnHAFMUo7:b-f7ur6x) ([raw file](https://github.com/CoreumFoundation/crust/blob/465d62628f3f0483a409fca9de1c409e1866fb0b/build/crust/build.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

isn't it just adding more items to this list ? if so, it might not require a separate task maybe ?
</blockquote></details>

If it is that simple, I can do it.
Done.
___
*[`build/tools/tools.go` line 225 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbs0qB13TRc-0MGG2Na:-NbsKGfK2N9sJ2CVHXXo:b8y4r08) ([raw file](https://github.com/CoreumFoundation/crust/blob/9f7dee0b1e42a0e2c9084d26763e5d078e7e09cd/build/tools/tools.go#L225)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should not need docker anymore, right ?
</blockquote></details>

As I understand we need, especially after my changes

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 225 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/268#-Nbs0qB13TRc-0MGG2Na:-NbsmxrUBO-owuf1c7of:bihvtqz) ([raw file](https://github.com/CoreumFoundation/crust/blob/9f7dee0b1e42a0e2c9084d26763e5d078e7e09cd/build/tools/tools.go#L225)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

As I understand we need, especially after my changes
</blockquote></details>

I see, the old version (15) threw me off here, with the new version I guess you need both until the other problem regarding the building docker image is resolved. 
resolved this.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 8 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/268)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Pull request merged**
