### PR TITLE
Upgrade tools

### PR DESCRIPTION
**Pull request by wojtek-coreum**
go: v1.20.5
golangci: v1.53.3
gaia: v10.0.1
hermes: v1.5.1
osmosis: 15.1.2
grafana: 10.0.1
postgres: 15.3
prometheus: v2.45.0
alpine: 3.18.2
rust-optimizer 0.13.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ0g0Iy97TjsGcg2mr3:bxqv7o4) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
> ```Go
> 	BDJuno     bdjuno.BDJuno
> 	Hermes     hermes.Hermes
> 	// FIXME (dzmitry): after replacing cosmos relayer with hermes for osmosis sth here probably stops working.
> ```

Why the `FIXME (dzmitry)` :-) ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ0gVfs-VEYsSv_lWkv:b-xpa0at) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the `FIXME (dzmitry)` :-) ?
</blockquote></details>

Because I don't get the stuff around `job_name` in prometheus and grafana

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ15DXz6Vy-CaBBGgp7:b12qmsh) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because I don't get the stuff around `job_name` in prometheus and grafana
</blockquote></details>

Do you do you thing that `sth here probably stops working` ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ4wdBW0WT1jju-4eiV:blzml68) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you do you thing that `sth here probably stops working` ?
</blockquote></details>

yes because if osmosis uses hermes instead of cosmos relayer, then cosmos relayer cannot be set here

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ4wl_-6sQfuXrBVFDC:besnukg) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes because if osmosis uses hermes instead of cosmos relayer, then cosmos relayer cannot be set here
</blockquote></details>

In that case we have two hermes instances and the design here is not flexible to replace monitored apps easily. It requires modifying everything starting from here up to the prometheus config file. It should be implemented in a way where set of monitored apps is defined and prometheus app knows how to handle them.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ5pduHAETazIZn5Kw1:b-yt6uyy) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In that case we have two hermes instances and the design here is not flexible to replace monitored apps easily. It requires modifying everything starting from here up to the prometheus config file. It should be implemented in a way where set of monitored apps is defined and prometheus app knows how to handle them.
</blockquote></details>

Since we decided not to updathe osmisis in that PR we don't need the comment as well.  Right?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ61fi87U-ZuiWj4Y3O:bh63o4q) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Since we decided not to updathe osmisis in that PR we don't need the comment as well.  Right?
</blockquote></details>

I don't think so:
1. Problem with osmosis still exist, we just forget about it for a moment
2. Design here is still horrible

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ6DofA4IdpVbczDN5k:b-owiqw4) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't think so:
1. Problem with osmosis still exist, we just forget about it for a moment
2. Design here is still horrible
</blockquote></details>

It make sence to refactor it in general including the explorer since the design in it seems horrible as well. But I don't see a reason for that PR to add that fixme. Moreover I don't see a reason to add my name here :-)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ6G6AABWB-d7L-JAiZ:bfyhvct) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It make sence to refactor it in general including the explorer since the design in it seems horrible as well. But I don't see a reason for that PR to add that fixme. Moreover I don't see a reason to add my name here :-)
</blockquote></details>

okay, I will remove it

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/prometheus/prometheus.go` line 56 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/238#-NZ0g0IxA_69g-9iuNLs:-NZ6GRcvAxpj-2OCL0Yi:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/ecd8411cf9f196baf1af5ac23ced788d0388c3c8/infra/apps/prometheus/prometheus.go#L56)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

okay, I will remove it
</blockquote></details>

Done

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 3 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
