### PR TITLE
Convert genesis content to be compatible with cored v1.0.0

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/304)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/304)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 410 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/304#-Nij1s9F4xMPTZhyZjO0:-Nij1s9F4xMPTZhyZjO1:b-qzjzll) ([raw file](https://github.com/CoreumFoundation/crust/blob/7c23685e224198243a69ded7fc3cf35f33323353/infra/apps/cored/cored.go#L410)):*
> ```Go
> 	}
> 
> 	if strings.HasPrefix(c.config.BinaryVersion, "v1") || strings.HasPrefix(c.config.BinaryVersion, "v2") {
> ```

Could you please explain why do you use both v1 and v2 here ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/304)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/cored/cored.go` line 410 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/304#-Nij1s9F4xMPTZhyZjO0:-Nij42raDHj9vJk7gvMx:blvxcx9) ([raw file](https://github.com/CoreumFoundation/crust/blob/7c23685e224198243a69ded7fc3cf35f33323353/infra/apps/cored/cored.go#L410)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why do you use both v1 and v2 here ?
</blockquote></details>

because "uri" and "uri_hash" were introduced in v3 so they don't work with both v2 and v1

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/304)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
