### PR TITLE
Run integration tests stored in `coreum`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/index.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/39#-N8hq-Gn2tsoV2d5VaQJ:-N8hq-Gn2tsoV2d5VaQK:bpsefch) ([raw file](https://github.com/coreumfoundation/crust/blob/53c811cda2fcc8c1c90cb81b6266719630f7e0dc/tests/index.go#L38)):*
> ```Go
> 	// with a single one running 200 of them.
> 	for i := 0; i < 10; i++ {
> 		tests = append(tests, testing.New(bank.TestTransferMaximumGas(nodes[i%len(nodes)], 20)))
> ```

why do we now send txs only to one node ?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`infra/testing/types.go` line 57 at r1](https://reviewable.io/reviews/coreumfoundation/crust/39#-N8hirgYCG0wQbmjH6SC:-N8hirgYCG0wQbmjH6SD:b-e6k3ld) ([raw file](https://github.com/coreumfoundation/crust/blob/bdde0c31c4a6f253b0a42f43e19969b59ea06c5d/infra/testing/types.go#L57)):*
> ```Go
> }
> 
> // FromCoreum imports coreum tests
> ```

1. we find it a bit confusing that we have coreum & cored used sort of interchangeably. WDYT on this ? because we both `cored.Cored` & Coreum naming used. It is probably caused because we named our repo coreum while it contains cored inside. It also applies to imported pkg names `coreumtests` but according to convention it is right

2. if we decide to keep FromCoreum pls rephrase comment to smth like: `Import tests from coreum repository` 
___
*[`infra/testing/types.go` line 72 at r1](https://reviewable.io/reviews/coreumfoundation/crust/39#-N8hmZCvAInN8jn0_xkl:-N8hmZCvAInN8jn0_xkm:b-m1n43l) ([raw file](https://github.com/coreumfoundation/crust/blob/bdde0c31c4a6f253b0a42f43e19969b59ea06c5d/infra/testing/types.go#L72)):*
> ```Go
> 			name:    funcToName(testFunc),
> 			prepare: PrepareFunc(prepareFunc),
> 			run: func(ctx context.Context, t *T) {
> ```

we were thinking of just using `run: runFunc` but it doesn't work and found reasonable issue
because the signature is different.

But it is still looks sort of tricky. Maybe you have some better idea for this ?

**Review by miladz68 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39#-:-N8hy7_D25uPOtbO5Hwe:bnfp4nl)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`infra/testing/types.go` line 57 at r1](https://reviewable.io/reviews/coreumfoundation/crust/39#-N8hirgYCG0wQbmjH6SC:-N8i-QEx3D1yUHF7rExc:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/bdde0c31c4a6f253b0a42f43e19969b59ea06c5d/infra/testing/types.go#L57)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. we find it a bit confusing that we have coreum & cored used sort of interchangeably. WDYT on this ? because we both `cored.Cored` & Coreum naming used. It is probably caused because we named our repo coreum while it contains cored inside. It also applies to imported pkg names `coreumtests` but according to convention it is right

2. if we decide to keep FromCoreum pls rephrase comment to smth like: `Import tests from coreum repository` 
</blockquote></details>

Done

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

**Pull request merged**
