### PR TITLE
Use SDK config to generate HD paths

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/115)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/115)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/apps.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/crust/115#-NDWfw2YDJEwnyzAe8rn:-NDWfw2Z1dLc_tcCnZZr:bq4w1dy) ([raw file](https://github.com/coreumfoundation/crust/blob/43c0dca67030c5475b7801a0ea12651e6cd9a4f8/infra/apps/apps.go#L92)):*
> ```Go
> 			RootNode: node0,
> 			ImportedMnemonics: map[string]string{
> 				"alice":   cored.AliceMnemonic,
> ```

did you verify that alice, bob and charlie accounts imported to keystore in znet work? (e.g. `coredev-00 q bank balances <address of alice>`)?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/115)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/115)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/apps.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/crust/115#-NDWfw2YDJEwnyzAe8rn:-NDXKkMCBOKQ_p6JOxxI:bbxmuli) ([raw file](https://github.com/coreumfoundation/crust/blob/43c0dca67030c5475b7801a0ea12651e6cd9a4f8/infra/apps/apps.go#L92)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

did you verify that alice, bob and charlie accounts imported to keystore in znet work? (e.g. `coredev-00 q bank balances <address of alice>`)?
</blockquote></details>

yes

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
