### PR TITLE
Fix README to not use $HOME in instructions

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/190#-NTrfahTB2m42I_8GESb:-NTrfahTB2m42I_8GESc:bb40lfo) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee4a86210461387276548a91888bae658899315e/README.md#L12)):*
> ```Markdown
> 
> ## Building
> 1. Clone repo to the directory of your choice (let's call it `$COREUM_PATH`):
> ```

minor: as a first instruction I would add instruction where we set COREUM_PATH `COREUM_PATH="my/coreum/location` so users don't skip unintentionally 
___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/190#-NTTl_935AN06kAujrfa:-NTrfOGJ8bdI22FKpcy9:byxs7f4) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee4a86210461387276548a91888bae658899315e/README.md#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's not duplicate the code, and add the references better. 
@ysv  @wojtek-coreum  ?
</blockquote></details>

I didn't get what you mean

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/190#-NTTl_935AN06kAujrfa:-NTrkbVm1Dz8jfp0zfuv:b-ymz8i2) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee4a86210461387276548a91888bae658899315e/README.md#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't get what you mean 
</blockquote></details>

We have similar instructions in the coreum and crust. I propose to have just in one place.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/190#-NTTl_935AN06kAujrfa:-NTrvYQ49SbRTVTAuLNE:bsqs1d9) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee4a86210461387276548a91888bae658899315e/README.md#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We have similar instructions in the coreum and crust. I propose to have just in one place. 
</blockquote></details>

it is reasonable but IDK how to make it beautiful & not confusing for users because I don't want to redirect them to crust repo from coreum

Maybe we should just have this doc in coreum repo and reference it from crust ? WDYT @dzmitryhil @miladz68 ?

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/190#-NTTl_935AN06kAujrfa:-NTsDYGDCAKAz_KovisQ:b938ln9) ([raw file](https://github.com/CoreumFoundation/crust/blob/ee4a86210461387276548a91888bae658899315e/README.md#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think duplication is OK here. 
</blockquote></details>

In the docs repo it's even worse, let's then keep the duplication.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
