### PR TITLE
Update gaia to a version compatible with our version of IBC

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/428)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/428)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`infra/apps/gaiad/run.tmpl` line 61 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/428#-O6LMRc64kgZarJ_EONI:-O6LMRc64kgZarJ_EONJ:bj4dgql) ([raw file](https://github.com/CoreumFoundation/crust/blob/dfc41b3d3697ee3b3793c18856f55911ba75766e/infra/apps/gaiad/run.tmpl#L61)):*
> ```
> --p2p.laddr {{ .P2PLaddr }} \
> --grpc.address {{ .GRPCAddress }} \
> --grpc-web.address {{ .GRPCWebAddress }} \
> ```

Does the support removed ?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/428)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/gaiad/run.tmpl` line 61 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/428#-O6LMRc64kgZarJ_EONI:-O6LN_-92ZTlsSyL57Wu:b-ehjvb8) ([raw file](https://github.com/CoreumFoundation/crust/blob/dfc41b3d3697ee3b3793c18856f55911ba75766e/infra/apps/gaiad/run.tmpl#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does the support removed ?
</blockquote></details>

It is using the same port for both.
reference: https://github.com/cosmos/cosmos-sdk/pull/14652

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/428)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`infra/apps/gaiad/run.tmpl` line 61 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/428#-O6LMRc64kgZarJ_EONI:-O6Ldf7l6pvm-hiW7JoO:brf8j4u) ([raw file](https://github.com/CoreumFoundation/crust/blob/dfc41b3d3697ee3b3793c18856f55911ba75766e/infra/apps/gaiad/run.tmpl#L61)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is using the same port for both.
reference: https://github.com/cosmos/cosmos-sdk/pull/14652
</blockquote></details>

But don't you need to remove it from go-code as well?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/428)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/428)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
