### PR TITLE
Generate OpenAPI spec

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Generate OpenAPI spec from proto files for Cosmos API server

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`build/coreum/generate-proto-openapi.go` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdEr-z280BQmLH7_2yr:-NdEr-z280BQmLH7_2ys:bna64fy) ([raw file](https://github.com/CoreumFoundation/crust/blob/b39d15a14fbbc56ead6a9c57e1e44c39baeaeba7/build/coreum/generate-proto-openapi.go#L67)):*
> ```Go
> 	}
> 
> 	generateDirs := []string{
> ```

Optional: It would be nice to add root paths such as `absPath, "coreum"` and `oduleDirs[cosmosSDKModule], "proto", "cosmos"` to their variables to not duplicate them in the each line. 
___
*[`build/coreum/generate-proto-openapi.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdEqi8_0QiLMjNz3fVN:-NdEqi8_0QiLMjNz3fVO:b-x8ujrz) ([raw file](https://github.com/CoreumFoundation/crust/blob/b39d15a14fbbc56ead6a9c57e1e44c39baeaeba7/build/coreum/generate-proto-openapi.go#L93)):*
> ```Go
> 
> 	err = executeOpenAPIProtocCommand(ctx, deps, includeDirs, generateDirs)
> 	if err != nil {
> ```

Why don't you just retrun `executeOpenAPIProtocCommand(...)` ?
___
*[`build/coreum/generate-proto-openapi.go` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdErNcj65naeqgIKkOX:-NdErNcj65naeqgIKkOY:bsyp1ce) ([raw file](https://github.com/CoreumFoundation/crust/blob/b39d15a14fbbc56ead6a9c57e1e44c39baeaeba7/build/coreum/generate-proto-openapi.go#L166)):*
> ```Go
> 				for opK, opV := range v {
> 					var opID string
> 					if err := json.Unmarshal(opV["operationId"], &opID); err != nil {
> ```

Optional: `operationId`  looks like a candidate for a constant.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdErtyU4S32GI_OLccQ:-NdErtyU4S32GI_OLccR:b-86rsrt) (no related file):*
Our node, in addition to the SDK modules, exposed the tendermint REST service to get node info, which should be nice to include in the openapi spec and API docs as well. Probably in separate task. 
Here is the example: https://docs.tendermint.com/v0.34/rpc/

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdErtyU4S32GI_OLccQ:-NdEt4aN40j6brq_Itk0:bpezasx) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Our node, in addition to the SDK modules, exposed the tendermint REST service to get node info, which should be nice to include in the openapi spec and API docs as well. Probably in separate task. 
Here is the example: https://docs.tendermint.com/v0.34/rpc/
</blockquote></details>

This is yet another thing because that API is a different endpoint. Moreover, it's a static API (there is nothing to generate, right?) So we just need to take swagger spec from somewhere and add it to the repo.

___
___
*[`build/coreum/generate-proto-openapi.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdEqi8_0QiLMjNz3fVN:-NdEscrk2LPRcDdXL5ry:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/b39d15a14fbbc56ead6a9c57e1e44c39baeaeba7/build/coreum/generate-proto-openapi.go#L93)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you just retrun `executeOpenAPIProtocCommand(...)` ?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdErtyU4S32GI_OLccQ:-NdFbkZ_-gqxRkRRbbd7:bxoi2xt) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is yet another thing because that API is a different endpoint. Moreover, it's a static API (there is nothing to generate, right?) So we just need to take swagger spec from somewhere and add it to the repo.
</blockquote></details>

I'm not sure, probably it can be generated. Let's at least create a task for it.

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/281#-NdErtyU4S32GI_OLccQ:-NdUC4OP25r_Of0ArXCS:bwr4un7) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I'm not sure, probably it can be generated. Let's at least create a task for it.
</blockquote></details>

Done: https://app.clickup.com/t/8685gh9ad

___

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Pull request merged**
