### PR TITLE
Added latest tag to the go image

### PR DESCRIPTION
**Pull request by begmaroman**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/golang/go.go` line 204 at r1](https://reviewable.io/reviews/coreumfoundation/crust/94#-NCPJMkE84xeKuCvLlir:-NCPJMkF99DLzax7KeN-:b3zukva) ([raw file](https://github.com/coreumfoundation/crust/blob/4fde887d5e591d4803dd18077f88314bc3cb9218/build/golang/go.go#L204)):*
> ```Go
> 	}
> 
> 	buildCmd := exec.Command("docker", "build", "--tag", image, "--tag", "crust-go-build:znet", "-")
> ```

`znet` doesn't use this image at all. I think just `latest` is a better tag for this

**Review by begmaroman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 204 at r1](https://reviewable.io/reviews/coreumfoundation/crust/94#-NCPJMkE84xeKuCvLlir:-NCPQGrU2Ty3SUtOg7FF:boj7l8c) ([raw file](https://github.com/coreumfoundation/crust/blob/4fde887d5e591d4803dd18077f88314bc3cb9218/build/golang/go.go#L204)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`znet` doesn't use this image at all. I think just `latest` is a better tag for this
</blockquote></details>

makes sense, done

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/94#-NCPViO25YJY7UQTCuqi:-NCPViO32BEGrqASCtFK:b2t4k9p) (no related file):*
Please update the title of the PR

___

**Review by begmaroman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/94#-NCPViO25YJY7UQTCuqi:-NCPXf9K1gU63OZIp0nL:bb7f2mf) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please update the title of the PR
</blockquote></details>

done

___

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — APPROVED** [review]

**Pull request merged**
