### PR TITLE
Bump tools

### PR DESCRIPTION
**Pull request by wojtek-coreum**
go: 1.19.2
golangci: 1.50.0
ignite: 0.24.0
libwasmmuslc: v1.1.1

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/124)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/124)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 144 at r1](https://reviewable.io/reviews/coreumfoundation/crust/124#-NEABJHpBvFZp6f5CbNp:-NEABJHpBvFZp6f5CbNq:bv5qyfw) ([raw file](https://github.com/coreumfoundation/crust/blob/05112a9093bf32eb99ab240a6bafde8d0e6117b5/build/tools/tools.go#L144)):*
> ```Go
> 			dockerARM64: {
> 				URL:  "https://github.com/CosmWasm/wasmvm/releases/download/v1.1.1/libwasmvm_muslc.aarch64.a",
> 				Hash: "sha256:9ecb037336bd56076573dc18c26631a9d2099a7f2b40dc04b6cae31ffb4c8f9a",
> ```

Are you sure that it's compatible with the wasm module we use?
https://github.com/CosmWasm/wasmd on the main ready the list of the VM and module compatibility

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/124)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 144 at r1](https://reviewable.io/reviews/coreumfoundation/crust/124#-NEABJHpBvFZp6f5CbNp:-NEAGv4w3sa5-lFWOigM:b-4ie2uh) ([raw file](https://github.com/coreumfoundation/crust/blob/05112a9093bf32eb99ab240a6bafde8d0e6117b5/build/tools/tools.go#L144)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Are you sure that it's compatible with the wasm module we use?
https://github.com/CosmWasm/wasmd on the main ready the list of the VM and module compatibility
</blockquote></details>

We use wasmd 0.28 and they declare compatibility with 1.1, so I believe 1.1.1 is covered too

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/124)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
