### PR TITLE
Update coreum module version

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/93)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/93)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by begmaroman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/93#-:-NCLrI5bE_4PT-U3C-4n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
