### PR TITLE
Set version on `cored` compilation

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/105)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/105)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/git/git.go` line 43 at r1](https://reviewable.io/reviews/coreumfoundation/crust/105#-ND3-_tR1QcYs-yXSLuc:-ND36av1-gdR7J-aZvvc:bcylb3k) ([raw file](https://github.com/coreumfoundation/crust/blob/c34127490814ce56280f50a3b199fa3ff7e18912/build/git/git.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

When is it possible to face such state?
</blockquote></details>

When you have uncommitted changes

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/105)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 108 at r1](https://reviewable.io/reviews/coreumfoundation/crust/105#-ND3-kddA07ZF6b-CtAw:-ND3YEad5emRdxru8D0Z:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/c34127490814ce56280f50a3b199fa3ff7e18912/build/coreum/build.go#L108)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about make the values "core" and "cored" constant, since we use them everywhere.
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
