### PR TITLE
Integration test checking that gas consumed by token transfer is below assumed level

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)

### CODE REVIEW

**Review by oliverasistemas — DISMISSED** [review]

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6IWryR8GPKtiJi5Kq8:b-8pc7cu) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
> ```Go
> 
> var (
> 	memo                   = strings.Repeat("-", 256) // cosmos sdk is configured to accept maximum memo of 256 characters by default
> ```

what is the logic of defining this memo here ?
___
*[`tests/index.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IVxWrDQlN6XJepa1w:-N6IVxWrDQlN6XJepa1x:b-htexvc) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/index.go#L26)):*
> ```Go
> 			testing.New(bank.TestCoreTransfer(node0)),
> 
> 			// Run the same test 9 times to reuse the parallelism implemented inside the testing framework to use CPUs fully.
> ```

so the idea is to run 9 * 20 txs to get more data & utilize paralelizm to make it faster?

if it is the case than description could be improved a bit because for me it seemed like we run because we can 

we could also pass num of tx as parameter so in the future we just change it
___
*[`tests/bank/gas.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6ITWI6EXsmpETXwEuq:-N6ITWI77N3F3hlakVuM:b4dg3f1) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/bank/gas.go#L48)):*
> ```Go
> 			var maxGasUsed int64
> 			toSend := cored.Balance{Denom: "core", Amount: amount}
> 			send := func(sender *cored.Wallet, receiver cored.Wallet) {
> ```

Is there any specific reason to define this fuction inside another which is actually inside other func ?

Can we just define send outside & use it. I would rather prefer to pass client explicitly rather than implicitly use it from external space as for gas used I would return it from func

I just don't like this wrapping funcs inside funcs which is not go style but some sort of functional approach

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6IZJzDEbztGVQ-c2xB:b-6n6vdf) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the logic of defining this memo here ?
</blockquote></details>

create 256 characters of anything ("------ ..." in this case)
___
*[`tests/bank/gas.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6ITWI6EXsmpETXwEuq:-N6IZdyD4n0fPUjUXGcu:b-nf7fyg) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/bank/gas.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Is there any specific reason to define this fuction inside another which is actually inside other func ?

Can we just define send outside & use it. I would rather prefer to pass client explicitly rather than implicitly use it from external space as for gas used I would return it from func

I just don't like this wrapping funcs inside funcs which is not go style but some sort of functional approach
</blockquote></details>

I decided to do it this way because it's a function specific to this test, it has no meaning outside it and moreover it's much simpler if it might just access private vars defined inside the test. And it's very simple to understand what it does. Do you still prefer to move it outside?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`tests/index.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IVxWrDQlN6XJepa1w:-N6J6y8d2wite-LtUk92:b-86ha5z) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/index.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so the idea is to run 9 * 20 txs to get more data & utilize paralelizm to make it faster?

if it is the case than description could be improved a bit because for me it seemed like we run because we can 

we could also pass num of tx as parameter so in the future we just change it
</blockquote></details>

The idea is:
1. I would like to run ~200 transactions to check statistically that gas used does not exceed the limit we defined
2. I could do it in a single test running 200 transactions but it would be slow
3. I could start 10 goroutines internally to make it faster but then I would fight for resources with other tests - in the future we will have many tests running in parallel, so it doesn't make sense to create more goroutines inside the test because number of CPUs is limited anyway
4. Because now we have only few tests, so it's possible to use 10 tests running 20 txs each, instead of running 200 of them by the same test.
5. In the future we will have to switch anyway but for now things might be executed faster.
6. Also transactions are sent to different nodes to not overload a single one but it probably doesn't matter here

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6JAZqaBBPQB52MJQmC:bl3ygoi) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

create 256 characters of anything ("------ ..." in this case)
</blockquote></details>

to give more context:
With every transaction you may attach a string which is stored on blockchain (I don't know why but long time ago Satoshi decided that it's a good idea to be able to put any funny text on blockchain). By default cosmos sdk limits the length of memo to 256 characters.
Cosmos sdk charges gas for every byte of transaction. So to consume maximum possible gas I set this string to maximum allowed length.

I generate it here to do it once, not every time a transaction is created.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6Ne7f4A-9OMTYhPqMs:b9qpd0b) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

to give more context:
With every transaction you may attach a string which is stored on blockchain (I don't know why but long time ago Satoshi decided that it's a good idea to be able to put any funny text on blockchain). By default cosmos sdk limits the length of memo to 256 characters.
Cosmos sdk charges gas for every byte of transaction. So to consume maximum possible gas I set this string to maximum allowed length.

I generate it here to do it once, not every time a transaction is created.
</blockquote></details>

the context is clear for me
but we need this memo only for some specific testing while we define it in main client .go file that is what seems to be strange for me.

There is no any business logic in this memo so I would prefer to move it to some _test.go file
___
*[`tests/index.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IVxWrDQlN6XJepa1w:-N6NehEA3BRJxOddQoS6:b-ph56r5) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/index.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The idea is:
1. I would like to run ~200 transactions to check statistically that gas used does not exceed the limit we defined
2. I could do it in a single test running 200 transactions but it would be slow
3. I could start 10 goroutines internally to make it faster but then I would fight for resources with other tests - in the future we will have many tests running in parallel, so it doesn't make sense to create more goroutines inside the test because number of CPUs is limited anyway
4. Because now we have only few tests, so it's possible to use 10 tests running 20 txs each, instead of running 200 of them by the same test.
5. In the future we will have to switch anyway but for now things might be executed faster.
6. Also transactions are sent to different nodes to not overload a single one but it probably doesn't matter here
</blockquote></details>

ok makes sense for me
___
*[`tests/index.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6NelpY25VG-zFsOZIj:-N6NelpY25VG-zFsOZIk:b3gkaxm) ([raw file](https://github.com/coreumfoundation/crust/blob/a606f892f5e3711598869cfb6b7ef6ae8a884d1e/tests/index.go#L31)):*
> ```Go
> 			// In the future, once we have more tests running in parallel, we will replace 10 tests running 20 transactions each
> 			// with a single one running 200 of them.
> 			testing.New(bank.TestTransferMaximumGas(node0, 20)),
> ```

minor: looks a bit scary 
I would still do this in for loop
```golang
for i := 0; i < 10; i ++ {
  			testing.New(bank.TestTransferMaximumGas(nodes[i%3], 20)),
}
```
___
*[`tests/bank/gas.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6ITWI6EXsmpETXwEuq:-N6NgUZa5-FePvBKhAqI:b-jnypd2) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/bank/gas.go#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I decided to do it this way because it's a function specific to this test, it has no meaning outside it and moreover it's much simpler if it might just access private vars defined inside the test. And it's very simple to understand what it does. Do you still prefer to move it outside?
</blockquote></details>

I don't like mixing outer namespace in inner functions I have strong opinion that it is wrong approach

I wish I could see it fully It might be not that beautiful but from what I have in mind now seems ok:
```golang
func sendAndReturnGasUsed(ctx, sender, receiver) int64, error {
 // define send amount here
 // return error if fails
}
```

If it is not as simple as this
___
*[`tests/bank/gas.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6NhF9Y0NX-mNCmzaM7:-N6NhF9Y0NX-mNCmzaM8:buw32s) ([raw file](https://github.com/coreumfoundation/crust/blob/a606f892f5e3711598869cfb6b7ef6ae8a884d1e/tests/bank/gas.go#L46)):*
> ```Go
> 			require.NoError(t, err)
> 
> 			var maxGasUsed int64
> ```

I prefer to be explicit and set it to 0 so I don't recall what is the default value for int64

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6NoWWY0G6iQ6zLlIay:b-twqzvz) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

the context is clear for me
but we need this memo only for some specific testing while we define it in main client .go file that is what seems to be strange for me.

There is no any business logic in this memo so I would prefer to move it to some _test.go file
</blockquote></details>

There is a business logic behind this because in integration test I'm checking how much gas transaction takes. And the memo is the part of the equation internally. That's why it can't be just a unit test, I need it in real code. I've put it by default in all the transactions because this code is used only for development so it's not harmful to add this memo to every tx.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`tests/index.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6NelpY25VG-zFsOZIj:-N6NtXH21XEnuY7Oooro:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/a606f892f5e3711598869cfb6b7ef6ae8a884d1e/tests/index.go#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: looks a bit scary 
I would still do this in for loop
```golang
for i := 0; i < 10; i ++ {
  			testing.New(bank.TestTransferMaximumGas(nodes[i%3], 20)),
}
```
</blockquote></details>

Done
___
*[`tests/bank/gas.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6ITWI6EXsmpETXwEuq:-N6NvJ2O4AQPOazA-5f3:b-2k8w3z) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/bank/gas.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like mixing outer namespace in inner functions I have strong opinion that it is wrong approach

I wish I could see it fully It might be not that beautiful but from what I have in mind now seems ok:
```golang
func sendAndReturnGasUsed(ctx, sender, receiver) int64, error {
 // define send amount here
 // return error if fails
}
```

If it is not as simple as this

</blockquote></details>

Implemented it the kosher way, but have to say that I prefer the previous version much more
___
*[`tests/bank/gas.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6NhF9Y0NX-mNCmzaM7:-N6NteVX6bPrMZdwZzO6:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/a606f892f5e3711598869cfb6b7ef6ae8a884d1e/tests/bank/gas.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I prefer to be explicit and set it to 0 so I don't recall what is the default value for int64
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @ysv)

**Review by xlab — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @ysv)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6m8d-D5b7j1DDhRNMs:b-mvp6a7) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
> so it's not harmful to add this memo to every tx.

But this could be a part of the integration test. What

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`tests/bank/gas.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6ITWI6EXsmpETXwEuq:-N6mCFoW1PASFaY1nop9:bw5806i) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/bank/gas.go#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Implemented it the kosher way, but have to say that I prefer the previous version much more
</blockquote></details>

if we do like this ?

```golang
for i := 0; i >= numOfTransactions; i++ {
  from, to := wallet1, wallet2
   if i % 2 == 1 {
    from, to = to, from
  }
  				gasUsed, err := sendAndReturnGasUsed(ctx, client, wallet1, wallet2, toSend)
				require.NoError(t, err)

				if gasUsed > maxGasUsed {
					maxGasUsed = gasUsed
				}
  				from.AccountSequence++
}

```



_Code quote:_
```Go
			for i := numOfTransactions / 2; i >= 0; i-- {
```
___
*[`tests/bank/gas.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6NhF9Y0NX-mNCmzaM7:-N6mBCFlCMNPBQAw9EQj:bagb4oi) ([raw file](https://github.com/coreumfoundation/crust/blob/a606f892f5e3711598869cfb6b7ef6ae8a884d1e/tests/bank/gas.go#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

did you forget to push ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @xlab)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6mCuxe4S6uPSbcgYDD:b-fh6n0x) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> so it's not harmful to add this memo to every tx.

But this could be a part of the integration test. What
</blockquote></details>

discussed in slack waiting for adding memo as param to a proper function

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`tests/bank/gas.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6NhF9Y0NX-mNCmzaM7:-N6mPrni6yYWkapoSqi5:b-wayaso) ([raw file](https://github.com/coreumfoundation/crust/blob/a606f892f5e3711598869cfb6b7ef6ae8a884d1e/tests/bank/gas.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

did you forget to push ?
</blockquote></details>

I pushed it but then removed again because linter (revive) complained about having `var maxGasUsed int64 = 0` saying that ` = 0` is not needed

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`infra/apps/cored/client.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6IWryR8GPKtiJi5Kq7:-N6mYQZO7cTvDysnm32m:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/infra/apps/cored/client.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

discussed in slack waiting for adding memo as param to a proper function
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/bank/gas.go` line 48 at r1](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6ITWI6EXsmpETXwEuq:-N6mbqaZAo-gygxPrPwT:b-qd0qdm) ([raw file](https://github.com/coreumfoundation/crust/blob/ae9ee4a13fe3796a023dfa45ba243b8cb005cbda/tests/bank/gas.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if we do like this ?

```golang
for i := 0; i >= numOfTransactions; i++ {
  from, to := wallet1, wallet2
   if i % 2 == 1 {
    from, to = to, from
  }
  				gasUsed, err := sendAndReturnGasUsed(ctx, client, wallet1, wallet2, toSend)
				require.NoError(t, err)

				if gasUsed > maxGasUsed {
					maxGasUsed = gasUsed
				}
  				from.AccountSequence++
}

```
</blockquote></details>

Good idea! Done

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13#-:-N6qSCyC5ikFlZShH9kc:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`infra/apps/cored/client.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6qR9Dw4w54fRevV0yR:-N6qR9Dx6zPOARyqRhlp:bfzh1sf) ([raw file](https://github.com/coreumfoundation/crust/blob/8724cf8ec1fe334baec1533bd1e949ed3ac7a1bf/infra/apps/cored/client.go#L197)):*
> ```Go
> 
> // TxBankSendData holds input data for PrepareTxBankSend
> type TxBankSendData struct {
> ```

Maybe `TxBankSendInput` .

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

___
*[`infra/apps/cored/client.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/crust/13#-N6qR9Dw4w54fRevV0yR:-N6qqj0EC0AS7WPBN9f3:b132usx) ([raw file](https://github.com/coreumfoundation/crust/blob/8724cf8ec1fe334baec1533bd1e949ed3ac7a1bf/infra/apps/cored/client.go#L197)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Maybe `TxBankSendInput` .
</blockquote></details>

Ok, will do it in next PR where I touch this part again

**Pull request merged**
