### PR TITLE
Generate go code from proto files

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

- Generate go code from proto files
- Extend crust to install tools based on the go package because some providers don't share precompiled binaries

Here: https://github.com/golang/go/issues/25922 it is described how `import` and `go install` might be used to install binaries compiled from go code:
- put a dummy import in the package with `go:build` tag
- use `go install -tag <tag> <package-to-build>` command

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/273)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/273)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/273#-Nc20Akj16EBy32_pSNV:-Nc20Akk1TLa0JlXFShu:b8jjbce) (no related file):*
This PR contains two commits:
- containing changes reiewed in previous PRs + necessary merges from master (tool versions)
- new changes related to fixing proto generation for v47

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/273)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/273)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @vertex451)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/273)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Pull request merged**
