### PR TITLE
update go version to 1.23.3

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/440)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/440)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/docker/docker_test.go` line 44 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/440#-OC2i89y8rweaFDyLBw6:-OC2i89y8rweaFDyLBw7:b-enc23f) ([raw file](https://github.com/CoreumFoundation/crust/blob/e352dde6f2b2770d67ba96294b9bdfdc27979844/build/docker/docker_test.go#L44)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		tc := tc
> ```

Why did you remove it? And same for other such case?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/440)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`build/docker/docker_test.go` line 44 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/440#-OC2i89y8rweaFDyLBw6:-OC2iVsK-yya_0opQXMK:bnkontk) ([raw file](https://github.com/CoreumFoundation/crust/blob/e352dde6f2b2770d67ba96294b9bdfdc27979844/build/docker/docker_test.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why did you remove it? And same for other such case?
</blockquote></details>

in newer version of go, this is no longer a reference and is a copy so it is not needed to copy it again. linter complains because of this.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/440)* status: 2 of 17 files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 14 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
