### PR TITLE
Add wasm IBC contract to build.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/221#-NXjRMDW-wS5Z6Sgx7r_:-NXjhzir0U90UmSi3_lR:b-ezpdam) ([raw file](https://github.com/CoreumFoundation/crust/blob/666272f4b348c86884d8170cb77767dc7fcc8a36/build/coreum/wasm.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

instead of passing `dirPath` and `name`, just pass one argument: `contractPath` which is `fileptah.Join(dirPath, name)`
</blockquote></details>

But that's almost the same. I don't see a big difference.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/221#-NXjRMDW-wS5Z6Sgx7r_:-NXnWANUDcEZYs1VXf0z:b-k2mpyt) ([raw file](https://github.com/CoreumFoundation/crust/blob/666272f4b348c86884d8170cb77767dc7fcc8a36/build/coreum/wasm.go#L66)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But that's almost the same. I don't see a big difference. 
</blockquote></details>

It's more about convention. This function does not need dir and name separately. This is like fopen taking full path instead of each dir and file name as separate arguments.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/221#-NXjRMDW-wS5Z6Sgx7r_:-NXsZgxKDM0o54IFY6vD:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/666272f4b348c86884d8170cb77767dc7fcc8a36/build/coreum/wasm.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's more about convention. This function does not need dir and name separately. This is like fopen taking full path instead of each dir and file name as separate arguments.
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 39 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/221#-NYXNMYV4sTE1gB9AE9t:-NYXNMYV4sTE1gB9AE9u:bn794i6) ([raw file](https://github.com/CoreumFoundation/crust/blob/85f8153a49907ab3015d08d87668b0e90837ad80/build/coreum/wasm.go#L39)):*
> ```Go
> 
> // CompileModulesSmartContracts compiles modules smart contracts.
> func CompileModulesSmartContracts(ctx context.Context, deps build.DepsFunc) error {
> ```

```go
func CompileSmartContracts(dir string) build.CommandFunc {
        return func(ctx context.Context, deps build.DepsFunc) error {
	        deps(ensureRepo)

                return compileWasmDir(dir, deps)
        }
}

```

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 39 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/221#-NYXNMYV4sTE1gB9AE9t:-NYXvGw7BrAh2L4ysSaq:b-58zfgs) ([raw file](https://github.com/CoreumFoundation/crust/blob/85f8153a49907ab3015d08d87668b0e90837ad80/build/coreum/wasm.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

```go
func CompileSmartContracts(dir string) build.CommandFunc {
        return func(ctx context.Context, deps build.DepsFunc) error {
	        deps(ensureRepo)

                return compileWasmDir(dir, deps)
        }
}

```
</blockquote></details>

Don't see a readon for additiona wrapper for the current `func CompileSmartContract(codeDirPath string) build.CommandFunc` func.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Pull request merged**
