### PR TITLE
Testing profiles will be chosen based on test groups

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`cmd/znet/main.go` line 107 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBLnJQ3ntQ1Gn91fcW:-NaBLnJUEPNipgxyK4-h:bymgzv4) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/cmd/znet/main.go#L107)):*
> ```Go
> 			case lo.Some(configF.TestGroups, []string{apps.TestGroupCoreumIBC, apps.TestGroupCoreumUpgrade}):
> 				configF.Profiles = []string{apps.ProfileIntegrationTestsIBC}
> 			case len(configF.TestGroups) == 0:
> ```

minor: 1st & 2nd case could be merged
___
*[`infra/apps/profiles.go` line 79 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBNYdnBmY8T6Evv50V:-NaBNYdnBmY8T6Evv50W:b-uja4wf) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L79)):*
> ```Go
> 
> // BuildAppSet builds the application set to deploy based on provided profiles.
> func BuildAppSet(appF *Factory, profiles []string, coredVersion string) (infra.AppSet, error) {
> ```

IMO this func start to get complicated in terms of business logic. 
Also I'm not 100% sure how it behaves for some cases
WDYT about adding unit-tests for it ?
___
*[`infra/apps/profiles.go` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBMSsLDKkLW7LY1I0w:-NaBMSsLDKkLW7LY1I0x:blsc22r) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L103)):*
> ```Go
> 		}
> 
> 		pMap[ProfileFaucet] = true
> ```

do you really need faucet in case of coreum-modules tests ?
___
*[`infra/apps/profiles.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBKu3BCnU1rG5hcX11:-NaBKu3BCnU1rG5hcX12:bdsb30a) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L106)):*
> ```Go
> 	}
> 
> 	if pMap[ProfileIntegrationTestsIBC] {
> ```

I thought that idea is not to set one profile based on another.
 IMO `ProfileIntegrationTestsIBC` standalone profile and instead of setting IBC you should treat it like this:

```
	if pMap[ProfileIBC] ||  pMap[ProfileIntegrationTestsIBC] {
		appSet = append(appSet, appF.IBC(AppPrefixIBC, coredApp)...)
	}
```

Also it seems to be more clear

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`cmd/znet/main.go` line 107 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBLnJQ3ntQ1Gn91fcW:-NaBSmXN5uqNrnCzzAqY:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/cmd/znet/main.go#L107)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: 1st & 2nd case could be merged
</blockquote></details>

Done
___
*[`infra/apps/profiles.go` line 79 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBNYdnBmY8T6Evv50V:-NaBYOcZDLlbCgNiKzws:bf8ebz1) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L79)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO this func start to get complicated in terms of business logic. 
Also I'm not 100% sure how it behaves for some cases
WDYT about adding unit-tests for it ?
</blockquote></details>

the code is not written in a testable way, do you want a major refactor ?
___
*[`infra/apps/profiles.go` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBMSsLDKkLW7LY1I0w:-NaBSw475xTtgpB7ETsE:b-j642qz) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L103)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you really need faucet in case of coreum-modules tests ?
</blockquote></details>

Well the code is not written in a testable way, do you want a major refactor ?
___
*[`infra/apps/profiles.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBKu3BCnU1rG5hcX11:-NaBUvwH-Uwh_VC1XfIh:brz6piv) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L106)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought that idea is not to set one profile based on another.
 IMO `ProfileIntegrationTestsIBC` standalone profile and instead of setting IBC you should treat it like this:

```
	if pMap[ProfileIBC] ||  pMap[ProfileIntegrationTestsIBC] {
		appSet = append(appSet, appF.IBC(AppPrefixIBC, coredApp)...)
	}
```

Also it seems to be more clear
</blockquote></details>

well, the main idea was to decide which profiles to start based on the test-groups flags.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/profiles.go` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBMSsLDKkLW7LY1I0w:-NaBxHrk8Ww-vUdMUGe3:b-tac7i5) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L103)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Well the code is not written in a testable way, do you want a major refactor ?
</blockquote></details>

I see that @miladz68 just update the constants, and partially touched the existing code, not sure that he should add tests for it. But let's discuss.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/profiles.go` line 103 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBMSsLDKkLW7LY1I0w:-NaCXZvj6x3O_-gX11e5:bvw9i1k) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L103)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see that @miladz68 just update the constants, and partially touched the existing code, not sure that he should add tests for it. But let's discuss. 
</blockquote></details>

Discussed that we don't need it. 
___
*[`infra/apps/profiles.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaBKu3BCnU1rG5hcX11:-NaCtv9p9X02UW75UVqY:bcipdch) ([raw file](https://github.com/CoreumFoundation/crust/blob/cd4beb2b8637a88af17764b5bc2729c490f40d54/infra/apps/profiles.go#L106)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well, the main idea was to decide which profiles to start based on the test-groups flags. 
</blockquote></details>

discussed that we keep it as is.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @vertex451)

___
*[`infra/apps/profiles.go` line 82 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaLMhE81Euwx4BwwZlR:-NaLMhE81Euwx4BwwZlS:b-28t723) ([raw file](https://github.com/CoreumFoundation/crust/blob/b5d1d1b3aedea985a20c46d5bad3dea943e4e94e/infra/apps/profiles.go#L82)):*
> ```Go
> func BuildAppSet(appF *Factory, profiles []string, coredVersion string) (infra.AppSet, error) {
> 	pMap := map[string]bool{}
> 	if err := checkProfiles(pMap); err != nil {
> ```

the fact that `pMap` is modified inside this function is not obvious. It would be better to return the map 
___
*[`infra/apps/profiles.go` line 174 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaLN1K3Ciupq_hDpohv:-NaLN1K3Ciupq_hDpohw:b-o0fia3) ([raw file](https://github.com/CoreumFoundation/crust/blob/b5d1d1b3aedea985a20c46d5bad3dea943e4e94e/infra/apps/profiles.go#L174)):*
> ```Go
> }
> 
> func decideNumOfCoredValidators(pMap map[string]bool) int {
> ```

this function is not used

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/profiles.go` line 82 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaLMhE81Euwx4BwwZlR:-NaLvy0E3K_6qOll2CIj:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/b5d1d1b3aedea985a20c46d5bad3dea943e4e94e/infra/apps/profiles.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

the fact that `pMap` is modified inside this function is not obvious. It would be better to return the map 
</blockquote></details>

Done.
___
*[`infra/apps/profiles.go` line 174 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaLN1K3Ciupq_hDpohv:-NaLvyTF06Nqekdpgu25:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/b5d1d1b3aedea985a20c46d5bad3dea943e4e94e/infra/apps/profiles.go#L174)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this function is not used
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 2 unresolved discussions (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @vertex451)

___
*[`cmd/znet/main.go` line 113 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaN2EP1DCF4dcjF3OBF:-NaN2EP239RUwM-Cu_cy:b-a6dzhu) ([raw file](https://github.com/CoreumFoundation/crust/blob/f5f88c703f6a42c05541959e7c37a96dfd292ced/cmd/znet/main.go#L113)):*
> ```Go
> 			}
> 			if lo.Contains(configF.TestGroups, apps.TestGroupFaucet) {
> 				configF.Profiles = []string{apps.ProfileFaucet}
> ```

I think it should append, no?
___
*[`infra/apps/profiles.go` line 82 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaLMhE81Euwx4BwwZlR:-NaN2KVd755ZT-C2cRfa:b-qdmm7c) ([raw file](https://github.com/CoreumFoundation/crust/blob/b5d1d1b3aedea985a20c46d5bad3dea943e4e94e/infra/apps/profiles.go#L82)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean you may create this map internally in the function, and not pass as a parameter here
___
*[`infra/apps/profiles.go` line 174 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaN2cyq9OIBQURShmqa:-NaN2cyq9OIBQURShmqb:b-967dkz) ([raw file](https://github.com/CoreumFoundation/crust/blob/f5f88c703f6a42c05541959e7c37a96dfd292ced/infra/apps/profiles.go#L174)):*
> ```Go
> 		return 5
> 	default:
> 		return 1
> ```

maybe it should panic?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`cmd/znet/main.go` line 113 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaN2EP1DCF4dcjF3OBF:-NaQgVfz8mPdAgLJ5siP:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/f5f88c703f6a42c05541959e7c37a96dfd292ced/cmd/znet/main.go#L113)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think it should append, no?
</blockquote></details>

Done.
___
*[`infra/apps/profiles.go` line 82 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaLMhE81Euwx4BwwZlR:-NaQeZDz1OOpsNc2u5BP:b-prdiol) ([raw file](https://github.com/CoreumFoundation/crust/blob/b5d1d1b3aedea985a20c46d5bad3dea943e4e94e/infra/apps/profiles.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean you may create this map internally in the function, and not pass as a parameter here
</blockquote></details>

gotcha, Done
___
*[`infra/apps/profiles.go` line 174 at r5](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaN2cyq9OIBQURShmqa:-NaQfHGe1weXpz7ZctXq:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/f5f88c703f6a42c05541959e7c37a96dfd292ced/infra/apps/profiles.go#L174)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe it should panic?
</blockquote></details>

Done

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @ysv)

___
*[`infra/apps/profiles.go` line 178 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/252#-NaR5vhR8lwLM4GsLE9T:-NaR5vhS-jfEfaQKDPqK:b-d46glf) ([raw file](https://github.com/CoreumFoundation/crust/blob/384a1f5c0b6f6a212fce49cf0509784ab6a0661b/infra/apps/profiles.go#L178)):*
> ```Go
> 
> func checkProfiles(profiles []string) (map[string]bool, error) {
> 	var pMap map[string]bool
> ```

`pMap := map[string]bool{}` otherwise it will panic

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @vertex451)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
