### PR TITLE
Lint and test `faucet` repo

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/65)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
The changes seems reasonable, be because the the dependencies issues we can't check that they work properly on CI. As soon as the CI pass I'll give my approval.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/65#-:-N9pvBndCZtd-f6qWP4D:bn88y6k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

**Review by miladz68 — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/65#-:-NA3_c0yAvQM7v5n7Huy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
Pls remove everything related to coreum-tools from here
Adding faucet is acceptable for me but for coreum-tools we will do some restructuring 

> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/65#-:-NAEQWvv5D7KMfN4_rxY:bos9q7d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/65#-:-NAERSvGC53mDrp6sh2u:bb6un1j)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @xlab)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

**Pull request merged**
