### PR TITLE
Remove/update the crust with the removed legacy types

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`go.mod` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEdu0tRD3-15hyaYPnn:-NEdu0tRD3-15hyaYPno:b-juo2y2) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/go.mod#L12)):*
> ```XML
> 
> require (
> 	github.com/CoreumFoundation/coreum v0.0.0-20221017082630-1a5292f0c4a7
> ```

Blocking until this commit is in master
___
*[`infra/apps/cored/cored.go` line 135 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEduUicB7zUxaaX3Vum:-NEduUicB7zUxaaX3Vun:b-io09zx) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/infra/apps/cored/cored.go#L135)):*
> ```Go
> 	must.OK(err)
> 
> 	return tx.NewClientContext(app.ModuleBasics).
> ```

Please remove dependency on `app` because it requires us to compile znet with cgo and libwasm.
This context is used only by pingpong meaning that only `bank` and `auth` modules must be added here, not entire `app.ModuleBasics`.

Please find the functions `BuildCoredLocally` and `BuildCoredInDocker` in `build/coreum/build.go` and remove lines:
`CGOEnabled:    true,`, `Tags:           []string{"muslc"},` and `LinkStatically: true,`

If after doing this, command `crust build/znet` succeeds, it means `znet` does not depend on libwasm
___
*[`pkg/znet/commands.go` line 269 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEdvbh8AqndY2NZKUQg:-NEdvbh8AqndY2NZKUQh:b-o5m2c1) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/pkg/znet/commands.go#L269)):*
> ```Go
> func importMnemonic(clientCtx tx.ClientContext, mnemonic string) sdk.AccAddress {
> 	keyInfo, err := clientCtx.Keyring().NewAccount(
> 		uuid.New().String(),
> ```

Maybe use names: "alice", "bob", "charlie"
___
*[`pkg/znet/commands.go` line 284 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEdvk5Y32w_L70Oi8Nv:-NEdvk5Z0JpaL_SlB2lj:bdvykq) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/pkg/znet/commands.go#L284)):*
> ```Go
> 
> 	amount := sdk.NewCoin(network.TokenSymbol(), sdk.OneInt())
> 	txf = txf.WithSimulateAndExecute(true)
> ```

you may simulate it once before loop, because amount is always the same

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`infra/apps/cored/cored.go` line 135 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEduUicB7zUxaaX3Vum:-NEfNgaf3J14p1d2IZsD:bf1bmdw) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/infra/apps/cored/cored.go#L135)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, removed. 
</blockquote></details>

so you may try to update `build` too

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`infra/apps/cored/cored.go` line 135 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEduUicB7zUxaaX3Vum:-NEfQ32pAdDDc4W1VTqN:b-8932mk) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/infra/apps/cored/cored.go#L135)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But the cored still need it.
</blockquote></details>

ahh, sorry I pointed you to wrong place. I meant `build/crust/build.go` and function `BuildZNet` there. `CGOEnabled:    true` might be removed there

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`infra/apps/cored/cored.go` line 135 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEduUicB7zUxaaX3Vum:-NEj251cB3TXt5K5xywn:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/infra/apps/cored/cored.go#L135)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ahh, sorry I pointed you to wrong place. I meant `build/crust/build.go` and function `BuildZNet` there. `CGOEnabled:    true` might be removed there
</blockquote></details>

Done.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEdu0tRD3-15hyaYPnn:-NEjSDpZ8p5ezX2qR_N7:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/go.mod#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

+
</blockquote></details>

Done

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`infra/apps/cored/cored.go` line 135 at r1](https://reviewable.io/reviews/coreumfoundation/crust/130#-NEduUicB7zUxaaX3Vum:-NEkGGQT9vFZoKYUA0SI:b33d0so) ([raw file](https://github.com/coreumfoundation/crust/blob/3edfa5afaed4e8ec1628282aa0597afdaa8e56c3/infra/apps/cored/cored.go#L135)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It doesn't work without the CGOEnabled: true,
</blockquote></details>

I see. It's because in coreum we import app in `integration-tests/testing/chain.go` :-(. And crust imports it to get NetworkConfig.
At least we are one step closer to removing this dependency.

**Pull request merged**
