### PR TITLE
WASM Contracts deployment via Crust

### PR DESCRIPTION
**Pull request by xlab**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/29)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/29)* status: all files reviewed, 14 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bUQMp4Z6RdDAIJPEj:-N7bUQMp4Z6RdDAIJPEk:bqoktok) (no related file):*
@miladz68 @ysv 

I haven't reviewed this PR deeply - mostly parts related to znet. I skipped all the parts related to the contract-building tool.
My opinion related to this tool is still strong, as discussed on the meeting, IMO we should not offer any kind of official tooling for building the contracts. We have no resources and capacity at the moment to maintain this kind of ecosystem. Such thing usually requires dedicated team providing support, tutorials etc. Because we are not actively developing our contracts, maintenance of this tool is a special investment, not a side effect of our daily operations.

Left some comments, I'm not blocking on them, so PR might be merged if you decide that it might be. But their non-blocking status should not be interpreted as the fact that they are minor.

___
___
*[`.gitignore` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7b9FPsDt0dCIUuqmvz:-N7b9FPt9EmuGvZChj6S:b-nr6cio) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L3)):*
> ```ignore
> .idea
> .vscode
> .DS_Store
> ```

I would prefer to not pollute repo's `.gitignore` with platform-specific stuff. Even `.idea` and `.vscode` should not be here. For that kind of things everyone may configure global .gitignore specific to his machine:

```
git config --global core.excludesfile ~/.gitignore
```
___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bAh2Y7KfFceApx69C:-N7bAh2Y7KfFceApx69D:bk2svum) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L4)):*
> ```ignore
> .vscode
> .DS_Store
> /var
> ```

I don't see this path to be used in the code
___
*[`infra/apps/cored/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bEnfbE9PorLm0Zh5c:-N7bEnfbE9PorLm0Zh5d:b-r3xz3p) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L47)):*
> ```Go
> 		strings.HasPrefix(addr, "https://"):
> 	default:
> 		addr = "http://" + addr
> ```

Could you return error in this case? Otherwise typos like `htps://` will generate weird errors later.
___
*[`infra/apps/cored/client.go` line 146 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bFWzA0R0lC4VwbZUw:-N7bFWzA0R0lC4VwbZUx:b9rdp09) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L146)):*
> ```Go
> 
> 	txSvcClient := txtypes.NewServiceClient(c.clientCtx)
> 	simRes, err := txSvcClient.Simulate(context.Background(), &txtypes.SimulateRequest{
> ```

Instead of using `context.Background()` use this one:

```go
requestCtx, cancel := context.WithTimeout(ctx, someReasonableTimeout)
defer cancel()
```

like other methods of the client. It's unexpected for smart contract to run for more than a second for example.
___
*[`infra/apps/cored/client.go` line 154 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bFKoZ6U2F2xmKFLkG:-N7bFKoZ6U2F2xmKFLkH:b-l7nybs) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L154)):*
> ```Go
> 	}
> 
> 	// usually gas has to be multiplied by some adjustment coeff: e.g. *1,5
> ```

`1,5` -> `1.5`
___
*[`infra/apps/cored/client.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bJB2s5C_l_r4yIbFm:-N7bJB2s5C_l_r4yIbFn:bcsf0qe) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L170)):*
> ```Go
> 	TxHash    string
> 	GasUsed   int64
> 	EventLogs sdk.StringEvents
> ```

@ysv @miladz68 

Earlier we decided to not expose sdk types from the client.
Can it be avoided here?
___
*[`infra/apps/cored/client.go` line 391 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bMarKEKTbD1wuxgu_:-N7bMarKEKTbD1wuxgua:bv18e63) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L391)):*
> ```Go
> // the encoded transaction or an error if the unsigned transaction cannot be
> // built.
> func buildSimTx(
> ```

I see some common parts here and in `signTx` and `Client.Encode`. Could you make some effort to merge this and `signTx` into a single function. Haven't dived deeply but looks like it should be possible.
___
*[`infra/apps/cored/client.go` line 433 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bKo-JEHQWF50osbXh:-N7bKo-JEHQWF50osbXi:b-yeg96b) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L433)):*
> ```Go
> // WASMQueryClient returns a WASM module querying client, initialized
> // using the internal clientCtx.
> func (c Client) WASMQueryClient() wasmtypes.QueryClient {
> ```

Instead of just returning `wasmQueryClient`, please create a method here which calls `c.wasmQueryClient.Code(...)` like you do later. The whole purpose of the client is to have all the operations required by other pieces of code grouped in single place/package.

Otherwise the client could just return `authQueryClient` and `bankQueryClient` too. I understand that you would probably prefer to do it this way but for now it is what it is and should not be changed without a discussion in the team, which might happen when I come back.
___
*[`infra/apps/cored/types.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bN5qdAfZSiT1avKyk:-N7bN5qe0D987XWe78J2:b-ymgjcc) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L45)):*
> ```Go
> }
> 
> func (w Wallet) AddressString() string {
> ```

maybe just `Address()` like in `w.Key`. I know that cosmos provides object representation of address and functions called `Address` returns that one, not string. But code in znet does not care much about cosmos, and it's a convention there that it operates everywhere using bech32-encoded strings, returned by methods called `Address`.
___
*[`infra/apps/cored/types.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bNarxB0Qfn2Cw_0fM:-N7bNary5kDACtO-DTAo:b-2uh0i3) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L49)):*
> ```Go
> }
> 
> func (w Wallet) Address() sdk.AccAddress {
> ```

This is exactly what `Wallet` should not expose. As already said in another comment, result of previous discussion (IIRC you left that daily before this discussion) was that we don't want to expose cosmos-sdk types from client code used by znet. Of course, we might discuss it again if you want to.
___
*[`infra/apps/cored/types.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bOXIgDeC7aukmxbSl:-N7bOXIh1bRqo_WlzBhM:b8v4hss) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L55)):*
> ```Go
> 
> // NewWalletFromKeyring allows to wrap an account key from keyring into an unsafe Wallet wrapper.
> func NewWalletFromKeyring(kb cosmkeyring.Keyring, accAddr sdk.AccAddress) (Wallet, error) {
> ```

This entire code (Wallet, Client etc.) was never intended to be used as any kind of professional, production-ready implementation of coreum blockchain client. It was just a code to group common client-specific functions (signing, broadcasting, preparing transactions) in a wrapper allowing to issue transactions using **temporary**, **random**, **autogenerated**,  **meaningless** private keys.

If the idea is to turn it into a production-ready client with correct security model, system keystore access etc. then let's do it correctly, not by just creating a weird workaround to provide functionality which was never intended to be supported here. It means that it should become it's own task to design it correctly and integrate properly into all the existing processes. Not by imitating a support for secure keystores by exposing secrets to entire neighborhood.

Otherwise half of the community will make fun of us once someone finds this code in the repo.

**This function should not go to master.**
___
*[`pkg/contracts/deploy.go` line 399 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bIsFgCV7Q9ROl1gwG:-N7bIsFhBMC-zTjNDOIG:ba6m2cc) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/pkg/contracts/deploy.go#L399)):*
> ```Go
> 			log.With(
> 				zap.String("txHash", txHash),
> 			).Warn("contract code stored MsgStoreCode, but events don't have codeID")
> ```

Capitalize log message
___
*[`pkg/contracts/deploy.go` line 399 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bIzlV4u-LkMU-k0TO:-N7bIzlV4u-LkMU-k0TP:b-8hrqb5) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/pkg/contracts/deploy.go#L399)):*
> ```Go
> 			log.With(
> 				zap.String("txHash", txHash),
> 			).Warn("contract code stored MsgStoreCode, but events don't have codeID")
> ```

What does this message mean?

**Review by xlab — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/29)* status: all files reviewed, 14 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.gitignore` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7b9FPsDt0dCIUuqmvz:-N7f-oaj5X9ZciVa-SzA:b-3xhb4q) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would prefer to not pollute repo's `.gitignore` with platform-specific stuff. Even `.idea` and `.vscode` should not be here. For that kind of things everyone may configure global .gitignore specific to his machine:

```
git config --global core.excludesfile ~/.gitignore
```
</blockquote></details>

And how `pollution of .gitignore` actually affects the project? Does it cause a global warming of the repo?
___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bAh2Y7KfFceApx69C:-N7f-ymBCV-M01ZE4b_s:bninaa1) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see this path to be used in the code
</blockquote></details>

That is the point of `.gitignore`, to ignore files on the disk that are not relevant to the code.
___
*[`infra/apps/cored/client.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bEnfbE9PorLm0Zh5c:-N7f04lP7GEw2E6BDsQW:bh9ew4r) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you return error in this case? Otherwise typos like `htps://` will generate weird errors later.
</blockquote></details>

Weird typos will generate weird errors. Enforcing the schema will break the current interface of the client and I don't want to revise all other scripts and code that uses it incorrectly (having host without schema).
___
*[`infra/apps/cored/client.go` line 391 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bMarKEKTbD1wuxgu_:-N7f1qHX9gkQyR8EiCaO:by5coy) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L391)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see some common parts here and in `signTx` and `Client.Encode`. Could you make some effort to merge this and `signTx` into a single function. Haven't dived deeply but looks like it should be possible.
</blockquote></details>

SimTx is not related to signTx, the Tx encoding there is for gas estimation and carries empty signature.
___
*[`infra/apps/cored/client.go` line 433 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bKo-JEHQWF50osbXh:-N7f20XHCbXrQeerTI5l:b8x4gwl) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L433)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Instead of just returning `wasmQueryClient`, please create a method here which calls `c.wasmQueryClient.Code(...)` like you do later. The whole purpose of the client is to have all the operations required by other pieces of code grouped in single place/package.

Otherwise the client could just return `authQueryClient` and `bankQueryClient` too. I understand that you would probably prefer to do it this way but for now it is what it is and should not be changed without a discussion in the team, which might happen when I come back.
</blockquote></details>

I don't like the idea of bringing all domain-specific things in a single place. The client has to be abstract and work with messages, not trying to wrap modules types into some custom wrappers (i.e. BankSend params are wrapped fro some reason). We don't have luxury to double-wrap every single message from chain into this extra layer that provides 0 abstractions.
___
*[`infra/apps/cored/types.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bN5qdAfZSiT1avKyk:-N7f3Xa3CJq-o-2VzqqP:b3e27s9) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L45)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe just `Address()` like in `w.Key`. I know that cosmos provides object representation of address and functions called `Address` returns that one, not string. But code in znet does not care much about cosmos, and it's a convention there that it operates everywhere using bech32-encoded strings, returned by methods called `Address`.
</blockquote></details>

Address() usually returns sdk.AccAddress.
___
*[`infra/apps/cored/types.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bOXIgDeC7aukmxbSl:-N7f3krR2SRqGXHd9XYC:b-90s02x) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L55)):*
> This entire code (Wallet, Client etc.) was never intended to be used as any kind

Okay, that's why I think the whole client shall be redone. Because extending current codebase that is just a quick hack to get some test done is a waste of time.

**Comment by xlab** [comment]
*[`infra/apps/cored/types.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bOXIgDeC7aukmxbSl:-N7f5M2JEeckKLPw7bd3:b-wy76ch) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L55)):*
>  It means that it should become it's own task to design it correctly and integrate properly into all the existing processes.

Doing that requires to have Keyring wrapper which is introduced there, but also exposing Cosmos SDK types, which is a good thing because we use Cosmos SDK.

**Comment by xlab** [comment]
*[`infra/apps/cored/types.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bNarxB0Qfn2Cw_0fM:-N7f5XPw9X_yVnRdJEfj:b-n7bgpx) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is exactly what `Wallet` should not expose. As already said in another comment, result of previous discussion (IIRC you left that daily before this discussion) was that we don't want to expose cosmos-sdk types from client code used by znet. Of course, we might discuss it again if you want to.
</blockquote></details>

Dailys are for standups and reports, I exist on every daily daily, I think I missed only 3 dailys so far. Yet you guys figured out something and agreed on that without me. If that was the intention (too agree on something without my input), I will not try to interfere you there.

But programming for Cosmos requires to expose and work with SDK types, you may have other plans, but in the end you'll give up and use SDK types anyway. That holds true for Geth types from Ethereum too.

**Comment by xlab** [comment]
*[`pkg/contracts/deploy.go` line 399 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bIzlV4u-LkMU-k0TO:-N7f6A3l0FcRm9-_8T32:b-h5b9fh) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/pkg/contracts/deploy.go#L399)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What does this message mean?
</blockquote></details>

Tx success, but its Logs are missing an important field. Could be due to a breaking API change (i.e. log field has been renamed)

**Comment by xlab** [comment]
*[`infra/apps/cored/client.go` line 170 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bJB2s5C_l_r4yIbFm:-N7f6hKp4c3LATDjD7Ct:bp2bc8p) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/client.go#L170)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv @miladz68 

Earlier we decided to not expose sdk types from the client.
Can it be avoided here?
</blockquote></details>

Can be avoided by reimplementing Cosmos SDK from scratch.

**Comment by xlab** [comment]
*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7uqBVGCJaRGDAHcTjS:-N7uqBVH4b8Dj27M5awA:bxnl0fg) (no related file):*
**Important notice** ⚠️

Before deploying a contract, you need to adjust the `genesis.json` produced by `crust znet`. This is required before another PR will be merged.
https://coreumfoundation.slack.com/archives/C03LL8YJFK6/p1658490239575019

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/29)* status: 13 of 35 files reviewed, 15 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bAh2Y7KfFceApx69C:-N8N5VSi00F02xuxpLl4:b-40hg5b) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L4)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

That is the point of `.gitignore`, to ignore files on the disk that are not relevant to the code.
</blockquote></details>

What this directory is used for?

**Comment by xlab** [comment]
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bAh2Y7KfFceApx69C:-N8XvHx30vcoJypY8JGE:b-ddtlvo) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What this directory is used for?
</blockquote></details>

For temporary development files, e.g. staged contracts

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/29)* status: 12 of 48 files reviewed, 16 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.gitignore` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7b9FPsDt0dCIUuqmvz:-N8YUdl46XEKjZcphZCS:b-i7du5o) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L3)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

And how `pollution of .gitignore` actually affects the project? Does it cause a global warming of the repo?
</blockquote></details>

Lets keep it in .gitignore
___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bAh2Y7KfFceApx69C:-N8YUqJ00NR3TeeR6jUm:b-myps4l) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L4)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

For temporary development files, e.g. staged contracts
</blockquote></details>

I don't mind keeping it here

pls add comment for this gitignore line so we don't have more questions in the future
___
*[`infra/apps/cored/types.go` line 59 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N8YjoYe7jvUxFFvDnqW:-N8YjoYe7jvUxFFvDnqX:bi6upjt) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/infra/apps/cored/types.go#L59)):*
> ```Go
> 	if err != nil {
> 		err = errors.Wrapf(err, "failed to locate key by address %s in the keyring", accAddr.String())
> 		return Wallet{}, nil
> ```

return err ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/29)* status: 12 of 48 files reviewed, 16 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`.gitignore` line 4 at r1](https://reviewable.io/reviews/coreumfoundation/crust/29#-N7bAh2Y7KfFceApx69C:-N8YliNLAErgj18IgcC0:b-54zv5a) ([raw file](https://github.com/coreumfoundation/crust/blob/bc15bc4dbb16fb52a402aa57e80087d01ae744a9/.gitignore#L4)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

For temporary development files, e.g. staged contracts
</blockquote></details>

Please put them in `os.UserCacheDir() + "/crust/wasm"`

**Pull request closed without merging**
