### PR TITLE
Fix crust setup

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/391#-NwJZkIs0mccq5vDAwUu:-NwJZkIs0mccq5vDAwUv:brkwkug) ([raw file](https://github.com/CoreumFoundation/crust/blob/63895ed4864ce5178f61c583d236f6ab59595edf/build/golang/go.go#L69)):*
> ```Go
> 	for _, envVar := range osEnv {
> 		e := strings.ToUpper(envVar)
> 		if !strings.Contains(e, "GOROOT=") && !strings.Contains(e, "GOPATH=") {
> ```

Could you please explain the reason of it, and PR in-general (BTW it is better to add the PR description if the title of not 100% clear as it's here) !?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/391#-NwJZkIs0mccq5vDAwUu:-NwKLvsX2AZz_hyqKkTN:b-54sgk1) ([raw file](https://github.com/CoreumFoundation/crust/blob/63895ed4864ce5178f61c583d236f6ab59595edf/build/golang/go.go#L69)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain the reason of it, and PR in-general (BTW it is better to add the PR description if the title of not 100% clear as it's here) !?
</blockquote></details>

It is for this ticket:
https://app.clickup.com/t/86883fzt0

And the change is preventing conflict with other go versions installed in the machine. Maybe I need to write a comment for it

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/391#-NwJZkIs0mccq5vDAwUu:-NwOBHR3AeGbD4mYhhag:b-xazt2a) ([raw file](https://github.com/CoreumFoundation/crust/blob/63895ed4864ce5178f61c583d236f6ab59595edf/build/golang/go.go#L69)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is for this ticket:
https://app.clickup.com/t/86883fzt0

And the change is preventing conflict with other go versions installed in the machine. Maybe I need to write a comment for it
</blockquote></details>

Sure, write it please.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/golang/go.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/391#-NwJZkIs0mccq5vDAwUu:-NwOIPN8Ebv8JVaoOGY4:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/63895ed4864ce5178f61c583d236f6ab59595edf/build/golang/go.go#L69)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Sure, write it please.
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391#-:-NwPo5pG0k8mcAs0TR5q:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
