### PR TITLE
Initial migration to the v0.47.1.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/cored/cored.go` line 221 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NSzJMgi1rVpTKn7iuhe:-NSzJMgjBGTMIlsHWwQ1:b-fz24mr) ([raw file](https://github.com/CoreumFoundation/crust/blob/4af012169d13847f5e7ce3d5ea4c3aacdbacba30/infra/apps/cored/cored.go#L221)):*
> ```Go
> 		WithGRPCClient(grpcClient).
> 		WithKeyring(keyring.NewInMemory()).
> 		WithBroadcastMode(flags.BroadcastBlock)
> ```

Sync should be used I guess
___
*[`infra/cosmoschain/base.go` line 121 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NSzJeR0CDpLv5pOv44D:-NSzJeR0CDpLv5pOv44E:b-80r4sh) ([raw file](https://github.com/CoreumFoundation/crust/blob/4af012169d13847f5e7ce3d5ea4c3aacdbacba30/infra/cosmoschain/base.go#L121)):*
> ```Go
> 		WithGRPCClient(grpcClient).
> 		WithKeyring(keyring.NewInMemory()).
> 		WithBroadcastMode(flags.BroadcastBlock)
> ```

Sync?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 221 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NSzJMgi1rVpTKn7iuhe:-NTIdsmDD9Z5NpVjoPqJ:b-rr7k4r) ([raw file](https://github.com/CoreumFoundation/crust/blob/4af012169d13847f5e7ce3d5ea4c3aacdbacba30/infra/apps/cored/cored.go#L221)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Sync should be used I guess
</blockquote></details>

Agree, fixed.



_Code quote:_
```Go
WithKeyring(keyring.NewIn
```
___
*[`infra/cosmoschain/base.go` line 121 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NSzJeR0CDpLv5pOv44D:-NTIduKK0yvz5zRRC84C:bt2vr1b) ([raw file](https://github.com/CoreumFoundation/crust/blob/4af012169d13847f5e7ce3d5ea4c3aacdbacba30/infra/cosmoschain/base.go#L121)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Sync?
</blockquote></details>

Fixed.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKOaQT8mHupsZuw_Z9:-NTKOaQT8mHupsZuw_ZA:b-ej50h6) (no related file):*
Once I try to run `crust tidy` on this branch I get this error
```
reading github.com/gogo/protobuf/go.mod at revision v1.3.3: unknown revision v1.3.3
```

I think we should add replace
```
github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1
```

___
___
*[`build/golang/Dockerfile.tmpl` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLunG71Yb9b7aVidB:-NTKLunH2dyK9ym06YTc:b-w4g5v8) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/golang/Dockerfile.tmpl#L11)):*
> ```
>     rm aarch64-linux-musl-cross.tgz && \
> # install arm64 version of libwasmvm library (required by cored)
>     wget https://github.com/CosmWasm/wasmvm/releases/download/v1.2.1/libwasmvm_muslc.aarch64.a && \
> ```

@wojtek-coreum @dzmitryhil 
do you think it is possible to use version of wasmvm from `var tools = map[Name]Tool` ?

(not for this PR just a discussion)
___
*[`build/tools/tools.go` line 141 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLhvRA2IffH_lKiWU:-NTKLhvRA2IffH_lKiWV:bpyde20) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/tools/tools.go#L141)):*
> ```Go
> 	// Check compatibility with wasmd beore upgrading: https://github.com/CosmWasm/wasmd
> 	LibWASMMuslC: {
> 		Version:   "v1.2.1",
> ```

1.2.3 has been released a few hours ago
Should we start with it ?
___
*[`infra/apps/cored/cored.go` line 337 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKMKWd43l-lTqtmeXQ:-NTKMKWd43l-lTqtmeXR:b-66prno) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/infra/apps/cored/cored.go#L337)):*
> ```Go
> 	appCfg.Telemetry.Enabled = true
> 	appCfg.Telemetry.PrometheusRetentionTime = 600
> 	appCfg.MinGasPrices = fmt.Sprintf("0.00000000000000001%s", c.config.Network.Denom())
> ```

will we live it like this ?
___
*[`infra/apps/cored/key.go` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKMz_oDgpJKlsbhdXy:-NTKMz_oDgpJKlsbhdXz:bf92wgv) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/infra/apps/cored/key.go#L31)):*
> ```Go
> }
> 
> // UnsafeKeyring is kering with n ability to get private key,
> ```

so they dropped UnsafeKeyring type I guess ?

minor:  kering with n ability to get private key -> KEYRING with AN ability to get private key. (dot not comma)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKOaQT8mHupsZuw_Z9:-NTO4oq5APoPnHr-KvTJ:b-nww33q) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Once I try to run `crust tidy` on this branch I get this error
```
reading github.com/gogo/protobuf/go.mod at revision v1.3.3: unknown revision v1.3.3
```

I think we should add replace
```
github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1
```
</blockquote></details>

You need both coreum and crust on the branch `dzmitryhil/v0.47-initial-migration`. I've tested it works for me. 

___
___
*[`build/golang/Dockerfile.tmpl` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLunG71Yb9b7aVidB:-NTO50PVDzfib8L_M4Te:bis11oe) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/golang/Dockerfile.tmpl#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum @dzmitryhil 
do you think it is possible to use version of wasmvm from `var tools = map[Name]Tool` ?

(not for this PR just a discussion)
</blockquote></details>

Yes, it's possible. And we should do it that way.
___
*[`build/tools/tools.go` line 141 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLhvRA2IffH_lKiWU:-NTO55ocCMCGTqlg1Ciy:b-fe11je) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/tools/tools.go#L141)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1.2.3 has been released a few hours ago
Should we start with it ?
</blockquote></details>

They recommend to use `v1.2.1` for `v0.40`.

___
*[`infra/apps/cored/cored.go` line 337 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKMKWd43l-lTqtmeXQ:-NTO5Ktw2ZU5_Jzgmy99:b-fk95jc) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/infra/apps/cored/cored.go#L337)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

will we live it like this ?
</blockquote></details>

Yes, why not? On the corem side we use `init` and the `init` sets it. But here we generate the config manually, that's why we need to repeat it.
___
*[`infra/apps/cored/key.go` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKMz_oDgpJKlsbhdXy:-NTO5kKzAz051cAexLvu:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/infra/apps/cored/key.go#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so they dropped UnsafeKeyring type I guess ?

minor:  kering with n ability to get private key -> KEYRING with AN ability to get private key. (dot not comma)
</blockquote></details>

Done.



_Code quote:_
```Go
UnsafeKeyring is kering wit
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`build/golang/Dockerfile.tmpl` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLunG71Yb9b7aVidB:-NTOAo0G8nHkCJsLCk2-:b-c6muye) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/golang/Dockerfile.tmpl#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, it's possible. And we should do it that way.
</blockquote></details>

Yes, even better if we could avoid downloading it in dockerfile. The problem is that crosscompiler does not support libraries stored in another dir than the one specified below. At least I spent a lot of time trying to do it without any success.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/golang/Dockerfile.tmpl` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLunG71Yb9b7aVidB:-NTTS8VhERbwJK2LEl_H:bi2wmu1) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/golang/Dockerfile.tmpl#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yes, even better if we could avoid downloading it in dockerfile. The problem is that crosscompiler does not support libraries stored in another dir than the one specified below. At least I spent a lot of time trying to do it without any success.
</blockquote></details>

lets leave a todo in crust for this ?
___
*[`infra/apps/cored/cored.go` line 337 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKMKWd43l-lTqtmeXQ:-NTTSKI29-ii5KaqcSnu:b84akvk) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/infra/apps/cored/cored.go#L337)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, why not? On the corem side we use `init` and the `init` sets it. But here we generate the config manually, that's why we need to repeat it.
</blockquote></details>

I'm ok to set it here
Question is mostly about this value `0.00000000000000001`. Is it the smallest possible value for sdk.Dec ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/golang/Dockerfile.tmpl` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKLunG71Yb9b7aVidB:-NTTlUVW2C_LcCsEkaoZ:bw8m3vm) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/build/golang/Dockerfile.tmpl#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets leave a todo in crust for this ?
</blockquote></details>

Better task. 
___
*[`infra/apps/cored/cored.go` line 337 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/186#-NTKMKWd43l-lTqtmeXQ:-NTTlFKQ2WXYTwEJC24Y:b-x4n3ro) ([raw file](https://github.com/CoreumFoundation/crust/blob/bb603f45cdbb70304377b5858492c88c721eb01a/infra/apps/cored/cored.go#L337)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm ok to set it here
Question is mostly about this value `0.00000000000000001`. Is it the smallest possible value for sdk.Dec ?
</blockquote></details>

Nope, not smallest, but small enough not to reach any real min gas price.

**Review by miladz68 — APPROVED** [review]
> Reviewed 7 of 10 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
