### PR TITLE
Add timeout-commit flag for znet start and test subcommands.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_bgWFj9zaDQ7VXFE6b:-N_bgWFj9zaDQ7VXFE6c:biri2ih) (no related file):*
In general, I'm against this PR. Adding new flag to control every aspect of the environment, over time leads to situation where there are tons of them and no one understands what they do. If we want to speed up the chains, then let's simply set the timeout to 0.5s internally, without exposing it as a flag.

Why do we use 0.5s in one test set but 1s in the others?

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_bgWFj9zaDQ7VXFE6b:-N_bliwI1jyhTDvlmOi3:b-i5qxiz) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In general, I'm against this PR. Adding new flag to control every aspect of the environment, over time leads to situation where there are tons of them and no one understands what they do. If we want to speed up the chains, then let's simply set the timeout to 0.5s internally, without exposing it as a flag.

Why do we use 0.5s in one test set but 1s in the others?
</blockquote></details>

But that was the task to add it as an optional config to be able to run with default or updated time. The best way to do it is flag.

`Why do we use 0.5s in one test set but 1s in the others?` -  we use 1sec for the IBC tests, if the timeout-commit is fast on both chanis the IBC relayer can't create a connection, since the clients state is never in-sync. 

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_c9m9SENZh0aYMRRCq:-N_c9m9SENZh0aYMRRCr:bgw6g2w) (no related file):*
the reason for clients not being able to sync when commit timeout is 500ms, is probably `batch_delay = '%00ms'` hermes config. reduce it to 100ms and it should workout. 

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_c9m9SENZh0aYMRRCq:-N_hzUIA-OEQL0MlohVH:b-135yuj) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the reason for clients not being able to sync when commit timeout is 500ms, is probably `batch_delay = '%00ms'` hermes config. reduce it to 100ms and it should workout. 
</blockquote></details>

This config is for the new v1.6.0 feature, I've tested it:
```
event_source = { mode = 'push', url = '{{ .CoreumWebsocketURL }}', batch_delay = '100ms' }
```

Same result:

```2023-07-19T11:52:33.153847Z ERROR ThreadId(01) failed ChanOpenAck ChannelSide { chain: BaseChainHandle { chain_id: coreum-devnet-1 }, client_id: 07-tendermint-0, connection_id: connection-0, port_id: transfer, channel_id: channel-0, version: None }: failed during an operation on client '07-tendermint-0' hosted by chain 'coreum-devnet-1': update header from gaia-localnet-1 with height 1-703 and time 2023-07-19T12:00:34.107519839Z is in the future compared with latest header on coreum-devnet-1 with height 1-251 and time 2023-07-19T11:53:06.243285341Z, adjusted with drift 40s

```

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_c9m9SENZh0aYMRRCq:-N_hzlBJ5Vdqz2e4Ym11:bwn78oe) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This config is for the new v1.6.0 feature, I've tested it:
```
event_source = { mode = 'push', url = '{{ .CoreumWebsocketURL }}', batch_delay = '100ms' }
```

Same result:

```2023-07-19T11:52:33.153847Z ERROR ThreadId(01) failed ChanOpenAck ChannelSide { chain: BaseChainHandle { chain_id: coreum-devnet-1 }, client_id: 07-tendermint-0, connection_id: connection-0, port_id: transfer, channel_id: channel-0, version: None }: failed during an operation on client '07-tendermint-0' hosted by chain 'coreum-devnet-1': update header from gaia-localnet-1 with height 1-703 and time 2023-07-19T12:00:34.107519839Z is in the future compared with latest header on coreum-devnet-1 with height 1-251 and time 2023-07-19T11:53:06.243285341Z, adjusted with drift 40s

```
</blockquote></details>

2023-07-19T11:52:33.153847Z ERROR ThreadId(01) failed ChanOpenAck ChannelSide { chain: BaseChainHandle { chain_id: coreum-devnet-1 }, client_id: 07-tendermint-0, connection_id: connection-0, port_id: transfer, channel_id: channel-0, version: None }: failed during an operation on client '07-tendermint-0' hosted by chain 'coreum-devnet-1': update header from gaia-localnet-1 with height 1-703 and time 2023-07-19T12:00:34.107519839Z is in the future compared with latest header on coreum-devnet-1 with height 1-251 and time 2023-07-19T11:53:06.243285341Z, adjusted with drift 40s

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 56 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_nJbG05LNDZL-TXbUq:-N_sCLbS64c10gcqrWC1:b-fwafnt) ([raw file](https://github.com/CoreumFoundation/crust/blob/1999b0beb3a6ded6994a5b426bd4cdebbdd8643d/.github/workflows/ci.yml#L56)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why do we need different values for different test types ?
</blockquote></details>

The IBC doesn't pass with fast bock time because of the cosmos realyer.
___
*[`cmd/znet/main.go` line 163 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_nIL5sB6Og-SlbTTnD:-N_sCScw1x1xyJDI3ys4:bs7rnq8) ([raw file](https://github.com/CoreumFoundation/crust/blob/1999b0beb3a6ded6994a5b426bd4cdebbdd8643d/cmd/znet/main.go#L163)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is 0s really good default value ?

or 0s means that default value for chain is used ?
</blockquote></details>

0s means that default value for chain is used

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 50 at r6](https://reviewable.io/reviews/CoreumFoundation/crust/250#-N_sX4Qe0uwSUq8Amqfm:-N_sXTTM5nYWGHeEDrTy:bb710yj) ([raw file](https://github.com/CoreumFoundation/crust/blob/376465d4a3ebf2f364d1beb5249ec38af80fe103/.github/workflows/ci.yml#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

did it not work with 0.5s ?
</blockquote></details>

Nope

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
