### PR TITLE
Expose metrics from faucet

### PR DESCRIPTION
**Pull request by wojtek-coreum**
Related to https://reviewable.io/reviews/CoreumFoundation/faucet/72

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/248)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/248)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

___
*[`infra/apps/faucet/faucet.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/248#-N_E-w9d-m4AbsY2iREz:-N_E0jdEDs-Y0rd4fo-_:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/70a3ef49af402fbc2021d0bfc6efb9407e141167/infra/apps/faucet/faucet.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The port is different from the default in the faucet PR, idealy it should be the same.
</blockquote></details>

Done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/248)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
