### PR TITLE
Update v0.47 migration to v2 compatible

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

The PR contains changes required for the crust to run tests for the coreum `v0.47-migration-v2` branch.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`infra/apps/cored/cored.go` line 222 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTn51iAZuA21AcdaSl:-NbTn51iAZuA21AcdaSm:bnwqgce) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L222)):*
> ```Go
> 		WithChainID(string(c.config.NetworkConfig.ChainID())).
> 		WithRPCClient(rpcClient).
> 		WithGRPCClient(grpcClient).
> ```

Why GRPC is removed? It is required for the health check. Otherwise RPC might be up but GRPC not (yet) and integration tests might fail
___
*[`infra/apps/cored/cored.go` line 223 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTnEbz9a1sRyU--xBa:-NbTnEbz9a1sRyU--xBb:borsaf0) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L223)):*
> ```Go
> 		WithRPCClient(rpcClient).
> 		WithGRPCClient(grpcClient).
> 		WithKeyring(keyring.NewInMemory()).
> ```

why removed?
___
*[`infra/apps/cored/cored.go` line 285 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTnKMm-dhERgaIdyhD:-NbTnKMm-dhERgaIdyhE:b-dh07q6) ([raw file](https://github.com/CoreumFoundation/crust/blob/99e50e6aed07b86bbaffc3472c8ed9f16a972262/infra/apps/cored/cored.go#L285)):*
> ```Go
> 				"--inv-check-period", "1",
> 				"--chain-id", string(c.config.NetworkConfig.ChainID()),
> 				"--minimum-gas-prices", fmt.Sprintf("0.000000000000000001%s", c.config.NetworkConfig.Denom()),
> ```

Ive seen in the cored PR that you set it there internally, so why is it needed to do it here?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 222 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTn51iAZuA21AcdaSl:-NbU4dAy8FC9fNi6elf8:b9bpu67) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L222)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think Dima explain this during the call
But I though that temporary fix is different there (not to use GRPC in integration tests).

As for removing it in healthchecks I'm not sure
</blockquote></details>

Right. And also we don't need to init both GRPC and RPC because only one works.
___
*[`infra/apps/cored/cored.go` line 223 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTnEbz9a1sRyU--xBa:-NbU4pDJ3CkbtMGhqmFM:bao9tgq) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L223)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why removed?
</blockquote></details>

See prev comment.
___
*[`infra/apps/cored/cored.go` line 285 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTnKMm-dhERgaIdyhD:-NbU4rc3BMx8aBBvHmD_:b-55ebq4) ([raw file](https://github.com/CoreumFoundation/crust/blob/99e50e6aed07b86bbaffc3472c8ed9f16a972262/infra/apps/cored/cored.go#L285)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Same question
</blockquote></details>

We ignore in the crust the standard init, and form the config ourselves

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 222 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTn51iAZuA21AcdaSl:-NbU74M08vrp3Q5DwRNq:bdsn474) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L222)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right. And also we don't need to init both GRPC and RPC because only one works.
</blockquote></details>

yes we don't need both
But in znet we want to make sure both are up in healthchecks, no ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @vertex451)

___
*[`infra/apps/cored/cored.go` line 223 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTnEbz9a1sRyU--xBa:-NbUBw0G4nw2eXQtygB0:baj3b5u) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L223)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

See prev comment.
</blockquote></details>

but this question is about keyring

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 222 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTn51iAZuA21AcdaSl:-NbUK63F4DEnv7ii-BdO:b-8qp7wt) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L222)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes we don't need both
But in znet we want to make sure both are up in healthchecks, no ?
</blockquote></details>

No, we need to check that znet is running. Also you you set both, only GRPC is used. 
___
*[`infra/apps/cored/cored.go` line 223 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTnEbz9a1sRyU--xBa:-NbUKPBG1DFDmxnuASV-:b989ya9) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L223)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but this question is about keyring
</blockquote></details>

I didn't get it. The keyring is removed since it isn't used for the client.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 222 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTn51iAZuA21AcdaSl:-NbUXFfDA7U6bwjGBye0:bw3n5ps) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L222)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so our integration tests don't use grpc again?
</blockquote></details>

Yes and we have a task to recover it, I explained it today.

**Review by miladz68 — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`infra/apps/cored/cored.go` line 222 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/267#-NbTn51iAZuA21AcdaSl:-NbUgTSx5XwfcuLfWHJz:b-lx4fj3) ([raw file](https://github.com/CoreumFoundation/crust/blob/86db93e77650a38cda9b1e7b0483abfd09b7c7f7/infra/apps/cored/cored.go#L222)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes and we have a task to recover it, I explained it today.
</blockquote></details>

Fixed.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
