### PR TITLE
Crosscompile `cored` for arm64

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/150#-NKNX-5-0z4xx5qkXeoX:-NKNX-5-0z4xx5qkXeoY:bta6a3f) (no related file):*
Let's discuss this PR after daily

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/release.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/150#-NKNd9DY67q9z-Kz3Vqr:-NKNd9DY67q9z-Kz3Vqs:b-dwgyfu) ([raw file](https://github.com/coreumfoundation/crust/blob/efed270d41c55503ce3fdb0c8c999f6c62fe6037/build/coreum/release.go#L38)):*
> ```Go
> 
> 	config.BinOutputPath = releaseARM64BinaryPath
> 	config.CrosscompileARM64 = true
> ```

I would go with the apparach where you set the `Arch` to compile, because when the `Cross compile ARM64` is flag so you can't compile for the `AMD` on none AMD machine. And in general it looks non-standard.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/release.go` line 33 at r1](https://reviewable.io/reviews/coreumfoundation/crust/150#-NKSwR6Z4tO2gAIJYBXC:-NKXJK1E3SAlFr3vZooB:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/efed270d41c55503ce3fdb0c8c999f6c62fe6037/build/coreum/release.go#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so if you run this from machine with ARM architecture it will fail on this step ? 
Or what is the behaviour ?

IMO we should return error here if smn tries to build cored release from unsupported machine
</blockquote></details>

Done.
___
*[`build/golang/Dockerfile.tmpl` line 5 at r1](https://reviewable.io/reviews/coreumfoundation/crust/150#-NKSvNek306Pcw8iCt1S:-NKXK-JW6HrDvpfQ7jht:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/efed270d41c55503ce3fdb0c8c999f6c62fe6037/build/golang/Dockerfile.tmpl#L5)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I would add a comment describing the magic done here
</blockquote></details>

Done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
