### PR TITLE
Security update github.com/opencontainers/runc to v1.1.2

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/51#-N9GehghE3QoU4mS9_mb:-N9GehghE3QoU4mS9_mc:b-qo9iir) (no related file):*
Could you share the approach you took to upgrade the dependency ?

___

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/51#-N9GehghE3QoU4mS9_mb:-N9Gf5-f5b8H3ffpcwtB:b-2js5vs) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Could you share the approach you took to upgrade the dependency ?
</blockquote></details>

@miladz68 
`go get -u github.com/opencontainers/runc@v1.1.2`

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/51#-N9GehghE3QoU4mS9_mb:-N9GmVcC6edAtSKwW55o:beuqlfm) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@miladz68 
`go get -u github.com/opencontainers/runc@v1.1.2`
</blockquote></details>

I wonder how it will workout since runc is an indirect dependency and upgrading that might affect the functionality of the packages that depend on it.

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/51#-N9GehghE3QoU4mS9_mb:-N9Gml5qExpGa9KXifrV:b-1beo58) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I wonder how it will workout since runc is an indirect dependency and upgrading that might affect the functionality of the packages that depend on it.
</blockquote></details>

let's see how the `ci` reacts :smile: 

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @xlab, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/51#-N9GehghE3QoU4mS9_mb:-N9GnxLD6iJ_iuDK6qUH:b-gf2h0g) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's see how the `ci` reacts :smile: 
</blockquote></details>

In theory this version change is only some fix, so should work

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @xlab)

**Pull request merged**
