### PR TITLE
Remove integration tests

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/44)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Review by miladz68 — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/44#-:-N8wvqHZCJScQo6PHkBX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/44#-N8wvf0Y2CE9-mr5pi7w:-N8wvf0Y2CE9-mr5pi7x:bqziiqx) (no related file):*
Looks good to me, but I will wait for @ysv to review it as well.

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/44)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/44#-N8wvf0Y2CE9-mr5pi7w:-N8wxk3aB_4A1rryP4Un:b-h5a03p) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Looks good to me, but I will wait for @ysv to review it as well.
</blockquote></details>

Setting my status to "Blocking" so it is not accidentally merged by me again until he reviews it.
@ysv Please give it a priority

___

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/44)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

**Pull request merged**
