### PR TITLE
Start znet with `cored-v1.0.0` so it's easier to test bdjuno with all versions of cored.

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/301)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/301)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 272 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/301#-Niiesv09EGmE3jnhkmM:-Niiesv09EGmE3jnhkmN:b-f6y3pt) ([raw file](https://github.com/CoreumFoundation/crust/blob/f67e2dc074c742797bc3ff33d30b5413eff9f458/build/tools/tools.go#L272)):*
> ```Go
> 	BinaryTool{
> 		Name:    CoredV100,
> 		Version: "v1.0.0",
> ```

Why did you update the `v2.0.2` instead of adding `v1.0.0` ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/301)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 272 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/301#-Niiesv09EGmE3jnhkmM:-NiifFkW7s97ovS9b1Dj:b-8cvbjn) ([raw file](https://github.com/CoreumFoundation/crust/blob/f67e2dc074c742797bc3ff33d30b5413eff9f458/build/tools/tools.go#L272)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why did you update the `v2.0.2` instead of adding `v1.0.0` ?
</blockquote></details>

Because v2.0.2 was duplicated on the list :D

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/301)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/301)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
