### PR TITLE
Set correct hash for go `1.22.4` version.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Set correct hash for go `1.22.4` version.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/424)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/424)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/424#-O45Ges30EFkGkm6Ac-V:-O45Ges44i-aW7TPaDh2:b-422bsc) ([raw file](https://github.com/CoreumFoundation/crust/blob/cab0a0a6b30ad21506b142d338488e8ffa0ee6ae/build/tools/tools.go#L74)):*
> ```Go
> 			TargetPlatformDarwinAMD64: {
> 				URL:  "https://go.dev/dl/go1.22.4.darwin-amd64.tar.gz",
> 				Hash: "sha256:7788f40f3a46f201df1dc46ca640403eb535d5513fc33449164a90dbd229b761",
> ```

It seems like the AMD one is also wrong. I calculate `c95967f50aa4ace34af0c236cbdb49a9a3e80ee2ad09d85775cb4462a5c19ed3`. Would you check it?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/424)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/424#-O45Ges30EFkGkm6Ac-V:-O45KUpI1NJgjV5r1lpq:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/crust/blob/cab0a0a6b30ad21506b142d338488e8ffa0ee6ae/build/tools/tools.go#L74)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It seems like the AMD one is also wrong. I calculate `c95967f50aa4ace34af0c236cbdb49a9a3e80ee2ad09d85775cb4462a5c19ed3`. Would you check it?
</blockquote></details>

Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/424)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/424#-:-O45dEbW89cLnEF6vXQt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/424)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
