### PR TITLE
`znet`: Integrate big dipper

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`infra/types.go` line 356 at r1](https://reviewable.io/reviews/coreumfoundation/crust/48#-N90UFUPC6rW-Yfg4hbX:-N90UFUPC6rW-Yfg4hbY:bxdq0mp) ([raw file](https://github.com/coreumfoundation/crust/blob/cda58c5dda920a28e3c7c3c6a5486f95dfa8fe26/infra/types.go#L356)):*
> ```Go
> // Volume is used to define mounted volume for docker container
> type Volume struct {
> 	From string
> ```

non-blocking
I am no docker expert, but don't they use `source`, `destination` for this ?
___
*[`infra/apps/bigdipper/bigdipper.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/crust/48#-N90VN5a6CIm7FfR56vN:-N90VN5a6CIm7FfR56vO:b-fij4yp) ([raw file](https://github.com/coreumfoundation/crust/blob/cda58c5dda920a28e3c7c3c6a5486f95dfa8fe26/infra/apps/bigdipper/bigdipper.go#L28)):*
> ```Go
> 	return BigDipper{
> 		name:        name,
> 		homeDir:     config.AppDir + "/" + name,
> ```

non-blocking
use `filepath.Join()`
___
*[`infra/apps/bigdipper/bigdipper.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/crust/48#-N90Vfcc1IJIelQ4TChQ:-N90Vfcc1IJIelQ4TChR:bjxpsly) ([raw file](https://github.com/coreumfoundation/crust/blob/cda58c5dda920a28e3c7c3c6a5486f95dfa8fe26/infra/apps/bigdipper/bigdipper.go#L69)):*
> ```Go
> 		Volumes: []infra.Volume{
> 			{
> 				From: bd.homeDir + "/env",
> ```

nonblocking.
use `filepath.Join()`

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`infra/types.go` line 356 at r1](https://reviewable.io/reviews/coreumfoundation/crust/48#-N90UFUPC6rW-Yfg4hbX:-N90leeG5ZSamsmTiFXi:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/cda58c5dda920a28e3c7c3c6a5486f95dfa8fe26/infra/types.go#L356)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
I am no docker expert, but don't they use `source`, `destination` for this ?
</blockquote></details>

Done
___
*[`infra/apps/bigdipper/bigdipper.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/crust/48#-N90VN5a6CIm7FfR56vN:-N90lbKjDY-FXnrtzotP:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/cda58c5dda920a28e3c7c3c6a5486f95dfa8fe26/infra/apps/bigdipper/bigdipper.go#L28)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
use `filepath.Join()`
</blockquote></details>

Done
___
*[`infra/apps/bigdipper/bigdipper.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/crust/48#-N90Vfcc1IJIelQ4TChQ:-N90lcj_BfjRGiyuhLCd:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/cda58c5dda920a28e3c7c3c6a5486f95dfa8fe26/infra/apps/bigdipper/bigdipper.go#L69)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

nonblocking.
use `filepath.Join()`
</blockquote></details>

Done

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
Yes, because I need new hasura image which doesn't exist yet

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48#-:-N9CG_Fj474YzeOrtS5b:b-brhygq)* status: all files reviewed, 4 unresolved discussions (waiting on @alinetskyi, @begmaroman, @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`infra/apps/bigdipper/bigdipper.go` line 67 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BwGIv4cKn4f92MX_P:-N9Gr3u770WWTyI3VJYU:bf8af94) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/bigdipper/bigdipper.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1.1 for now I'm ok to just push it to docker hub manually and put it here
</blockquote></details>

Ok, so I'm waiting until it is done
___
*[`infra/apps/bigdipper/bigdipper.go` line 68 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BxNha-zXyPXfDeGny:-N9GqjdNCPGYWIgpx815:b-43xk9s) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/bigdipper/bigdipper.go#L68)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would prefer to pass envs as envs (not file) here `docker run -e ...`
</blockquote></details>

Ah, yes - I prefer it too, I just thought that this is what next js requires because this is what our instruction says here: -dipper-2.0-cosmos

**Review by wojtek-coreum — COMMENTED** [review]
I will try to upgrade hasura metadata in znet for now so I see that big dipper works correctly

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48#-:-N9HDjUbA5_iQPULRXM4:bcdnncc)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`infra/apps/apps.go` line 78 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BydzG4-jifRMgWMmE:-N9HDbaSEXhWQJgV7eF-:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/apps.go#L78)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

applicable for other components here also

non blocking:
.New receives 6 arguments a bit too many if you ask me

Do you have some thought on better approach for this ? Maybe define bigdipper.Config struct ?
</blockquote></details>

Done
___
*[`infra/apps/bigdipper/bigdipper.go` line 68 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BxNha-zXyPXfDeGny:-N9HDflA8rKgGX1HELqq:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/bigdipper/bigdipper.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ah, yes - I prefer it too, I just thought that this is what next js requires because this is what our instruction says here: -dipper-2.0-cosmos
</blockquote></details>

Done.
___
*[`infra/apps/blockexplorer/bigdipper/env/env` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9By72Y1Znsmy35rnt5:-N9HDhwf-rbl6qL_2WVk:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/blockexplorer/bigdipper/env/env#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we decided to name go template files with `*.tmpl` suffix
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @alinetskyi, @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`infra/apps/bigdipper/bigdipper.go` line 67 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BwGIv4cKn4f92MX_P:-N9_oPGu65R3LtTx3Ejg:blgll45) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/bigdipper/bigdipper.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ok, so I'm waiting until it is done
</blockquote></details>

@ysv Now I remember that in previous company we had a problem using docker hub because of quota they apply on free accounts. This image might be pulled by any person in the world when using crust and we might eventually hit this.

**Review by ysv — DISMISSED** [review]
yes 
lets stick to the current approach since 90% is done here and I don't want to pause this PR just because of images & other devops stuff
 lets merge it as is now and once we have images ready we will migrate to use them

> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48#-:-N9aOzM77M_qREFq3SYA:bfxu1jx)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

___
*[`infra/apps/bigdipper/bigdipper.go` line 67 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BwGIv4cKn4f92MX_P:-N9aNFp33QEgeyVwLGJE:btmbcvj) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/bigdipper/bigdipper.go#L67)):*
yes but it is applied per user not per image as far as I understand

> Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. Pull rates limits are based on individual IP address. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For authenticated users, it is 200 pulls per 6 hour period. Users with a paid Docker subscription get up to 5000 pulls per day. If you require a higher number of pulls, you can also purchase an Enhanced Service Account add-on.

https://docs.docker.com/docker-hub/download-rate-limit/

> Ok, so I'm waiting until it is done

I'm resolving this discussion just add TODO here pls
Meanwhile I will work on setting up image storage on docker hub or quay.io for us

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

___
*[`infra/apps/bigdipper/bigdipper.go` line 67 at r2](https://reviewable.io/reviews/coreumfoundation/crust/48#-N9BwGIv4cKn4f92MX_P:-N9accKw8AMldaLLCEwP:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/5e50131d9640b1f3a623b07915460c17b5267d16/infra/apps/bigdipper/bigdipper.go#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes but it is applied per user not per image as far as I understand

> Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. Pull rates limits are based on individual IP address. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For authenticated users, it is 200 pulls per 6 hour period. Users with a paid Docker subscription get up to 5000 pulls per day. If you require a higher number of pulls, you can also purchase an Enhanced Service Account add-on.

https://docs.docker.com/docker-hub/download-rate-limit/

> Ok, so I'm waiting until it is done

I'm resolving this discussion just add TODO here pls
Meanwhile I will work on setting up image storage on docker hub or quay.io for us
</blockquote></details>

Done

**Review by ysv — APPROVED** [review]
works for both 1 & validatators for me 
Screenshot 2022-08-16 at 14.34.01

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48#-:-N9adJ6C9ZlHxffKJTAC:bv7nnyb)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 9 files at r1, 2 of 10 files at r3, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 2 of 6 files at r4, 1 of 1 files at r6, 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Pull request merged**
