### PR TITLE
Build docker images for `cored` and `faucet`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/docker/docker.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBm98qB47A0Dnud96ih:-NBm98qB47A0Dnud96ii:bigcchx) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/docker/docker.go#L38)):*
> ```Go
> 	logger.Get(ctx).Info("Building docker image", zap.String("binary", config.BinaryPath), zap.String("image", imageName))
> 
> 	dockerFile := fmt.Sprintf(`FROM alpine:3.16.0
> ```

If it's a remp solution I would agree, if not, better to use the dockerfile as file and provide build args to it.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmNQuEE_Pvp-LTK2C0:-NBmNQuF4Mmzk7SU9-Si:bc2oh3) (no related file):*
Talking about your question on using same/different dockerfiles to build binary
I suggest we split them because I expect to remove WASM from faucet in this sprint or the next one

___
___
*[`build/build.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmLykn60RxeUW-tXwC:-NBmLykn60RxeUW-tXwD:bvra94x) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/build.go#L25)):*
> ```Go
> }
> 
> func buildAllDockerImages(deps build.DepsFunc) {
> ```

what is the resulting docker image tag and how can I define/override it ?

I suggest tagging images like this for now: `gcr.io/coreum-devnet-1/cored:cad59fc` `gcr.io/coreum-devnet-1/faucet:ca08334`
where version is defined using commit sha

But I have concern on how we will fetch sha because binary might be build before and after this you pull a new version of repo so real binary is one version while git shows another one. Pls take this into account
___
*[`build/docker/docker.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBm98qB47A0Dnud96ih:-NBmKNWv0E4CGX2HJc2e:b4n3lej) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/docker/docker.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If it's a remp solution I would agree, if not, better to use the dockerfile as file and provide build args to it.
</blockquote></details>

yes I agree
Not acceptable for me also 

Either build args or use go template (Dockerfile.tmpl) & render before build 

But I prefer build args probably
___
*[`infra/apps/faucet/faucet.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmL1oq5kxI9BvwvjeY:-NBmL1oq5kxI9BvwvjeZ:b-n9gvbb) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/infra/apps/faucet/faucet.go#L99)):*
> ```Go
> func (f Faucet) Deployment() infra.Deployment {
> 	return infra.Binary{
> 		BinPath: f.config.BinDir + "/.cache/docker/faucet/faucet",
> ```

I don't like faucet/faucet & cored/cored repeated

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmNQuEE_Pvp-LTK2C0:-NBpR00YD75xnRJ3A6vF:b-scl877) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Talking about your question on using same/different dockerfiles to build binary
I suggest we split them because I expect to remove WASM from faucet in this sprint or the next one

</blockquote></details>

It's not related to removing WASM in any way. Binaries requiring wasm link this library statically, so they don't have any special requirements on the content of the image. You see that I build on top of pure `alpine` without adding any libraries there. Library must exist only in the image which builds them.

___
___
*[`build/build.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmLykn60RxeUW-tXwC:-NBpRPYt7j63nibXGzU6:bsh0fap) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/build.go#L25)):*
> I suggest tagging images like this for now

 ok

> But I have concern

Once PR is in master we will run github action building those images, so we have versions with correct tag
___
*[`build/docker/docker.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBm98qB47A0Dnud96ih:-NBpRj2g3VqzvD6Cozys:b-fzxfx8) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/docker/docker.go#L38)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes I agree
Not acceptable for me also 

Either build args or use go template (Dockerfile.tmpl) & render before build 

But I prefer build args probably
</blockquote></details>

ok, but I prefer template because later on I may set alpine version automatically based on some constant
___
*[`infra/apps/faucet/faucet.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmL1oq5kxI9BvwvjeY:-NBpS7Ge6CWMDzLgtJbe:b-kluw33) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/infra/apps/faucet/faucet.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like faucet/faucet & cored/cored repeated 
</blockquote></details>

I added this to limit the size of context sent to docker daemon when image is built. Each binary takes ~60MBs. So if directory contains both of them we send ~120MB twice (on each build) - in the future it will be worse. By putting them in separate dir I send only one file at a time. If you have an idea of better naming please propose. For me it's fine - we have a product called "faucet" containing "faucet" binary and we have a product called "cored" containing "cored" binary. The fact that product contains only one file which is named the same way is because the products accidentally don't need more files. IMO finding any other naming convention will create more issues than it solves, but if you have a good idea please propose it.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: 6 of 11 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/build.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmLykn60RxeUW-tXwC:-NBpc7cR5cJpC5ffDQfG:b4oha1d) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/build.go#L25)):*
> I suggest tagging images

Now, after thinking about it more I disagree. The difference between images built locally and those pulled from official repo should be clearly visible. So IMO images built locally shouln't be tagged with the url of our repo. Tagging them using that repo should be done only when they are pushed to the official repo.
___
*[`build/docker/docker.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBm98qB47A0Dnud96ih:-NBpc0Ib4YTpksAgq5u1:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/docker/docker.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ok, but I prefer template because later on I may set alpine version automatically based on some constant
</blockquote></details>

Done.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: 6 of 11 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmNQuEE_Pvp-LTK2C0:-NBqlCh4-TE2IsV3pVy4:b-fbnnq6) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not related to removing WASM in any way. Binaries requiring wasm link this library statically, so they don't have any special requirements on the content of the image. You see that I build on top of pure `alpine` without adding any libraries there. Library must exist only in the image which builds them.
</blockquote></details>

yes I understand 
I'm talking about crust/build/golang/go.go:96 (in current master version)
That there we currently mount WASM for both faucet & cored and we will change this behaviour soon to split logic between them

___
___
*[`build/build.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmLykn60RxeUW-tXwC:-NBqnB1P49JMQS1EPKyk:b-ia707o) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/build.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> I suggest tagging images

Now, after thinking about it more I disagree. The difference between images built locally and those pulled from official repo should be clearly visible. So IMO images built locally shouln't be tagged with the url of our repo. Tagging them using that repo should be done only when they are pushed to the official repo.
</blockquote></details>

to discuss:
1. how to build image for Artem ? We need to pass image prefix or smth like `--prod` to this cmd
2. image tag
3. binary build -> git pull -> image build
___
*[`build/docker/docker.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBm98qB47A0Dnud96ih:-NBqmEuC1Sjm9wGOzYJR:b-cuyhqq) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/docker/docker.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok for me
___
*[`infra/apps/faucet/faucet.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmL1oq5kxI9BvwvjeY:-NBqn4K6C9Pzaw7bN4U_:bcyd5t3) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/infra/apps/faucet/faucet.go#L99)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I added this to limit the size of context sent to docker daemon when image is built. Each binary takes ~60MBs. So if directory contains both of them we send ~120MB twice (on each build) - in the future it will be worse. By putting them in separate dir I send only one file at a time. If you have an idea of better naming please propose. For me it's fine - we have a product called "faucet" containing "faucet" binary and we have a product called "cored" containing "cored" binary. The fact that product contains only one file which is named the same way is because the products accidentally don't need more files. IMO finding any other naming convention will create more issues than it solves, but if you have a good idea please propose it.
</blockquote></details>

I thought that we copy only binaries itself not the whole folder 
Don't we ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmNQuEE_Pvp-LTK2C0:-NBqoVLQCCHnA_Ac5tW9:b32wtd) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes I understand 
I'm talking about crust/build/golang/go.go:96 (in current master version)
That there we currently mount WASM for both faucet & cored and we will change this behaviour soon to split logic between them
</blockquote></details>

ok

___
___
*[`build/build.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmLykn60RxeUW-tXwC:-NBqoaKe6TmvLe8vDJS8:bxcida6) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/build.go#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to discuss:
1. how to build image for Artem ? We need to pass image prefix or smth like `--prod` to this cmd
2. image tag
3. binary build -> git pull -> image build
</blockquote></details>

crust images `cored:<sha>` & `faucet:<sha>-dirty`
___
*[`infra/apps/faucet/faucet.go` line 99 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmL1oq5kxI9BvwvjeY:-NBqq0SYEUIIx1T2nU3k:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/infra/apps/faucet/faucet.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought that we copy only binaries itself not the whole folder 
Don't we ?
</blockquote></details>

ok

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

___
*[`build/build.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/crust/84#-NBmLykn60RxeUW-tXwC:-NBvnK9I5_QV5IqLM4Dk:b32wtd) ([raw file](https://github.com/coreumfoundation/crust/blob/4ce15f9c636436528f412a0ad85778dbba8cf8e9/build/build.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok

**Pull request merged**
