### PR TITLE
Allow to build the binary from the imported package

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/410)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

___
*[`build/tools/tools.go` line 1563 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/410#-O-5mWJH0fb2iQpX6-1j:-O-5mWJH0fb2iQpX6-1k:bjspmfy) ([raw file](https://github.com/CoreumFoundation/crust/blob/4c8e4d2d1d5112c61bcd4971bb76fefdf8d0fbd4/build/tools/tools.go#L1563)):*
> ```Go
> // CrustModule returns the name of crust module.
> func CrustModule() string {
> 	//nolint:dogsled // yes, there are 3 blanks and what?
> ```

the comment is weird :-)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

___
*[`build/tools/tools.go` line 1563 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/410#-O-5mWJH0fb2iQpX6-1j:-O-5wb_f4y8iVD_Duz-3:bck1kk0) ([raw file](https://github.com/CoreumFoundation/crust/blob/4c8e4d2d1d5112c61bcd4971bb76fefdf8d0fbd4/build/tools/tools.go#L1563)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

the comment is weird :-)
</blockquote></details>

because I have no idea what should I do about error saying that there are 3 blanks

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/410)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

___
*[`build/tools/tools.go` line 1563 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/410#-O-5mWJH0fb2iQpX6-1j:-O-AHFTwBxl_Bk0V6DFu:bf2sm29) ([raw file](https://github.com/CoreumFoundation/crust/blob/4c8e4d2d1d5112c61bcd4971bb76fefdf8d0fbd4/build/tools/tools.go#L1563)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

because I have no idea what should I do about error saying that there are 3 blanks
</blockquote></details>

you want to ignore the error, so the comment should just say that.

**Pull request merged**
