### PR TITLE
Version environments containing installed tools

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

We are moving toward building mechanism to be local to every repository.
The side effect of this design is that every repository (at least temporarily, until everything is aligned) might import different version of `crust `, containing different versions of tools.

It might happen e.g. when we upgrade tools. First we create a new commit in `crust`, and then we must create new commits in every repository to switch to that new `crust` version. It means that our system might use different versions of tools (e.g. `go`) at the same time.

Until now we use centralized setup where all the tools are linked to the same project-global location. It cannot work this way anymore.

This PR introduces versioned environments. Version is determined by the version of `crust/build` module imported by `build` module of every repository. All the tools are linked under the version directory.

Implemented solution has some pros:
- two repositories importing different `crust/build` versions may be built together, both locally and in CI, and each repository uses the right version of the tool, preventing conflicts and incompatibilities.
- two repositories using the same version of crust, reuse the same versioned linked tools
- if two repositories import different versions of crust, but both versions of crust use the same version of a tool (e.g. go), that tool is downloaded only once, and both versioned environments link to the same tool directory
- all the stuff follows these rules, e.g. configuration of golang linter, to prevent that linting rules imported by two repositories conflict.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/tools/tools.go` line 1583 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NmMN58f400fZ6ql35oz:-NmMN58f400fZ6ql35p-:bxs5ey4) ([raw file](https://github.com/CoreumFoundation/crust/blob/3d072edccc31a48a13e695e32187888fd3f62ac1/build/tools/tools.go#L1583)):*
> ```Go
> 		}
> 
> 		if m.Version == "(devel)" {
> ```

This happens in two cases:
- building is done in `crust` repository
- any other repository (currently only `coreum`)  has `go.mod` modified to replace `crust/build` with the local source code

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NmqAGpQ713d9rhZtgsi:-NmqAGpQ713d9rhZtgsj:b-k49e0t) (no related file):*
In general the idea is nice but not 100% clear lets discuss on a quick call

___

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`build/golang/lint.go` line 158 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NoXmNSWDQ_6rnLczzPW:-NoXmNSWDQ_6rnLczzPX:b-sprzgc) ([raw file](https://github.com/CoreumFoundation/crust/blob/d77f87591e5116d84edac7e0da4af3d0354700f3/build/golang/lint.go#L158)):*
> ```Go
> 
> func lintConfigPath() string {
> 	return filepath.Join(tools.VersionRootPath(tools.TargetPlatformLocal), "golangci.yaml")
> ```

nit: VersionedRootPath



_Code quote:_
```Go
VersionRootPath
```
___
*[`build/tools/tools.go` line 1583 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NmMN58f400fZ6ql35oz:-NoXokMj7Zgil3tT0o0R:blo2v7u) ([raw file](https://github.com/CoreumFoundation/crust/blob/3d072edccc31a48a13e695e32187888fd3f62ac1/build/tools/tools.go#L1583)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This happens in two cases:
- building is done in `crust` repository
- any other repository (currently only `coreum`)  has `go.mod` modified to replace `crust/build` with the local source code
</blockquote></details>

worth adding as comment inside code
___
*[`build/tools/tools.go` line 1567 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NoXlyS698t6v0FWznT7:-NoXlyS698t6v0FWznT8:b-5by7g1) ([raw file](https://github.com/CoreumFoundation/crust/blob/d77f87591e5116d84edac7e0da4af3d0354700f3/build/tools/tools.go#L1567)):*
> ```Go
> 
> // Version returns crust version.
> func Version() string {
> ```

how does it work ? 
It returns version of crust/build which is specified inside go.mod, doesn't it ?

Pls improve comment

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`build/tools/tools.go` line 1583 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NmMN58f400fZ6ql35oz:-Nol6KMZBcmL17bXprzz:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/3d072edccc31a48a13e695e32187888fd3f62ac1/build/tools/tools.go#L1583)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

worth adding as comment inside code
</blockquote></details>

Done.
___
*[`build/tools/tools.go` line 1567 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/339#-NoXlyS698t6v0FWznT7:-Nol6AC8-RIEq8bNryU6:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/d77f87591e5116d84edac7e0da4af3d0354700f3/build/tools/tools.go#L1567)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

how does it work ? 
It returns version of crust/build which is specified inside go.mod, doesn't it ?

Pls improve comment
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/339)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
