### PR TITLE
Add osmosis IBC testing flags

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/210#-NV_2Zka6RC9KiIZHpzO:-NV_2Zka6RC9KiIZHpzP:b718s1q) ([raw file](https://github.com/CoreumFoundation/crust/blob/3d6f6ed9d53fb6816d0b8c0874f38957fa31b3de/.github/workflows/ci.yml#L83)):*
> ```YAML
>           repository: CoreumFoundation/coreum
>           path: coreum
>           ref: dzmitryhil/burn-send-rate-ibc # FIXME remove once merged
> ```

you don't need this, you can use default values on coreum side, and once the coreum side is merged, introduce the flags here.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/210#-NV_2Zka6RC9KiIZHpzO:-NVcWNEME9mIKmfCS7Dl:b-pw6dk1) ([raw file](https://github.com/CoreumFoundation/crust/blob/3d6f6ed9d53fb6816d0b8c0874f38957fa31b3de/.github/workflows/ci.yml#L83)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, but I wanted to be sure that PR passes CI. I don't merge it, since waitonf for the coreum to be first. 
</blockquote></details>

I see, but there is no need to merge them into master with a FIXME right ?

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/210#-NV_2Zka6RC9KiIZHpzO:-NVcX15s-464QJ1xr5f1:bsvudb5) ([raw file](https://github.com/CoreumFoundation/crust/blob/3d6f6ed9d53fb6816d0b8c0874f38957fa31b3de/.github/workflows/ci.yml#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see, but there is no need to merge them into master with a FIXME right ?
</blockquote></details>

Remvoed.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
