### PR TITLE
use predefined network configs defined in coreum

### PR DESCRIPTION
**Pull request by miladz68**
Coreum repo will use predefined network configs to connect to different networks for a given chain-id. We want use this config in crust as well when we define our local networks. For now we will use devnet and over write genesis txs to get a new network.

NOTE: This PR is dependent on https://github.com/CoreumFoundation/coreum/pull/113, and cannot be merged before that.

---
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: all files reviewed, 22 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/znet/main.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NK5e-ASDjBsdhl4P-:-N8NK5e-ASDjBsdhl4P0:b-3ud6wi) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/cmd/znet/main.go#L22)):*
> ```Go
> 	network, err := app.NetworkByChainID(app.Devnet)
> 	must.OK(err)
> 	network.SetupPrefixes()
> ```

I would really prefer if `znet` (and `zstress`) didn't need to call `SetupPrefixes`. It might be achieved easily by providing a function which generates addresses based on token prefix stored in the `Network`, not globally set by cosmos sdk. It might be done in this PR or another one. I'm not blocking on this.
___
*[`cmd/znet/main.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NJy9RE2bzvq_vjjh5:-N8NJy9RE2bzvq_vjjh6:b-ysgt9u) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/cmd/znet/main.go#L24)):*
> ```Go
> 	network.SetupPrefixes()
> 	run.Tool("znet", znet.IoC, func(c *ioc.Container, configF *infra.ConfigFactory, cmdF *znet.CmdFactory) error {
> 		c.Singleton(func() app.Network {
> ```

move this to the `znet.IoC` function
___
*[`cmd/zstress/main.go` line 27 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NUlTI-E8ZqHRh4uwq:-N8NUlTI-E8ZqHRh4uwr:b23l9m9) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/cmd/zstress/main.go#L27)):*
> ```Go
> 
> func main() {
> 	network, err := app.NetworkByChainID(app.Mainnet)
> ```

I think Mainnet -> Devnet
___
*[`cmd/zstress/main.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NUuxG4EdVn5UGPxUL:-N8NUuxG4EdVn5UGPxUM:bo292z4) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/cmd/zstress/main.go#L65)):*
> ```Go
> 		rootCmd.Flags().IntVar(&stressConfig.NumOfTransactions, "transactions", 1000, "Number of transactions to send from each account")
> 
> 		var generateConfig zstress.GenerateConfig
> ```

maybe:

```go
generateConfig := zstress.GenerateConfig {
  Network: network,
}
```
___
*[`infra/apps/apps.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NL4Bk86z8_FadFq7h:-N8NL4Bk86z8_FadFq7i:b-yc6huv) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/apps.go#L28)):*
> ```Go
> 	config  infra.Config
> 	spec    *infra.Spec
> 	Network app.Network
> ```

this field should not be exported
___
*[`infra/apps/apps.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NQdVyDdDPFJG7dKJp:-N8NQdVzCuTgP0mji-Kj:b-wfxrzo) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/apps.go#L42)):*
> ```Go
> 		network.FundAccount(key.PubKey(), initialBalance)
> 	}
> 	network.ResetGenesisTxs()
> ```

I would prefer to just create a new `NetworkConfig` and then call `New` to get a network instead of doing this magic.
___
*[`infra/apps/cored/client.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NLm-PE8VcE_mAnAv3:-N8NLm-PE8VcE_mAnAv4:b-u95sdo) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/client.go#L131)):*
> ```Go
> 
> // ClientCtx returns client context
> func (c Client) ClientCtx() cosmosclient.Context {
> ```

why is it needed? It exposes cosmos-specific thing to the outside world
___
*[`infra/apps/cored/cored.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NMIesCyDKbjGmh9wI:-N8NMIesCyDKbjGmh9wJ:bmthmhx) ([raw file](https://github.com/coreumfoundation/crust/blob/8f07c0bf8b093f193575fa11c0df3790dc5b761d/infra/apps/cored/cored.go#L29)):*
> ```Go
> 
> // New creates new cored app
> func New(name string, config infra.Config, genesis *Genesis, appInfo *infra.AppInfo, ports Ports, validator bool, rootNode *Cored) Cored {
> ```

why `validator bool` is removed? It is a valid scenario to create a non-validator node for some manual tests from time to time
___
*[`infra/apps/cored/cored.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NP8bQ-2dNIy_LzNL4:-N8NP8bR8QIy1dQMP-6F:bzbgxcn) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L34)):*
> ```Go
> 
> // New creates new cored app
> func New(name string, cfg infra.Config, network *app.Network, appInfo *infra.AppInfo, ports Ports, rootNode *Cored) Cored {
> ```

why do you need a pointer for `network`?
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NMi5K2ufSqeIyRcQq:-N8NMi5K2ufSqeIyRcQr:bpzd85h) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L44)):*
> ```Go
> 	err = network.FundAccount(stakerPubKey, "100000000000000000000000"+network.TokenSymbol())
> 	must.OK(err)
> 	clientCtx := app.NewDefaultClientContext().WithChainID(string(network.ChainID()))
> ```

`clientCtx` introduces a cosmos type being used outside the client. Why isn't `clientCtx` stored internally by the client instead?
___
*[`infra/apps/cored/cored.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NPhtq3v5G_b1CHkVy:-N8NPhtr9APM6KkN85yD:bnftyy6) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L110)):*
> ```Go
> 
> // Network returns the network config used in the chain
> func (c Cored) Network() *app.Network {
> ```

why is it needed?
___
*[`infra/apps/cored/cored.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NQHv1A_YxtYQNbXC5:-N8NQHv1A_YxtYQNbXC6:b-k2cf6u) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L115)):*
> ```Go
> 
> // ChainID returns ID of the chain
> func (c Cored) ChainID() string {
> ```

this function should return `ChainID` type now
___
*[`infra/apps/cored/cored.go` line 147 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NPzu6A_MdhSGsQU5i:-N8NPzu6A_MdhSGsQU5j:b-9z958p) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L147)):*
> ```Go
> // Client creates new client for cored blockchain
> func (c Cored) Client() Client {
> 	return NewClient(string(c.network.ChainID()), infra.JoinNetAddr("", c.Info().HostFromHost, c.Ports().RPC))
> ```

`NewClient` should accept `ChainID` type now, not `string`
___
*[`infra/apps/cored/cored.go` line 232 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NR12fDVNrzZNkkT7m:-N8NR12fDVNrzZNkkT7n:b-k94ma4) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L232)):*
> ```Go
> 					ValidatorKey:   c.validatorPrivateKey,
> 				}
> 				SaveConfig(nodeConfig, c.homeDir)
> ```

Could `SaveConfig` and `AddKeysToStore` be unexported? Looks like no one else should use them
___
*[`pkg/znet/commands.go` line 222 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NRbGFDVO0dZ_SBMFM:-N8NRbGFDVO0dZ_SBMFN:b-vh7rel) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/znet/commands.go#L222)):*
> ```Go
> // PingPong connects to cored node and sends transactions back and forth from one account to another to generate
> // transactions on the blockchain
> func PingPong(ctx context.Context, mode infra.Mode) error {
> ```

This function should take `network` from IoC container (you added it there). Then `coredNode.Network()` is not needed
___
*[`pkg/znet/commands.go` line 253 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NRrMn-c-qMPRYUwoj:-N8NRrMn-c-qMPRYUwok:b-bazf1s) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/znet/commands.go#L253)):*
> ```Go
> 
> // Stress runs benchmark implemented by `zstress` on top of network deployed by `znet`
> func Stress(ctx context.Context, mode infra.Mode) error {
> ```

ditt, `network` should be taken from IoC container as an argument to this function
___
*[`pkg/znet/commands.go` line 286 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NS1Al3FYWMXjc4mPe:-N8NS1Al3FYWMXjc4mPf:bastwcf) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/znet/commands.go#L286)):*
> ```Go
> }
> 
> func sendTokens(ctx context.Context, client cored.Client, from, to types.Wallet, network *app.Network) error {
> ```

do you need a pointer for `network`?
___
*[`pkg/znet/mode.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NSHoM4pOJdFhijolH:-N8NSHoM4pOJdFhijolI:bko29sw) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/znet/mode.go#L11)):*
> ```Go
> 
> // DevMode is the environment for developer
> func DevMode(appF *apps.Factory) infra.Mode {
> ```

`apps.Factory` should take network from IoC as an argument to its constructor and pass it internally to cored object, not here
___
*[`pkg/zstress/generate.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NShTc8Dfnd4rYm-Ka:-N8NShTc8Dfnd4rYm-Kb:bjj2zvg) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/zstress/generate.go#L50)):*
> ```Go
> }
> 
> func nodeIDFromPubKey(pubKey ed25519.PublicKey) string {
> ```

function for getting node ID is already there: https://github.com/miladz68/crust/blob/milad/use_coreum_genesis_config/infra/apps/cored/node.go#L11
___
*[`pkg/zstress/generate.go` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NTHPWEVdD1mIHeGj3:-N8NTHPWEVdD1mIHeGj4:b-mnrx5n) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/zstress/generate.go#L69)):*
> ```Go
> 
> 	network := cfg.Network
> 	clientCtx := app.NewDefaultClientContext().WithChainID(string(network.ChainID()))
> ```

`clientCtx` should not be used outside client
___
*[`pkg/zstress/generate.go` line 87 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NTNsh1510fPC30gF9:-N8NTNsh1510fPC30gFA:b-pvqdhw) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/zstress/generate.go#L87)):*
> ```Go
> 			ValidatorKey:   validatorPrivateKey,
> 		}
> 		cored.SaveConfig(nodeConfig, valDir)
> ```

forgot setting `err`?
___
*[`pkg/zstress/generate.go` line 130 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NTflP1j32DO5xEofO:-N8NTflP1j32DO5xEofP:b-pvqdhw) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/pkg/zstress/generate.go#L130)):*
> ```Go
> 			NodeKey:        nodePrivateKey,
> 		}
> 		cored.SaveConfig(nodeConfig, nodeDir)
> ```

forgot setting `err`?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`infra/apps/apps.go` line 34 at r2](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8Or5bt-INMYHnE1JTI:-N8Or5bt-INMYHnE1JTJ:b-drty3c) ([raw file](https://github.com/coreumfoundation/crust/blob/5f7de05d9143a627c1d78a24931e979e06845e6e/infra/apps/apps.go#L34)):*
> ```Go
> // CoredNetwork creates new network of cored nodes
> func (f *Factory) CoredNetwork(name string, numOfValidators int, numOfSentryNodes int) infra.Mode {
> 	network := f.network
> ```

Technically it's a valid use case to create two independent blockchains in a single `znet` deployment. We will probably use it in the future to develop IBC. It means that `CoredNetwork` might be called twice, and each call should operate using it's own network.
Here you reference the same network all the time, which means same accounts (Alice, Bob, Charlie, RandomWallets) might be added to the same network twice creating a mess (funded accounts are stored in slice internally, and the same reference is used by all the copies).

I think you should store NetworkConfig in the Factory and call `NewNetwork` here every time, to create a fresh Network.
___
*[`infra/apps/apps.go` line 44 at r2](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8OqmWD5y8Ey2UN3qRU:-N8OqmWE7Wl--uOiRD61:b3ubob3) ([raw file](https://github.com/coreumfoundation/crust/blob/5f7de05d9143a627c1d78a24931e979e06845e6e/infra/apps/apps.go#L44)):*
> ```Go
> 		must.OK(network.FundAccount(key.PubKey(), initialBalance))
> 	}
> 	// network.ResetGenesisTxs()
> ```

Do you need this commented line for anything or is it a leftover?
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NMi5K2ufSqeIyRcQq:-N8OuquSCgd9lHS9OcI8:b-yboc86) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that is a valid piont but is related to the coreum repo. will make another PR to fix it in coreum repo.
</blockquote></details>

Please leave a FIXME here and in the other place

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: all files reviewed, 3 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`infra/apps/apps.go` line 34 at r2](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8Or5bt-INMYHnE1JTI:-N8P28rI7YjSbB9RE0ex:bcpfluj) ([raw file](https://github.com/coreumfoundation/crust/blob/5f7de05d9143a627c1d78a24931e979e06845e6e/infra/apps/apps.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Technically it's a valid use case to create two independent blockchains in a single `znet` deployment. We will probably use it in the future to develop IBC. It means that `CoredNetwork` might be called twice, and each call should operate using it's own network.
Here you reference the same network all the time, which means same accounts (Alice, Bob, Charlie, RandomWallets) might be added to the same network twice creating a mess (funded accounts are stored in slice internally, and the same reference is used by all the copies).

I think you should store NetworkConfig in the Factory and call `NewNetwork` here every time, to create a fresh Network.
</blockquote></details>

Done.
However this fix does not fully resolve the issue. It is better to leave it here and revisit this issue when the use case arises.
___
*[`infra/apps/apps.go` line 44 at r2](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8OqmWD5y8Ey2UN3qRU:-N8P0Yhv44QHPytN6Gz-:b-aqggaf) ([raw file](https://github.com/coreumfoundation/crust/blob/5f7de05d9143a627c1d78a24931e979e06845e6e/infra/apps/apps.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you need this commented line for anything or is it a leftover?
</blockquote></details>

it is left over, removed.
___
*[`infra/apps/cored/cored.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8NMi5K2ufSqeIyRcQq:-N8P13PBBmfpXuwicgdj:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/cde1664c17d697defe1b0f9487621565e665b693/infra/apps/cored/cored.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please leave a FIXME here and in the other place
</blockquote></details>

Done.



_Code quote:_
```Go
NewDefaultClientContext()
```

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`infra/apps/apps.go` line 34 at r2](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8Or5bt-INMYHnE1JTI:-N8S5kmN4q6VeUSZ6oF8:b-3xyabq) ([raw file](https://github.com/coreumfoundation/crust/blob/5f7de05d9143a627c1d78a24931e979e06845e6e/infra/apps/apps.go#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
However this fix does not fully resolve the issue. It is better to leave it here and revisit this issue when the use case arises.
</blockquote></details>

What's the problem?
___
*[`infra/apps/apps.go` line 17 at r3](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8S5ZTY2fC9UNKFtO8z:-N8S5ZTY2fC9UNKFtO9-:byxts48) ([raw file](https://github.com/coreumfoundation/crust/blob/bebd2810e32bd51857705681ca21a7203f9c974d/infra/apps/apps.go#L17)):*
> ```Go
> 
> // NewFactory creates new app factory
> func NewFactory(config infra.Config, spec *infra.Spec, network app.NetworkConfig) *Factory {
> ```

network -> networkConfig
___
*[`pkg/znet/setup.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8S6DxbEnSrWoBZ4FGB:-N8S6DxbEnSrWoBZ4FGC:b-siq2ht) ([raw file](https://github.com/coreumfoundation/crust/blob/bebd2810e32bd51857705681ca21a7203f9c974d/pkg/znet/setup.go#L23)):*
> ```Go
> func IoC(c *ioc.Container) {
> 	c.Singleton(func() app.NetworkConfig {
> 		app.NewNetwork(cored.CustomZNetNetworkConfig).SetupPrefixes()
> ```

Please add a FIXME saying that this is a temporary hack until we add our own address encoder. I will do it once fee model is done.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: all files reviewed, 3 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`infra/apps/apps.go` line 34 at r2](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8Or5bt-INMYHnE1JTI:-N8SW53_7zYwp9j1uj2K:b-kr6b1e) ([raw file](https://github.com/coreumfoundation/crust/blob/5f7de05d9143a627c1d78a24931e979e06845e6e/infra/apps/apps.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What's the problem?
</blockquote></details>

there is still the global config that packages use.
___
*[`infra/apps/apps.go` line 17 at r3](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8S5ZTY2fC9UNKFtO8z:-N8SYCQ14t90jarV-WRQ:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/bebd2810e32bd51857705681ca21a7203f9c974d/infra/apps/apps.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

network -> networkConfig
</blockquote></details>

Done.
___
*[`pkg/znet/setup.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8S6DxbEnSrWoBZ4FGB:-N8SWanR7vWptWX6PUtK:bs7wumb) ([raw file](https://github.com/coreumfoundation/crust/blob/bebd2810e32bd51857705681ca21a7203f9c974d/pkg/znet/setup.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please add a FIXME saying that this is a temporary hack until we add our own address encoder. I will do it once fee model is done.
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30#-:-N8SdmJ82yWcuz8zQUVo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`tests/bank/gas.go` line 77 at r6](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8Tn9m7-VYc67cGLmW-:-N8Tn9m7-VYc67cGLmW0:b58t1wb) ([raw file](https://github.com/coreumfoundation/crust/blob/70d820114e04f2dd66e85c9fe4b70a3f11386a3b/tests/bank/gas.go#L77)):*
> ```Go
> // TestTransferFailsIfNotEnoughGasIsProvided checks that transfer fails if not enough gas is provided
> func TestTransferFailsIfNotEnoughGasIsProvided(chain cored.Cored) (testing.PrepareFunc, testing.RunFunc) {
> 	maxGasAssumed := chain.Network().DeterministicGas().BankSend // set it to 50%+ higher than maximum observed value
> ```

please remove the comment from this line. Looks like I blindly copied it from another test, but it doesn't make sense here

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/bank/gas.go` line 77 at r6](https://reviewable.io/reviews/coreumfoundation/crust/30#-N8Tn9m7-VYc67cGLmW-:-N8TqnIe8003uV4pNftl:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/70d820114e04f2dd66e85c9fe4b70a3f11386a3b/tests/bank/gas.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please remove the comment from this line. Looks like I blindly copied it from another test, but it doesn't make sense here
</blockquote></details>

Done.



_Code quote:_
```Go
 TestTransferFailsIfNotEnoughGasIsProvided
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 9 of 25 files at r1, 3 of 13 files at r2, 3 of 6 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 5 of 7 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas and @xlab)

**Pull request merged**
