### PR TITLE
Introduce application profiles to `znet`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This PR is created on top of #141 because of some breaking changes introduced there. Once that PR is merged, this one will target the master.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: 0 of 15 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`README.md` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICmlbB-5-J7BCWMx7Y:-NICmlbB-5-J7BCWMx7Z:b83s34i) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L67)):*
> ```Markdown
> Each environment is independent, you may create many of them and work with them in parallel.
> 
> ### --profiles
> ```

Clean the local cache (/Users/<user>/crust/bin/.cache/) and run

```bash
crust znet start --profiles=3cored
```

I got the error:

```bash
Application returned error: open /Users/<user>/crust/bin/.cache/docker/cored-upgrade/cored-upgrade: no such file or directory 
```

I know that I need to build images first, but there is a check in the code that builds if not built, which ignores it. Is it expected? 
___
*[`README.md` line 69 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICknyD7KUuO1dODYc-:-NICknyD7KUuO1dODYc0:bcz90fv) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L69)):*
> ```Markdown
> ### --profiles
> 
> Defines the list of available application profiles to run. Available profiles:
> ```

It would be nice to have that full example of the build or start with the profile.
___
*[`README.md` line 70 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICj3pdEGf-TNaxk0Sj:-NICj3pdEGf-TNaxk0Sk:byuvsmj) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L70)):*
> ```Markdown
> 
> Defines the list of available application profiles to run. Available profiles:
> - 1cored - runs one cored validator (default one)
> ```

Maybe `scale-cored=5` additional flag?
In the case it's not a profile it just a additional option.
___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NICltxJ2bcHJfYpP09C:b-ew048m) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
> ```Go
> )
> 
> var availableProfiles = map[string]bool{
> ```

Why do you need bool here?
___
*[`infra/apps/profiles.go` line 66 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICnVfbDpH6cd5ugTMn:-NICnVfbDpH6cd5ugTMo:b-v9cpz4) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L66)):*
> ```Go
> 	if pMap["integration-tests"] {
> 		if pMap["1cored"] {
> 			return nil, errors.Errorf("profile 1cored can't be used together with integration-tests as it requires 3cored")
> ```

Why do we need that check?
___
*[`infra/apps/profiles.go` line 104 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICndQQCkdhT_hsoRif:-NICndQQCkdhT_hsoRig:b-37t851) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L104)):*
> ```Go
> 	}
> 
> 	if pMap["ibc"] || pMap["integration-tests"] {
> ```

I guess we don't need to run the `ibc` for the tests now since we don't have such tests.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`README.md` line 70 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICj3pdEGf-TNaxk0Sj:-NIH6Kuk2HisHm8z-gW6:b6wt27f) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Maybe `scale-cored=5` additional flag?
In the case it's not a profile it just a additional option.
</blockquote></details>

I don't see any use case for having any other number than 1 or 3

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`README.md` line 69 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICknyD7KUuO1dODYc-:-NIHIDAw74NeG3hJ8wE0:b-7tdf7d) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L69)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to have that full example of the build or start with the profile.
</blockquote></details>

agree
___
*[`README.md` line 70 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICj3pdEGf-TNaxk0Sj:-NIHIFI08HK_e2Um_-pB:bouxecb) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see any use case for having any other number than 1 or 3
</blockquote></details>

what about such approach: `profiles="cored=4,faucet,ibc"` doesn't look perfect but more or less logical
As for other number than 3 it is actually needed in some rare cases eg. Artem has a task to test jailing and for this he had to kill 1 validator but if we leave 2/3 they will not be able to reach quorum so he needs 4 for this. 
If we wan't to implement this feature fully I think number should be accepted here also

This wils also help if we want to run full IBC setup with e.g 3 gaiad & 3 cored nodes
___
*[`README.md` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIHEuHuD5aKDBTEljkP:-NIHEuHuD5aKDBTEljkQ:b-ncxecy) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L75)):*
> ```Markdown
> - explorer - runs block explorer
> - ibc - runs setup for testing IBC with coreum, gaia and relayer between them
> - integration-tests - runs setup required by integration tests (3cored, faucet and ibc)
> ```

I think we don't have any integration tests for IBC yet maybe we can disable it for now on integration-tests or at least make optional ?
Because my main intention was to have minimalistic setup for integration-tests because current one is too heavy IMO
___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NIHLSp09Vjv3wudrMFj:bmme4ld) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need bool here?
</blockquote></details>

I also do not understand why we need map but not a slice of available profiles. What is more we convert it to slice later.

IMO it should be smth like this:

```golang
type Profile string

const (
  ProfileFaucet Profile = "faucet"
  ProfileExplorer Profile = "explorere"
  ...
)

var availableProfiles = []string{ProfileFaucet, ProfileExplorer, ...}
```
___
*[`infra/apps/profiles.go` line 51 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIHNlGL4DOX7oNgfLwI:-NIHNlGL4DOX7oNgfLwJ:bxo60gl) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L51)):*
> ```Go
> 
> // BuildAppSet builds the application set to deploy based on provided profiles
> func BuildAppSet(appF *Factory, profiles []string) (infra.AppSet, error) {
> ```

IMO logic in this func is too hardcoded I suggest doing it differently
Here is the main idea but it might be not clear so we can discuss on the call:


```golang
type ProfileApp struct {
  appType AppType
  replicas int
  // other configs from cli could be added later if needed 
}

var profileDefinitions = map[ProfileName][]ProfileDefinition{
  ProfileExplorer = []ProfileDefinition{{appType: hasura.AppType, replicas: 1}, {appType: bigdipper.AppType, replicas: 1}}
 ///  ...
}

// And then in `BuildAppSet` you just need to iterate through all profile definitions and unite them
func BuildAppSet(appF *Factory, profiles []string) (infra.AppSet, error) {
  appReplicas := map[AppType]int
  
for profile := range profiles {
    profileDefinitions := profileDefinitions[profile]
    for profileApp := range profileDefinitions {
       // The only question here is how we want to handle different num of replicas. I propose to use max number
       appReplicas[profileApp.appType] = profileApp.replicas
     }
  }
  
var appSet infra.AppSet
// initialize appSet from appReplicas

coredApp, coredNodes, err = appF.CoredNetwork("cored", cored.DefaultPorts, appReplicas[cored.ApplicationType], 0)
// ...
}
```

we can discuss on the call
___
*[`infra/apps/profiles.go` line 105 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIHeST76B1tT5AxJhDj:-NIHeST9-XcXlirF0Fnh:b-4eazp5) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L105)):*
> ```Go
> 
> 	if pMap["ibc"] || pMap["integration-tests"] {
> 		gaiaApp := appF.Gaia("gaiad")
> ```

minor:
should it be gaia or gaiad since we have cored

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`README.md` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICmlbB-5-J7BCWMx7Y:-NIWDIwl-ms_qB9LUeiI:bl9apc6) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L67)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Clean the local cache (/Users/<user>/crust/bin/.cache/) and run

```bash
crust znet start --profiles=3cored
```

I got the error:

```bash
Application returned error: open /Users/<user>/crust/bin/.cache/docker/cored-upgrade/cored-upgrade: no such file or directory 
```

I know that I need to build images first, but there is a check in the code that builds if not built, which ignores it. Is it expected? 
</blockquote></details>

`znet` does not build stuff, you need to run crust first
___
*[`README.md` line 69 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICknyD7KUuO1dODYc-:-NIWDjC28zrppTYzKmM4:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L69)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.
___
*[`README.md` line 70 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICj3pdEGf-TNaxk0Sj:-NIWGICL9nxyn0RRdh-K:b-jzp8qp) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about such approach: `profiles="cored=4,faucet,ibc"` doesn't look perfect but more or less logical
As for other number than 3 it is actually needed in some rare cases eg. Artem has a task to test jailing and for this he had to kill 1 validator but if we leave 2/3 they will not be able to reach quorum so he needs 4 for this. 
If we wan't to implement this feature fully I think number should be accepted here also

This wils also help if we want to run full IBC setup with e.g 3 gaiad & 3 cored nodes
</blockquote></details>

I'm not sure if we should care. My original idea behind crust was that, if you need a super-special one time environment to do one thing you will never repeat, it's better to just go to the source code, modify one number and be happy instead of flooding user interface/CLI with tons of options which are needed for 0.1% of time
___
*[`README.md` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIHEuHuD5aKDBTEljkP:-NIWDqZq8kB9TrnsHJPM:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we don't have any integration tests for IBC yet maybe we can disable it for now on integration-tests or at least make optional ?
Because my main intention was to have minimalistic setup for integration-tests because current one is too heavy IMO
</blockquote></details>

Done.
___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NIWE2GT7ttj2wqVXE5q:b6c4g9r) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also do not understand why we need map but not a slice of available profiles. What is more we convert it to slice later.

IMO it should be smth like this:

```golang
type Profile string

const (
  ProfileFaucet Profile = "faucet"
  ProfileExplorer Profile = "explorere"
  ...
)

var availableProfiles = []string{ProfileFaucet, ProfileExplorer, ...}
```
</blockquote></details>

Map is there to not iterate over slice many times to verify that all requested profiles are defined
___
*[`infra/apps/profiles.go` line 51 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIHNlGL4DOX7oNgfLwI:-NIWF4f1BZ4I1jkRDkXC:b-9a0lpn) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO logic in this func is too hardcoded I suggest doing it differently
Here is the main idea but it might be not clear so we can discuss on the call:


```golang
type ProfileApp struct {
  appType AppType
  replicas int
  // other configs from cli could be added later if needed 
}

var profileDefinitions = map[ProfileName][]ProfileDefinition{
  ProfileExplorer = []ProfileDefinition{{appType: hasura.AppType, replicas: 1}, {appType: bigdipper.AppType, replicas: 1}}
 ///  ...
}

// And then in `BuildAppSet` you just need to iterate through all profile definitions and unite them
func BuildAppSet(appF *Factory, profiles []string) (infra.AppSet, error) {
  appReplicas := map[AppType]int
  
for profile := range profiles {
    profileDefinitions := profileDefinitions[profile]
    for profileApp := range profileDefinitions {
       // The only question here is how we want to handle different num of replicas. I propose to use max number
       appReplicas[profileApp.appType] = profileApp.replicas
     }
  }
  
var appSet infra.AppSet
// initialize appSet from appReplicas

coredApp, coredNodes, err = appF.CoredNetwork("cored", cored.DefaultPorts, appReplicas[cored.ApplicationType], 0)
// ...
}
```

we can discuss on the call
</blockquote></details>

I'm against during it this way. It's not that simple because there are many interdependencies. E.g. faucet requires `cored or 3cored but integration test requires faucet and 3cored. You can't provide a universal way of defining that some apps require at least one cored but other requires at least 3 - but for that requiring 1, 3 is also fine.

Second thing: defining replicas for stuff like hasura, big dipper etc. makes no sense because if you try to run two, you will get port conflicts.

So instead of trying to define yet-another magic syntax to do it in declarative way I prefer to have function with simple ifs we all understand, constructing setup we need
___
*[`infra/apps/profiles.go` line 66 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICnVfbDpH6cd5ugTMn:-NIWG-B9D8WhMIrl9vVJ:brpsccj) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L66)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need that check?
</blockquote></details>

because integration-tests must be run with 3cored to detect non-deterministic logic inside transactions.
___
*[`infra/apps/profiles.go` line 104 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICndQQCkdhT_hsoRif:-NIWG9_w9alxWysGx5Bj:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L104)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I guess we don't need to run the `ibc` for the tests now since we don't have such tests. 
</blockquote></details>

Done.
___
*[`infra/apps/profiles.go` line 105 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIHeST76B1tT5AxJhDj:-NIWGCGrCeJq45AxmyW5:bux2xbb) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L105)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
should it be gaia or gaiad since we have cored
</blockquote></details>

probably gaiad but removed anyway for now

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NIXXAq5AUti6DOPl-WN:b-9owwad) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Map is there to not iterate over slice many times to verify that all requested profiles are defined
</blockquote></details>

My point is - why `true`, why not `struct{}{}`?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NIXj0AY1_ZhbYjDjaPq:b-fqz81y) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

My point is - why `true`, why not `struct{}{}`?
</blockquote></details>

to be able to write `if someMap["key"] {`

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`README.md` line 70 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICj3pdEGf-TNaxk0Sj:-NIY8S5BEc9FMWFVTP3W:b-aifwb2) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would agree with you if support of different number of nodes required full implementation than It wouldn't make sense. But currently crust supports it fully on all levels except CLI which is quite easy to add. What is more doing it in cored={number} instead of hardcoded way 1cored, 3cored looks more elegant and brings more flexibility and is easy to implement IMO

the probability of running different number of cored nodes is not that low. It is required from time to time:

Final decision: `1cored, 3cored, 5cored`
</blockquote></details>

first part of the comment is irrelevant only this should be referenced: 
**Final decision: 1cored, 3cored, 5cored**

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`README.md` line 70 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICj3pdEGf-TNaxk0Sj:-NIaLZweC_NZb9ejadYo:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/README.md#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

first part of the comment is irrelevant only this should be referenced: 
**Final decision: 1cored, 3cored, 5cored**
</blockquote></details>

Done.
___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NIaKgfT-eyqtXyzxd8R:b-wswoft) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok then it should be like this IMO.

1. `[]string profileList` is a primary data struct while `availableProfiles map` is just a helper
So `availableProfiles map` should be initialized from `profileList` slice

2. There is also a trick to use struct{} in such maps where value is not really needed because struct {} requires 0 memory. Not really critical here but still might be beneficial

3. Side question: what is the complexity of reading from map in golang ? 



</blockquote></details>

Ad. 1. Done

Ad. 2. Changed to `struct{}{}` in `availableProfiles` but kept bools in `pMap` due to simpler `&&` and `||` comparison. It really doesn't matter in case of maps of this size.

Ad. 3. It's a matter of probability - how often you hit the result in hashmap in first shot. If you do, then it's close O(1). Here is the article I read some time ago: https://dave.cheney.net/2018/05/29/how-the-go-runtime-implements-maps-efficiently-without-generics
___
*[`infra/apps/profiles.go` line 94 at r5](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIXZqQeARC1zoKeuCow:-NIaHj4K6Ca6qHzjxiMo:bihjz4v) ([raw file](https://github.com/coreumfoundation/crust/blob/e733d41f63102bf3a6fdbe3d83cb49afc26ec2fb/infra/apps/profiles.go#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need this check ?
</blockquote></details>

In our case it's not needed but I would keep it for completeness, if one day we will add app which doesn't require cored

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`infra/apps/profiles.go` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/crust/142#-NICltxJ2bcHJfYpP09B:-NIbabM49CIdvRgf7atM:bo1b4y5) ([raw file](https://github.com/coreumfoundation/crust/blob/4b7e1f0ceb5954958416d44e2733fa75d91379ea/infra/apps/profiles.go#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad. 1. Done

Ad. 2. Changed to `struct{}{}` in `availableProfiles` but kept bools in `pMap` due to simpler `&&` and `||` comparison. It really doesn't matter in case of maps of this size.

Ad. 3. It's a matter of probability - how often you hit the result in hashmap in first shot. If you do, then it's close O(1). Here is the article I read some time ago: https://dave.cheney.net/2018/05/29/how-the-go-runtime-implements-maps-efficiently-without-generics
</blockquote></details>

2. makes sense
3. Thanks for the article. The explanation is quite good
___
*[`infra/apps/profiles.go` line 94 at r5](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIXZqQeARC1zoKeuCow:-NIbbmiS-9tnLawZqKuq:bfcbyvs) ([raw file](https://github.com/coreumfoundation/crust/blob/e733d41f63102bf3a6fdbe3d83cb49afc26ec2fb/infra/apps/profiles.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In our case it's not needed but I would keep it for completeness, if one day we will add app which doesn't require cored
</blockquote></details>

minor:

maybe we should do it like this for now:
```
if nubOfCoredValidators <= 0 {
  return error...
}

// write all logic inside if numOfCoredValidators > 0 without if
```

Because currently it doesn't really make sense and coredApp is passed to almost all components so having nil there is unexpected
___
*[`infra/apps/profiles.go` line 34 at r6](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIbbMMeAb55eQzn7blZ:-NIbbMMeAb55eQzn7bl_:b95idb9) ([raw file](https://github.com/coreumfoundation/crust/blob/b2a488635e3c54c40301e3bc056263125949948d/infra/apps/profiles.go#L34)):*
> ```Go
> 
> var availableProfiles = func() map[string]struct{} {
> 	v := map[string]struct{}{}
> ```

minor:
you can prealocate map size with `make(map..., len(profiles))`
___
*[`infra/apps/profiles.go` line 59 at r6](https://reviewable.io/reviews/coreumfoundation/crust/142#-NIbbUAH085Z1I2Nz51n:-NIbbUAH085Z1I2Nz51o:b-2wm7og) ([raw file](https://github.com/coreumfoundation/crust/blob/b2a488635e3c54c40301e3bc056263125949948d/infra/apps/profiles.go#L59)):*
> ```Go
> func BuildAppSet(appF *Factory, profiles []string) (infra.AppSet, error) {
> 	pMap := map[string]bool{}
> 	var coredProfilePresent bool
> ```

minor:
can you please explicitly set vars in such cases: `coredProfilePresent := false`

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
