### PR TITLE
Remove deprecated network config and use genesis generator instead

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/378)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/378)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/378)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`infra/apps/profiles.go` line 155 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/378#-NtWf07o6RdqjTev0Zb_:-NtWf07o6RdqjTev0Zba:bu0l8ra) ([raw file](https://github.com/CoreumFoundation/crust/blob/082d941e5065b91e5171013ba85e8348a933f77d/infra/apps/profiles.go#L155)):*
> ```Go
> 			BankBalances: []banktypes.Balance{
> 				{
> 					Address: "devcore1ckuncyw0hftdq5qfjs6ee2v6z73sq0urd390cd",
> ```

to whom does this address belong ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/378)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`infra/apps/profiles.go` line 155 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/378#-NtWf07o6RdqjTev0Zb_:-Nt_KApH8_M-fGAN3Cx8:b-bttoee) ([raw file](https://github.com/CoreumFoundation/crust/blob/082d941e5065b91e5171013ba85e8348a933f77d/infra/apps/profiles.go#L155)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to whom does this address belong ?
</blockquote></details>

Added comment

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/378)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
