### PR TITLE
Add wasm module to bdjuno config template.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/253)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/253)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @vertex451)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/253)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/253#-NaHyJBl1hpT0_n4EY05:-NaepRR366RXSzzUYn-v:b-5tv1qo) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we also bump bdjuno version ?
</blockquote></details>

We use `latest` in the crust.

___

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
