### PR TITLE
Add ledger support

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/171)

### CODE REVIEW

**Review by ysv — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
