### PR TITLE
run faucet integration tests

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`build/build.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC7jOy2VXEcKaoDEFp:-NBC7jOy2VXEcKaoDEFq:by83786) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/build/build.go#L21)):*
> ```Go
> 
> func buildAllIntegrationTests(deps build.DepsFunc) {
> 	deps(buildCoreumIntegrationTests)
> ```

```go
deps(buildCoreumIntegrationTests, buildCoreumIntegrationTests)
```
___
*[`cmd/znet/main.go` line 59 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC7slgDvuqg324wnGy:-NBC7slh068gCc9VYleN:b3215u9) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/cmd/znet/main.go#L59)):*
> ```Go
> 			RunE:  cmdF.Cmd(znet.Test()),
> 		}
> 		testCmd.AddCommand(&cobra.Command{
> ```

Non-blocking: I would still prefer to have a flag to specify as many modules as I want to instead of having separate subcommands
___
*[`infra/testing/run.go` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC87kyA0GD37sKfC_C:-NBC87kyA0GD37sKfC_D:bhno3jf) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/infra/testing/run.go#L74)):*
> ```Go
> 	}
> 
> 	coredArgs := []string{
> ```

you could create a map:

```go
flags := map[string][]string{
  "coreum": ...
  "faucet": ...
}
```

and later get the right flags from map based on the name of executable file with integration test - it would eliminate the `switch`
___
*[`infra/testing/run.go` line 76 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC8Ops4wHvfZ-bPHPo:-NBC8Ops4wHvfZ-bPHPp:b-5pqj49) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/infra/testing/run.go#L76)):*
> ```Go
> 	coredArgs := []string{
> 		"-log-format", config.LogFormat,
> 		"-cored-address", infra.JoinNetAddr("", coredNode.Info().HostFromHost, coredNode.Ports().RPC),
> ```

here it's `-cored-address`, in faucet it is `-nodeURI`, please unify them
___
*[`infra/testing/run.go` line 81 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC8WAZ3xHhps0i2ohf:-NBC8WAZ3xHhps0i2ohg:b-eibxeo) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/infra/testing/run.go#L81)):*
> ```Go
> 
> 	faucetArgs := []string{
> 		"-nodeURI", "localhost:26657",
> ```

camel-case: `-node-uri`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`build/build.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC7jOy2VXEcKaoDEFp:-NBCWLsY-xINCy-uIT6B:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/build/build.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

```go
deps(buildCoreumIntegrationTests, buildCoreumIntegrationTests)
```
</blockquote></details>

Done.
___
*[`cmd/znet/main.go` line 59 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC7slgDvuqg324wnGy:-NBCiQsM6DzrEghv9HyR:bb6un1j) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/cmd/znet/main.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: I would still prefer to have a flag to specify as many modules as I want to instead of having separate subcommands
</blockquote></details>

Done
___
*[`infra/testing/run.go` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC87kyA0GD37sKfC_C:-NBCc-AQ24r4tezpvvjX:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/infra/testing/run.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you could create a map:

```go
flags := map[string][]string{
  "coreum": ...
  "faucet": ...
}
```

and later get the right flags from map based on the name of executable file with integration test - it would eliminate the `switch`
</blockquote></details>

Done.
___
*[`infra/testing/run.go` line 76 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC8Ops4wHvfZ-bPHPo:-NBCcWHr4214GtbRrRMj:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/infra/testing/run.go#L76)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

here it's `-cored-address`, in faucet it is `-nodeURI`, please unify them
</blockquote></details>

Done.
___
*[`infra/testing/run.go` line 81 at r1](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBC8WAZ3xHhps0i2ohf:-NBCcXcT2shc8_OWFY-1:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/1d34610bce70f00daa5e983f379af53229e8620b/infra/testing/run.go#L81)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

camel-case: `-node-uri`
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`cmd/znet/main.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNS0iDq7tOqvs10ut:-NBGNS0iDq7tOqvs10uu:b5gft1v) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/cmd/znet/main.go#L91)):*
> ```Go
> 		"repos",
> 		[]string{},
> 		"repos to run integration test for,empty means all repos,e.g. --repos=faucet,coreum or --repos=faucet --repos=coreum",
> ```

repos -> Repositories
___
*[`infra/types.go` line 422 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNaeS5dtr87XTSPva:-NBGNaeS5dtr87XTSPvb:b2nicf1) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/types.go#L422)):*
> ```Go
> 	TestFilter string
> 
> 	// TestRepos limits running integration tests on sp
> ```

sp?
___
*[`infra/testing/run.go` line 77 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNntkDGHOmzcAdM2o:-NBGNntkDGHOmzcAdM2p:bn30h76) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L77)):*
> ```Go
> 	appArgs := map[string][]string{
> 		"coreum": {
> 			"-log-format", config.LogFormat,
> ```

Could faucet tests also print logs in this format? We look at those logs only when sth fails and it's more friendly if there are encoded in yaml
___
*[`pkg/znet/commands.go` line 170 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGObaf23QXgZrMwzy0:-NBGObaf23QXgZrMwzy1:bvobjmf) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/pkg/znet/commands.go#L170)):*
> ```Go
> 		}
> 
> 		return testing.Run(ctx, target, mode, config, configF.TestRepos...)
> ```

TestRepos should be set in `config`.
The idea is like this:
1. `configF` is passed using pointer everywhere so its content might be set by application
2. then, based on `configF`, `config` is created which is a processed and frozen version of `configF` passed everywhere by value

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/testing/run.go` line 80 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGmh7qBXRj69HTlo8T:-NBGmh7qBXRj69HTlo8U:b-9dypyq) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L80)):*
> ```Go
> 			"-priv-key", base64.RawURLEncoding.EncodeToString(fundingPrivKey),
> 		},
> 		"faucet": {
> ```

please don't assume that faucet runs on default port in znet. Take a look how it is done for `-cored-address` using `mode.FindAnyRunningApp` above

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`cmd/znet/main.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNS0iDq7tOqvs10ut:-NBGm1zgDbFkXRauc37Z:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/cmd/znet/main.go#L91)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

repos -> Repositories
</blockquote></details>

Done.
___
*[`infra/types.go` line 422 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNaeS5dtr87XTSPva:-NBGmEP27FoR9JOgnBfj:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/types.go#L422)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

sp?
</blockquote></details>

Done.
___
*[`infra/testing/run.go` line 77 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNntkDGHOmzcAdM2o:-NBGmR3b7bRPRYJ4BNEe:b64wopu) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could faucet tests also print logs in this format? We look at those logs only when sth fails and it's more friendly if there are encoded in yaml
</blockquote></details>

I don't think that they can, all test logs are printed with assert package and i see no option to set a logger for that.
___
*[`infra/testing/run.go` line 80 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGmh7qBXRj69HTlo8T:-NBGnpDO2BdnOTeicVth:b-q9ex8b) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L80)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please don't assume that faucet runs on default port in znet. Take a look how it is done for `-cored-address` using `mode.FindAnyRunningApp` above
</blockquote></details>

I have used the same value as for the coreum integration test, So it is not assuming default value. 
___
*[`pkg/znet/commands.go` line 170 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGObaf23QXgZrMwzy0:-NBGncpPAL7XZkN57lJW:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/pkg/znet/commands.go#L170)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

TestRepos should be set in `config`.
The idea is like this:
1. `configF` is passed using pointer everywhere so its content might be set by application
2. then, based on `configF`, `config` is created which is a processed and frozen version of `configF` passed everywhere by value
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/testing/run.go` line 77 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNntkDGHOmzcAdM2o:-NBGo5325YUcKhkyJ6gw:b8l5cs9) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L77)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think that they can, all test logs are printed with assert package and i see no option to set a logger for that.
</blockquote></details>

If faucet test does not provide their own logs using zap, then this flag is not needed at all because it's zap-specific, `go test` framework doesn't use it
___
*[`infra/testing/run.go` line 80 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGmh7qBXRj69HTlo8T:-NBGoSn27CzA4bj7tmrG:bp1n5gp) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have used the same value as for the coreum integration test, So it is not assuming default value. 
</blockquote></details>

I mean `-faucet-address` should be set here

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`infra/testing/run.go` line 77 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNntkDGHOmzcAdM2o:-NBGpWC77AH7-WnVV7Nr:b-i9vdnj) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L77)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If faucet test does not provide their own logs using zap, then this flag is not needed at all because it's zap-specific, `go test` framework doesn't use it
</blockquote></details>

and I am not passing it to faucet, only to coreum. 
___
*[`infra/testing/run.go` line 80 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGmh7qBXRj69HTlo8T:-NBGrne-AaDPcXLXGqH2:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/infra/testing/run.go#L80)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean `-faucet-address` should be set here
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`cmd/znet/main.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNS0iDq7tOqvs10ut:-NBGyB1u4vwLlFN8Idmp:bz3frly) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/cmd/znet/main.go#L91)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I also meant starting with capital letter
___
*[`pkg/znet/commands.go` line 161 at r3](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGyrcqBB3uTKcd1405:-NBGyrcqBB3uTKcd1406:b83icxb) ([raw file](https://github.com/coreumfoundation/crust/blob/49f1086f08fa8b1c4f6a2b675f796b96205400c7/pkg/znet/commands.go#L161)):*
> ```Go
> 	var err error
> 	c.Call(func(ctx context.Context, config infra.Config, target infra.Target, mode infra.Mode, spec *infra.Spec) (retErr error) {
> 		config.TestRepos = append(config.TestRepos, configF.TestRepos...)
> ```

This should be done in `NewConfig` in `pkg/znet/setup.go`

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`cmd/znet/main.go` line 91 at r2](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGNS0iDq7tOqvs10ut:-NBHbfAf7sisNEqtIZQG:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/b946a0ebe04968e35197870f007762e7438b66a1/cmd/znet/main.go#L91)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I also meant starting with capital letter
</blockquote></details>

Done.
___
*[`pkg/znet/commands.go` line 161 at r3](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBGyrcqBB3uTKcd1405:-NBHcQXeDDJgmwil4KKD:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/49f1086f08fa8b1c4f6a2b675f796b96205400c7/pkg/znet/commands.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This should be done in `NewConfig` in `pkg/znet/setup.go`
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`pkg/znet/setup.go` line 87 at r4](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBHhU_uBwYdHB0Ufxmp:-NBHhU_uBwYdHB0Ufxmq:buyvz3m) ([raw file](https://github.com/coreumfoundation/crust/blob/4157cf909023b86c29d11bb3d38bd5b373ec4787/pkg/znet/setup.go#L87)):*
> ```Go
> 
> 	// we use append to make a copy of the original list, so it is not passed by reference
> 	config.TestRepos = append(config.TestRepos, configF.TestRepos...)
> ```

`config.TestRepos = append([]string{}, configF.TestRepos...)`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`pkg/znet/setup.go` line 87 at r4](https://reviewable.io/reviews/coreumfoundation/crust/78#-NBHhU_uBwYdHB0Ufxmp:-NBHkWHfE2LyAzynMp-p:b-896fix) ([raw file](https://github.com/coreumfoundation/crust/blob/4157cf909023b86c29d11bb3d38bd5b373ec4787/pkg/znet/setup.go#L87)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`config.TestRepos = append([]string{}, configF.TestRepos...)`
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 5 files at r2, 3 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 5 files at r2, 3 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Pull request merged**
