### PR TITLE
Update cosmovisor to v1.5.0

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 258 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPCG490R6S6D3arHE-:-NbPCG490R6S6D3arHE0:b-dh6kp) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/infra/apps/cored/cored.go#L258)):*
> ```Go
> 				},
> 				{
> 					Name:  "DAEMON_SHUTDOWN_GRACE",
> ```

During the call we discussed that we want to set it to 1m
But then I found that this env defines time for graceful shutdown of node **in case of upgrade only** 

cosmos-sdk/tools/cosmovisor/process.go:122


Screenshot 2023-08-09 at 14.12.15


Here is the PR: https://github.com/cosmos/cosmos-sdk/pull/16963
Do we want to keep the same value ?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`build/tools/tools.go` line 438 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPDKPR9B00o_30-r8R:-NbPDKPR9B00o_30-r8S:b-h9au93) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/build/tools/tools.go#L438)):*
> ```Go
> 	toolDir := toolDir(tool, platform)
> 	for dst, src := range lo.Assign(info.Binaries, source.Binaries) {
> 		// todo: IMO in this loop we should also verify that checksum of binary matches & if it doesn't - reinstall it.
> ```

WDYT @wojtek-coreum @dzmitryhil @miladz68 ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 438 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPDKPR9B00o_30-r8R:-NbPICHJAqDjwmeVted-:b2mhilr) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/build/tools/tools.go#L438)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

WDYT @wojtek-coreum @dzmitryhil @miladz68 ?
</blockquote></details>

make sence 
___
*[`infra/apps/cored/cored.go` line 258 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPCG490R6S6D3arHE-:-NbPILjc5q-gmILviM3K:b-geku7b) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/infra/apps/cored/cored.go#L258)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

During the call we discussed that we want to set it to 1m
But then I found that this env defines time for graceful shutdown of node **in case of upgrade only** 

cosmos-sdk/tools/cosmovisor/process.go:122


Screenshot 2023-08-09 at 14.12.15


Here is the PR: https://github.com/cosmos/cosmos-sdk/pull/16963
Do we want to keep the same value ?
</blockquote></details>

But the node stops itslef for the upgrade.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`build/tools/tools.go` line 438 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPDKPR9B00o_30-r8R:-NbPUixd-5_denLL7yUL:bt5lj5o) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/build/tools/tools.go#L438)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

make sence 
</blockquote></details>

We don't keep the checksums of individual files
___
*[`build/tools/tools.go` line 439 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPUtLA8J3rpY8BmrYl:-NbPUtLA8J3rpY8BmrYm:b-db8roa) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/build/tools/tools.go#L439)):*
> ```Go
> 	for dst, src := range lo.Assign(info.Binaries, source.Binaries) {
> 		// todo: IMO in this loop we should also verify that checksum of binary matches & if it doesn't - reinstall it.
> 		// If I'm not mistaken, crust wasn't downloading new cosmovisor binary when I changed version in tools.
> ```

It should do this. Whenever version is upgraded it downloads new one
___
*[`infra/apps/cored/cored.go` line 258 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPCG490R6S6D3arHE-:-NbPV9DX3Jvj9LRJOqbz:bmcfpd8) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/infra/apps/cored/cored.go#L258)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But the node stops itslef for the upgrade.
</blockquote></details>

I think it might be some legacy

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`build/tools/tools.go` line 438 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPDKPR9B00o_30-r8R:-NbQm1qa6XKOuFYeiUOw:bl642bz) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/build/tools/tools.go#L438)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We don't keep the checksums of individual files
</blockquote></details>

I see
We keep checksum of archive file

I wish it worked like this but ok
___
*[`build/tools/tools.go` line 439 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPUtLA8J3rpY8BmrYl:-NbQm9-o52ZxArhrrRdc:bnkauht) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/build/tools/tools.go#L439)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should do this. Whenever version is upgraded it downloads new one
</blockquote></details>

Tested and seems to work properly
___
*[`infra/apps/cored/cored.go` line 258 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPCG490R6S6D3arHE-:-NbQmeNR4f4eBtRxaZzt:b80jewv) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/infra/apps/cored/cored.go#L258)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think it might be some legacy
</blockquote></details>

from the PR:
```
Backend storage pebbledb needs a few seconds to flush async writes to disk.

Is graceful shutdown request before kill acceptable?

Make grace time configurable?
```

So I'm not sure

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`infra/apps/cored/cored.go` line 258 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPCG490R6S6D3arHE-:-NbTmByQ9uKImOMWtIbY:b1jkjtr) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/infra/apps/cored/cored.go#L258)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

from the PR:
```
Backend storage pebbledb needs a few seconds to flush async writes to disk.

Is graceful shutdown request before kill acceptable?

Make grace time configurable?
```

So I'm not sure
</blockquote></details>

Whenever upgrade should happen cosmos sdk emits panic and application exits. Whatever graceful shutdown is required it is implemented inside sdk (or not)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`infra/apps/cored/cored.go` line 258 at r2](https://reviewable.io/reviews/CoreumFoundation/crust/258#-NbPCG490R6S6D3arHE-:-NbU7X9R8X3y5gdUwgo5:b16nx5b) ([raw file](https://github.com/CoreumFoundation/crust/blob/3a9ce01bcca058e1f680928797c34384ba33e389/infra/apps/cored/cored.go#L258)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Whenever upgrade should happen cosmos sdk emits panic and application exits. Whatever graceful shutdown is required it is implemented inside sdk (or not)
</blockquote></details>

removed this env
I dont think we need it

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @vertex451)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
