### PR TITLE
Upgrade tools

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

alpine:3.18.4
go:1.21.4
golangci:1.55.2
gaia:13.0.2
osmosis:20.2.1
hermes:1.7.1
buf:1.28.0
protoc:25.0
grafana:10.2.1
postgres:16.1
prometheus:2.47.2
xrpld:1.12.0

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/306#-NjHz3TrEpiYEQnNSzPD:-NjHz3TrEpiYEQnNSzPE:blb4cad) (no related file):*
So many dependencies changed ..
Do we need to make some extra testing before we merge or it should be fine ?

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`infra/apps/xrpl/xrpl.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/306#-NjI07RIB0PDyNK2Omlr:-NjI07RIB0PDyNK2Omls:b-z0lfjp) ([raw file](https://github.com/CoreumFoundation/crust/blob/712a633649fc5b50b623230c86b9469d39f519ef/infra/apps/xrpl/xrpl.go#L140)):*
> ```Go
> 	return infra.Deployment{
> 		RunAsUser: true,
> 		Image:     "xrpllabsofficial/xrpld:1.12.0",
> ```

Did you test the XRPL ?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`infra/apps/xrpl/xrpl.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/306#-NjI07RIB0PDyNK2Omlr:-NjI09vP1P7oUtDnxmat:bo4i2x7) ([raw file](https://github.com/CoreumFoundation/crust/blob/712a633649fc5b50b623230c86b9469d39f519ef/infra/apps/xrpl/xrpl.go#L140)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you test the XRPL ?
</blockquote></details>

Does it work with the current run script?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/306#-NjHz3TrEpiYEQnNSzPD:-NjIFqzSCzHITS1eA4zi:btu4ai6) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

So many dependencies changed ..
Do we need to make some extra testing before we merge or it should be fine ?
</blockquote></details>

Nope, tests pass. All is fine.

___
___
*[`infra/apps/xrpl/xrpl.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/306#-NjI07RIB0PDyNK2Omlr:-NjIGrDLAz81J155wjLo:b1y2l10) ([raw file](https://github.com/CoreumFoundation/crust/blob/712a633649fc5b50b623230c86b9469d39f519ef/infra/apps/xrpl/xrpl.go#L140)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it work with the current run script?
</blockquote></details>

yes, it produces blocks

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
