### PR TITLE
Move cross compiling stuff from dockerfile to `tools`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR is it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264)

### CODE REVIEW

**Review by vertex451 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by ysv — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/tools/tools.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/264#-NbPHFR0940igPhi6WLw:-NbPHFR0940igPhi6WLx:b-y2nglk) ([raw file](https://github.com/CoreumFoundation/crust/blob/96df48ba10d9e885a24d51619ae6d1a76ae6fe4c/build/tools/tools.go#L145)):*
> ```Go
> 	// http://musl.cc/#binaries
> 	Aarch64LinuxMuslCross: {
> 		Version: "11.2.1",
> ```

q: is this version somehow connected to `libwasmvm_muslc` ?
Or they are completely independent ?

**Review by dzmitryhil — COMMENTED** [review]
Could you try to create a temp release to check that it works fine?

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264#-:-NbPIhNd0FS0uqdYbFB8:b26ndd7)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
We need a tag for this

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264#-:-NbPSwsNCGZJdq6T3lMZ:bx5emjb)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`build/tools/tools.go` line 145 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/264#-NbPHFR0940igPhi6WLw:-NbPT-qNE6wYyANHlZn7:b-zfrlwr) ([raw file](https://github.com/CoreumFoundation/crust/blob/96df48ba10d9e885a24d51619ae6d1a76ae6fe4c/build/tools/tools.go#L145)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

q: is this version somehow connected to `libwasmvm_muslc` ?
Or they are completely independent ?
</blockquote></details>

independent

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
