### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by vertex451**
I added clarification about running crust for the first time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/crust/140#-NHxnYsJ1ZNLiQ3Cd84d:-NHxnYsJ1ZNLiQ3Cd84e:b-3mmi3m) ([raw file](https://github.com/coreumfoundation/crust/blob/9fc726001323fcff4fc0f5166f988f5cce104fb7/README.md#L17)):*
> ```Markdown
> 
> ```
> ./bin/crust build images
> ```

Better to add the line on how to add it to the path, and remove the next line about it.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/crust/140#-NHxnYsJ1ZNLiQ3Cd84d:-NHy5Y8qD4LtWtzkSQyn:b-jslxf4) ([raw file](https://github.com/coreumfoundation/crust/blob/9fc726001323fcff4fc0f5166f988f5cce104fb7/README.md#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Better to add the line on how to add it to the path, and remove the next line about it.
</blockquote></details>

You can add the $HOME by default and add the remark, that if the location is different change it. That's it :-)
Or use the $PWD for example. But you will need to update the both repos this and coreum. 
If you just add the instruction similar to the coreum that would be fair enough,  IMHO.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 13 at r2](https://reviewable.io/reviews/coreumfoundation/crust/140#-NI0sFQZ5tSUJQLloqWk:-NI0sFQZ5tSUJQLloqWl:b-ipb6be) ([raw file](https://github.com/coreumfoundation/crust/blob/9983f3b4714d741e8676f305499f5a029578180e/README.md#L13)):*
> ```Markdown
> 
> ## Building
> 1. Clone repo to your `$HOME` directory:
> ```

Well it does not have to be HOME directory, any directory will work.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`README.md` line 13 at r2](https://reviewable.io/reviews/coreumfoundation/crust/140#-NI0sFQZ5tSUJQLloqWk:-NI1IysV5wVDU9d7ezIb:b1j2d67) ([raw file](https://github.com/coreumfoundation/crust/blob/9983f3b4714d741e8676f305499f5a029578180e/README.md#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Well it does not have to be HOME directory, any directory will work. 
</blockquote></details>

This is the copy/paste from the coreum.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`README.md` line 13 at r2](https://reviewable.io/reviews/coreumfoundation/crust/140#-NI0sFQZ5tSUJQLloqWk:-NI1J5--9dSMWcL3iry5:b9kaloh) ([raw file](https://github.com/coreumfoundation/crust/blob/9983f3b4714d741e8676f305499f5a029578180e/README.md#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is the copy/paste from the coreum. 
</blockquote></details>

And next command expect "export PATH="$HOME/crust/bin:$PATH"" it to be in the home



_Code quote:_
```Markdown
export PATH="$HOME/crust/bin:$PATH"
```

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/crust/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

___
*[`README.md` line 13 at r2](https://reviewable.io/reviews/coreumfoundation/crust/140#-NI0sFQZ5tSUJQLloqWk:-NI1ViWMDhjRmrqg6CPE:b-nfqz7f) ([raw file](https://github.com/coreumfoundation/crust/blob/9983f3b4714d741e8676f305499f5a029578180e/README.md#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

And next command expect "export PATH="$HOME/crust/bin:$PATH"" it to be in the home
</blockquote></details>

I see, but I think both places should be fixed then. I will mark it as resolved, but we should keep it in mind.

**Pull request merged**
