### PR TITLE
Add cored-darwin binary client to the cored release.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add cored-darwin binary client to the cored release.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/coreum/build.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI040aDzBjwxNkEw8y:-NjI040b1Ww4628Jc0To:bxmv9d) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/coreum/build.go#L93)):*
> ```Go
> }
> 
> // buildCoredClientInDocker builds cored binary without the wasm VM and with CGO enabled. The result binary might be
> ```

with CGO disabled, right ?



_Code quote:_
```Go
with CGO enabled
```
___
*[`build/coreum/build.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjIa0fp49Xp5_r9dscB:-NjIa0fp49Xp5_r9dscC:btb7ch9) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/coreum/build.go#L106)):*
> ```Go
> 		Platform:       platform,
> 		PackagePath:    "../coreum/cmd/cored",
> 		BinOutputPath:  filepath.Join("bin", ".cache", binaryName, platform.String(), "bin", fmt.Sprintf("%s-client", binaryName)),
> ```

nit:



client-only would be a bit more descriptive IMO
___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI2lEh8KysNQZdziAy:-NjI2lEh8KysNQZdziAz:bjx6leo) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
> ```Go
> 	PlatformLinuxAMD64InDocker     = Platform{InDocker: true, OS: OSLinux, Arch: "amd64"}
> 	PlatformLinuxARM64InDocker     = Platform{InDocker: true, OS: OSLinux, Arch: "arm64"}
> 	PlatformLinuxLocalArchInDocker = Platform{InDocker: true, OS: OSLinux, Arch: runtime.GOARCH}
> ```

looks a bit confusing & complicated now

Maybe we can change Platform struct to smth like
```
type Platform struct {
  BuildOS string
  TargetOS string
  TargetArch string
}
```
But I'm not sure that it looks like platform then. It becomes some kind of build rule.
Maybe it should consist of BuildPlatform & TargetPlatfrom both of which has OS & Arch inside.

Or at least `InDocker` -> `BuildInDocker bool`

There are multiple options so Lets discuss
___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjIbRQd5nkxwULicGy3:-NjIbRQd5nkxwULicGy4:b-fxjnix) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
> ```Go
> 	PlatformLinuxAMD64InDocker     = Platform{InDocker: true, OS: OSLinux, Arch: "amd64"}
> 	PlatformLinuxARM64InDocker     = Platform{InDocker: true, OS: OSLinux, Arch: "arm64"}
> 	PlatformLinuxLocalArchInDocker = Platform{InDocker: true, OS: OSLinux, Arch: runtime.GOARCH}
> ```

PlatformLinuxLocalArchInDocker - don't like this name. Lets discuss

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/coreum/build.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI040aDzBjwxNkEw8y:-NjMHh5s2Z5gphkEbAoY:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/coreum/build.go#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

with CGO disabled, right ?
</blockquote></details>

Done.
___
*[`build/coreum/build.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjIa0fp49Xp5_r9dscB:-NjMHh_zDy2J2eBhHj9F:b-zhbfgf) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/coreum/build.go#L106)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit:



client-only would be a bit more descriptive IMO
</blockquote></details>

IMO better without the `only`, since with `only` and without the sense remains the same.
___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI2lEh8KysNQZdziAy:-NjMHvNOA2Smp5ZPkU4A:b9l6q45) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

looks a bit confusing & complicated now

Maybe we can change Platform struct to smth like
```
type Platform struct {
  BuildOS string
  TargetOS string
  TargetArch string
}
```
But I'm not sure that it looks like platform then. It becomes some kind of build rule.
Maybe it should consist of BuildPlatform & TargetPlatfrom both of which has OS & Arch inside.

Or at least `InDocker` -> `BuildInDocker bool`

There are multiple options so Lets discuss
</blockquote></details>

The `BuildOS` is not correct in terms of usage.  Agree with `BuildInDocker``, updated. 
___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjIbRQd5nkxwULicGy3:-NjMIEN7E_DeYpTuBqSt:bf3lfie) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

PlatformLinuxLocalArchInDocker - don't like this name. Lets discuss
</blockquote></details>

Ok, let discuss

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/coreum/build.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjIa0fp49Xp5_r9dscB:-NjMmLoDCa2FtUDYbx5P:b-5s06zv) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/coreum/build.go#L106)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO better without the `only`, since with `only` and without the sense remains the same.
</blockquote></details>

The issue with current naming is that when I see cored & cored-client
It seems like cored is binary to run node & cored-client is smth completely different which contains client
___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI2lEh8KysNQZdziAy:-NjMmhKD1LXcGJOkmdaJ:b-zih945) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `BuildOS` is not correct in terms of usage.  Agree with `BuildInDocker``, updated.
</blockquote></details>

`BuildInDocker` is better but lets have a quick discussion

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/coreum/build.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjIa0fp49Xp5_r9dscB:-NjNKmeC7x3vNCppqAe3:b2yb939) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/coreum/build.go#L106)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

The issue with current naming is that when I see cored & cored-client
It seems like cored is binary to run node & cored-client is smth completely different which contains client
</blockquote></details>

IMO `only` doesn't give you more clarity.  
___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI2lEh8KysNQZdziAy:-NjNKtI95YXyYyWIq9zB:b32w0x) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`BuildInDocker` is better but lets have a quick discussion
</blockquote></details>

OK

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI2lEh8KysNQZdziAy:-NjNdEPxEJZhkZBpDpno:b-1u15xw) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Decided to rename Platform to TargetPlatform

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: 5 of 27 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/tools/tools.go` line 467 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/307#-NjI2lEh8KysNQZdziAy:-NjNfP-YBuSo-K-TGc3d:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/1373a49a2b0e22f6ffd91f77170279933a519382/build/tools/tools.go#L467)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Decided to rename Platform to TargetPlatform
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by ysv — DISMISSED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 18 of 22 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
