### PR TITLE
Simplify test groups

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-NrKI7hk9kkFm23obFdv:biug12f) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
> ```Go
> 	TestGroupCoreumIBC                 = "coreum-ibc"
> 	TestGroupFaucet                    = "faucet"
> 	TestGroupCoreumBridgeXRPLContract  = "coreumbridge-xrpl-contract"
> ```

IMO we don't need the test goups for the bridge at all. The bridge runs all tests himself, so no need for crust to build and run it.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-NrKIQeV20XztEzjBjGk:b-52ii5m) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we don't need the test goups for the bridge at all. The bridge runs all tests himself, so no need for crust to build and run it.
</blockquote></details>

This will be the new command to run bridge tests:
```
crust znet --test-groups=coreumbridge-xrpl-contract
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-NrKJ15pAkGloaFtN6XP:b-xn4osy) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This will be the new command to run bridge tests:
```
crust znet --test-groups=coreumbridge-xrpl-contract
```
</blockquote></details>

This task is about bringing our standard building system to bridge: https://app.clickup.com/t/8687dy4q2

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-NrL-G_HAweEsS6hE9zf:b-1sm1cq) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This task is about bringing our standard building system to bridge: https://app.clickup.com/t/8687dy4q2
</blockquote></details>

IMO we should stop doint that here as well :-)
That's the repo specific thing

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-NrL3yPC8hvRMfamOeT5:b3eprjo) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we should stop doint that here as well :-)
That's the repo specific thing
</blockquote></details>

I agree we should not run bridge tests with znet

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-Nr_ERKPAx6NS946AvhM:b-qmg8d1) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree we should not run bridge tests with znet
</blockquote></details>

also discussed this on call and agreed to not run these tests with znet

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`infra/testing/run.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/365#-NrKI7hk9kkFm23obFdu:-Nslavwn4tKDJqEpadFJ:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/5177b78834e60acf9dac2bdeb01d85ba89a0b1ba/infra/testing/run.go#L32)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

also discussed this on call and agreed to not run these tests with znet
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/365)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
