### PR TITLE
Don't recompile wasm contracts if they are already complied and there are no changes.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 90 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3Bia8C4WIBhsMrY7W:-NY3Bia9BQlX-rfDtuyC:byxsba4) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L90)):*
> ```Go
> 		absPathHash := fmt.Sprintf("%x", sha256.Sum256([]byte(codeDirAbsPath)))
> 
> 		storedCodeHashes := make(map[string]string, 0)
> ```

You don't need 0
___
*[`build/coreum/wasm.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3CkR4ETLRfQRn5bRR:-NY3CkR4ETLRfQRn5bRS:b-2bak6u) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L97)):*
> ```Go
> 			}
> 
> 			storedHash, ok := storedCodeHashes[absPathHash]
> ```

Compute hash of the dir to compare only if item does not exist in the map
___
*[`build/coreum/wasm.go` line 126 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3DRvWCtJSFPoWtYtf:-NY3DRvWCtJSFPoWtYtg:b-begesv) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L126)):*
> ```Go
> 		}
> 
> 		newCodeHash, err := computeContractCodeHash(codeDirAbsPath)
> ```

here you don't need to compute the hash of all files, only artifacts:
1. at the beginning of the function compute hash of src and artifacts separately
2. join those two hashes into a single one
3. here compute hash of artifacts only
4. join the initial hash of src with new hash of artifacts
___
*[`build/coreum/wasm.go` line 160 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3D8A70d5TzXQ5j-rO:-NY3D8A70d5TzXQ5j-rP:beks71q) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L160)):*
> ```Go
> 
> func replaceFileContent(codeHashesFile *os.File, codeHashesBytes []byte) error {
> 	if err := codeHashesFile.Truncate(0); err != nil {
> ```

`os.WriteFile` does everything

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 90 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3Bia8C4WIBhsMrY7W:-NY3IXkU1Y7fxy2l2YXt:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L90)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need 0
</blockquote></details>

Done.
___
*[`build/coreum/wasm.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3CkR4ETLRfQRn5bRR:-NY3J1jKE8sjOWNho03Y:b-a3e6km) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Compute hash of the dir to compare only if item does not exist in the map
</blockquote></details>

The comment isn't clear. We need to compute the hash anyways. 
___
*[`build/coreum/wasm.go` line 126 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3DRvWCtJSFPoWtYtf:-NY3IrUG609YC1MKhxEM:b-g6niko) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L126)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

here you don't need to compute the hash of all files, only artifacts:
1. at the beginning of the function compute hash of src and artifacts separately
2. join those two hashes into a single one
3. here compute hash of artifacts only
4. join the initial hash of src with new hash of artifacts
</blockquote></details>

I don't see any purpose to overcomplicating the logic by splitting it into two different functions, the current function covers diff logic fully.  
___
*[`build/coreum/wasm.go` line 160 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3D8A70d5TzXQ5j-rO:-NY3IISz2Z3zHP91GI5X:b-lbzekb) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L160)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`os.WriteFile` does everything
</blockquote></details>

`os.WriteFile` uses the file path but I already have opened file, so do need to close it, and call the `os.WriteFile`.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3CkR4ETLRfQRn5bRR:-NY3L1o29ix1wl4730US:b26ryg6) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The comment isn't clear. We need to compute the hash anyways. 
</blockquote></details>

If hash for the contract is not in map, you don't need to compute the hash above because you need to recompile anyway
___
*[`build/coreum/wasm.go` line 126 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3DRvWCtJSFPoWtYtf:-NY3LQnb-5DVDjaJWyKD:bbu6uoo) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L126)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't see any purpose to overcomplicating the logic by splitting it into two different functions, the current function covers diff logic fully.  
</blockquote></details>

But you may save on computing hash on `src` dir twice

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3CkR4ETLRfQRn5bRR:-NY3QiykEZnQfFaFpMHx:b-o0p3ov) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

To understand that `If hash for the contract is not in map` I need to compute the hash. 
</blockquote></details>

No: `storedCodeHashes[absPathHash]` - you use path hash here, not content hash.
___
*[`build/coreum/wasm.go` line 126 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3DRvWCtJSFPoWtYtf:-NY3QvVBCKeO94MYS40y:b2o8egi) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L126)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see, but you won'r see the difference so IMO no need to make it more complicated. 
</blockquote></details>

I don't see how this solution is more complicated. You anyway compute the hash for both dirs separately and join them together. So no extra code is required - just rearranging it a bit.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3CkR4ETLRfQRn5bRR:-NY3TBki3QYx0R-IhUob:b-7lvd9e) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No: `storedCodeHashes[absPathHash]` - you use path hash here, not content hash.
</blockquote></details>

I see what you mean. Updated.
___
*[`build/coreum/wasm.go` line 126 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NY3DRvWCtJSFPoWtYtf:-NY3_SXH9D4mukt-4GmL:b-rmd0tb) ([raw file](https://github.com/CoreumFoundation/crust/blob/0d8b8263827103d94e1db33eeaa4c5ce6d76a796/build/coreum/wasm.go#L126)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see how this solution is more complicated. You anyway compute the hash for both dirs separately and join them together. So no extra code is required - just rearranging it a bit.
</blockquote></details>

Updated. Hope your computer will feel better now on the hash computation :-)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 158 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYHHeH24CA2cSjDQOw0:-NYHHeH24CA2cSjDQOw1:b-cr451z) ([raw file](https://github.com/CoreumFoundation/crust/blob/0e67bc7bd0da6220042d4af141de828c5cf0e31f/build/coreum/wasm.go#L158)):*
> ```Go
> }
> 
> func joinHashes(hashes ...[]byte) string {
> ```

`computeContractSrcHash` and `computeContractArtifactsHash` produce strings so strings should be taken here:

```go
fmt.Sprintf("%x", sha256.Sum256([]byte(strings.Join(hashes, ""))))
```
___
*[`build/coreum/wasm.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYHHAKu4GSCPNUHCBcV:-NYHHAKu4GSCPNUHCBcW:ba3fwi3) ([raw file](https://github.com/CoreumFoundation/crust/blob/0e67bc7bd0da6220042d4af141de828c5cf0e31f/build/coreum/wasm.go#L165)):*
> ```Go
> 	artifactsPath := filepath.Join(path, "artifacts")
> 	var artifactsHash string
> 	if _, err := os.Stat(artifactsPath); os.IsNotExist(err) {
> ```

Do you need to call `os.Stat`? Doesn't `dirhash.HashDir` return an error if dir is missing?
___
*[`build/coreum/wasm.go` line 166 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYHGZsqBrqYFO_JwELL:-NYHGZsrEYsjtTUlXN6p:biqsjfn) ([raw file](https://github.com/CoreumFoundation/crust/blob/0e67bc7bd0da6220042d4af141de828c5cf0e31f/build/coreum/wasm.go#L166)):*
> ```Go
> 	var artifactsHash string
> 	if _, err := os.Stat(artifactsPath); os.IsNotExist(err) {
> 		artifactsHash, err = dirhash.HashDir(filepath.Join(path, "src"), "", dirhash.Hash1)
> ```

If it does not exist simply `return "", nil`. Or error might be returned and checked later. Because before compilation this dir might not exist but after compilation it should. So after the compilation the logic of `computeContractSrcHash` should be used.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 158 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYHHeH24CA2cSjDQOw0:-NYHNUp4AnR6aykP_a7Y:b-896fix) ([raw file](https://github.com/CoreumFoundation/crust/blob/0e67bc7bd0da6220042d4af141de828c5cf0e31f/build/coreum/wasm.go#L158)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`computeContractSrcHash` and `computeContractArtifactsHash` produce strings so strings should be taken here:

```go
fmt.Sprintf("%x", sha256.Sum256([]byte(strings.Join(hashes, ""))))
```
</blockquote></details>

Done.
___
*[`build/coreum/wasm.go` line 165 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYHHAKu4GSCPNUHCBcV:-NYHQjBKEW6F2kIJZx74:b1xcvud) ([raw file](https://github.com/CoreumFoundation/crust/blob/0e67bc7bd0da6220042d4af141de828c5cf0e31f/build/coreum/wasm.go#L165)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you need to call `os.Stat`? Doesn't `dirhash.HashDir` return an error if dir is missing?
</blockquote></details>

Update to handle the error form the `dirhash.HashDir`
___
*[`build/coreum/wasm.go` line 166 at r3](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYHGZsqBrqYFO_JwELL:-NYHRoB11bSZJuOBM0II:bjx9do3) ([raw file](https://github.com/CoreumFoundation/crust/blob/0e67bc7bd0da6220042d4af141de828c5cf0e31f/build/coreum/wasm.go#L166)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If it does not exist simply `return "", nil`. Or error might be returned and checked later. Because before compilation this dir might not exist but after compilation it should. So after the compilation the logic of `computeContractSrcHash` should be used.
</blockquote></details>

Updated, added additional check for the none empty artifacts folder.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/coreum/wasm.go` line 175 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYI0cRW6CEMZJGafOJO:-NYI0cRW6CEMZJGafOJP:bl3ge72) ([raw file](https://github.com/CoreumFoundation/crust/blob/c3c0aed929a010dd49dc023818c12edd7d8d1edd/build/coreum/wasm.go#L175)):*
> ```Go
> 
> func joinHashes(hashes ...string) string {
> 	return fmt.Sprintf("%x", strings.Join(hashes, ""))
> ```

`return strings.Join(hashes, "")` or `return fmt.Sprintf("%x", sha256.Sum256(\[\]byte(strings.Join(hashes, ""))))` if you want to limit it to 32 bytes.

`return fmt.Sprintf("%x", strings.Join(hashes, ""))` doesn't make sense because strings are already hex-encoded

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/226)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`build/coreum/wasm.go` line 175 at r4](https://reviewable.io/reviews/CoreumFoundation/crust/226#-NYI0cRW6CEMZJGafOJO:-NYIK1-uB_LEITCcIz8r:b-hu3utv) ([raw file](https://github.com/CoreumFoundation/crust/blob/c3c0aed929a010dd49dc023818c12edd7d8d1edd/build/coreum/wasm.go#L175)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`return strings.Join(hashes, "")` or `return fmt.Sprintf("%x", sha256.Sum256(\[\]byte(strings.Join(hashes, ""))))` if you want to limit it to 32 bytes.

`return fmt.Sprintf("%x", strings.Join(hashes, ""))` doesn't make sense because strings are already hex-encoded
</blockquote></details>

Removed that func to use `+` instead.

**Pull request merged**
