### PR TITLE
Tag released image with the username and stop tagging them with znet tag

### PR DESCRIPTION
**Pull request by wojtek-coreum**
- image to be pushed is tagged using `<username>/<imagename>:<tag>`.
- those images are not tagged with `znet`

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/docker/docker.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/198#-NU6W81N9BpSE6PhjO8v:-NU6W81N9BpSE6PhjO8w:b-bu8dvw) ([raw file](https://github.com/CoreumFoundation/crust/blob/ff74900e4af140cb79df3bc8a42f4f10596cf971/build/docker/docker.go#L59)):*
> ```Go
> 
> 	// Tags to add to the image, despite standard ones (commit hash, version)
> 	Tags []string
> ```

I thought that tag for docker images is `user/my-image:other`
But probably these word is used interchangeably to identify both full tag & the last part after : 

Maybe lets call this field `VersionTags` to have less confusion ?

If we agree with this approach then also: ZNetTag -> ZNetVersionTag
___
*[`build/docker/docker.go` line 134 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/198#-NU6Y86s1CLnAn6hKg9j:-NU6Y86s1CLnAn6hKg9k:b-rx7ff5) ([raw file](https://github.com/CoreumFoundation/crust/blob/ff74900e4af140cb79df3bc8a42f4f10596cf971/build/docker/docker.go#L134)):*
> ```Go
> 	}
> 
> 	tags := append([]string{}, input.otherTags...)
> ```

minor: I guess this is a trick to avoid having 2 lines & using copy ?)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/docker/docker.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/198#-NU6W81N9BpSE6PhjO8v:-NU6agBl2mb2wrANqvrh:b-v4qdyh) ([raw file](https://github.com/CoreumFoundation/crust/blob/ff74900e4af140cb79df3bc8a42f4f10596cf971/build/docker/docker.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought that tag for docker images is `user/my-image:other`
But probably these word is used interchangeably to identify both full tag & the last part after : 

Maybe lets call this field `VersionTags` to have less confusion ?

If we agree with this approach then also: ZNetTag -> ZNetVersionTag
</blockquote></details>

Technically you are right but as you mentioned the last part also is called "tag" often
___
*[`build/docker/docker.go` line 134 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/198#-NU6Y86s1CLnAn6hKg9j:-NU6auJj7OWaHQmCsz38:beqcm42) ([raw file](https://github.com/CoreumFoundation/crust/blob/ff74900e4af140cb79df3bc8a42f4f10596cf971/build/docker/docker.go#L134)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: I guess this is a trick to avoid having 2 lines & using copy ?)
</blockquote></details>

sth like that

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`build/docker/docker.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/198#-NU6W81N9BpSE6PhjO8v:-NU6d4AyDpw27cKrSdG_:boedhgw) ([raw file](https://github.com/CoreumFoundation/crust/blob/ff74900e4af140cb79df3bc8a42f4f10596cf971/build/docker/docker.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Technically you are right but as you mentioned the last part also is called "tag" often
</blockquote></details>

don't you think that naming it versionTag here & in related places will make it more clear ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`build/docker/docker.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/198#-NU6W81N9BpSE6PhjO8v:-NU6nVshABb32jR2yR1e:b-ya7r7b) ([raw file](https://github.com/CoreumFoundation/crust/blob/ff74900e4af140cb79df3bc8a42f4f10596cf971/build/docker/docker.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

don't you think that naming it versionTag here & in related places will make it more clear ?
</blockquote></details>

Renamed it to version

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
