### PR TITLE
Replace BinOutputPath & Parameters & Tags etc with Flags & Envs

### PR DESCRIPTION
**Pull request by ysv**
# Description

Example of usage: https://github.com/CoreumFoundation/coreum/pull/783

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`build/golang/go.go` line 169 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGMa-f2C3aH6bRbior:-NrGMa-f2C3aH6bRbios:b-hibwc8) ([raw file](https://github.com/CoreumFoundation/crust/blob/c106a0cf1667e9ea5aad56a898e491eff710d60e/build/golang/go.go#L169)):*
> ```Go
> 	runArgs = append(runArgs, args...)
> 
> 	fmt.Println(exec.Command("docker", runArgs...).String())
> ```

@wojtek-coreum almost each time I do changes in crust I add log line here to see what is the resulting command produced to debug or try to run in locally

Shall we add log here ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGS7GK3XvBuUiUmwrl:-NrGS7GK3XvBuUiUmwrm:b9w93ax) (no related file):*
I'm against this PR. I accepted the one introducing this for `-cover` to see if this is good or not. Now I clearly see this decreases readability. Previous approach was very clear, fields were used to communicate user's intentions and there was one place converting those intentions to CLI flags. Now those flags are everywhere and every time I need to think what `-o` means.

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGS7GK3XvBuUiUmwrl:-NrGSzrZ2tzPe6gkOKXh:bpgeouz) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I'm against this PR. I accepted the one introducing this for `-cover` to see if this is good or not. Now I clearly see this decreases readability. Previous approach was very clear, fields were used to communicate user's intentions and there was one place converting those intentions to CLI flags. Now those flags are everywhere and every time I need to think what `-o` means.
</blockquote></details>

I would prefer to go one step back and convert `-cover` to another field instead.

___

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGS7GK3XvBuUiUmwrl:-NrGTn7oBhfMveyrpFiZ:bisjm6r) (no related file):*
> very time I need to think what `-o` means.

I think it is super common knowledge like 2+2 you don't even need to calculate it. 
But I can move this to const so we preserve the name.

1. but we agreed back then to do this refactoring and you also approved it

2. The benefit is that this interface is fully flexible and supports all the features in elegant way with just 2 attributes. And with your approach we will have to extend BinaryBuildConfig more and more

3. Vice versa for me I prefer to see flags which I pass for binary build directly instead of looking for it deep inside crust. It is always very tricky to find what is going on inside.

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`build/golang/go.go` line 169 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGMa-f2C3aH6bRbior:-NrKDNJx-tqdAdWnMHYf:buu2tdn) ([raw file](https://github.com/CoreumFoundation/crust/blob/c106a0cf1667e9ea5aad56a898e491eff710d60e/build/golang/go.go#L169)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum almost each time I do changes in crust I add log line here to see what is the resulting command produced to debug or try to run in locally

Shall we add log here ?
</blockquote></details>

The loggger should be in the context, so you can use it instead of `fmt`

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGS7GK3XvBuUiUmwrl:-NrjYZau5GO_yZLHWUnG:b98j6qu) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> very time I need to think what `-o` means.

I think it is super common knowledge like 2+2 you don't even need to calculate it. 
But I can move this to const so we preserve the name.

1. but we agreed back then to do this refactoring and you also approved it

2. The benefit is that this interface is fully flexible and supports all the features in elegant way with just 2 attributes. And with your approach we will have to extend BinaryBuildConfig more and more

3. Vice versa for me I prefer to see flags which I pass for binary build directly instead of looking for it deep inside crust. It is always very tricky to find what is going on inside.
</blockquote></details>

I went through code and decided to keep it as it is now (everything in Flags & Envs). 
Because I didn't find any extra logic for `CgoEnabled bool` except setting this env variable `CGO\_ENABLED=1` so IMO it is better to keep it in envs. 

@dzmitryhil @miladz68 are you aware of any extra logic related to CGO ?

___
___
*[`build/golang/go.go` line 169 at r1](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGMa-f2C3aH6bRbior:-NrjX7--3pX57XxZyGvU:bb6un1j) ([raw file](https://github.com/CoreumFoundation/crust/blob/c106a0cf1667e9ea5aad56a898e491eff710d60e/build/golang/go.go#L169)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The loggger should be in the context, so you can use it instead of `fmt`
</blockquote></details>

Done

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/crust/362#-NrGS7GK3XvBuUiUmwrl:-Nrk_AjNDyH370bA1ISn:b1mlcv7) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I went through code and decided to keep it as it is now (everything in Flags & Envs). 
Because I didn't find any extra logic for `CgoEnabled bool` except setting this env variable `CGO\_ENABLED=1` so IMO it is better to keep it in envs. 

@dzmitryhil @miladz68 are you aware of any extra logic related to CGO ?
</blockquote></details>

Ignore my prev comment
After rebase I can see that there is a specific logic for CGO

___

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/crust/362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
